// Code generated by ent, DO NOT EDIT.

package event

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the event type in the database.
	Label = "event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOrgID holds the string denoting the org_id field in the database.
	FieldOrgID = "org_id"
	// FieldProductID holds the string denoting the product_id field in the database.
	FieldProductID = "product_id"
	// FieldEventID holds the string denoting the event_id field in the database.
	FieldEventID = "event_id"
	// FieldSessionID holds the string denoting the session_id field in the database.
	FieldSessionID = "session_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldEventType holds the string denoting the event_type field in the database.
	FieldEventType = "event_type"
	// FieldEventName holds the string denoting the event_name field in the database.
	FieldEventName = "event_name"
	// FieldTimestamp holds the string denoting the timestamp field in the database.
	FieldTimestamp = "timestamp"
	// FieldSequence holds the string denoting the sequence field in the database.
	FieldSequence = "sequence"
	// FieldPagePath holds the string denoting the page_path field in the database.
	FieldPagePath = "page_path"
	// FieldPageTitle holds the string denoting the page_title field in the database.
	FieldPageTitle = "page_title"
	// FieldPageURL holds the string denoting the page_url field in the database.
	FieldPageURL = "page_url"
	// FieldPageReferrer holds the string denoting the page_referrer field in the database.
	FieldPageReferrer = "page_referrer"
	// FieldUIComponentName holds the string denoting the ui_component_name field in the database.
	FieldUIComponentName = "ui_component_name"
	// FieldUIComponentPath holds the string denoting the ui_component_path field in the database.
	FieldUIComponentPath = "ui_component_path"
	// FieldUIComponentType holds the string denoting the ui_component_type field in the database.
	FieldUIComponentType = "ui_component_type"
	// FieldUIAction holds the string denoting the ui_action field in the database.
	FieldUIAction = "ui_action"
	// FieldUIElement holds the string denoting the ui_element field in the database.
	FieldUIElement = "ui_element"
	// FieldUIElementText holds the string denoting the ui_element_text field in the database.
	FieldUIElementText = "ui_element_text"
	// FieldUIViewport holds the string denoting the ui_viewport field in the database.
	FieldUIViewport = "ui_viewport"
	// FieldUIScrollPosition holds the string denoting the ui_scroll_position field in the database.
	FieldUIScrollPosition = "ui_scroll_position"
	// FieldUIStateKey holds the string denoting the ui_state_key field in the database.
	FieldUIStateKey = "ui_state_key"
	// FieldUIStateBefore holds the string denoting the ui_state_before field in the database.
	FieldUIStateBefore = "ui_state_before"
	// FieldUIStateAfter holds the string denoting the ui_state_after field in the database.
	FieldUIStateAfter = "ui_state_after"
	// FieldUIStateChangeType holds the string denoting the ui_state_change_type field in the database.
	FieldUIStateChangeType = "ui_state_change_type"
	// FieldJourneyID holds the string denoting the journey_id field in the database.
	FieldJourneyID = "journey_id"
	// FieldJourneyStepID holds the string denoting the journey_step_id field in the database.
	FieldJourneyStepID = "journey_step_id"
	// FieldJourneyStepName holds the string denoting the journey_step_name field in the database.
	FieldJourneyStepName = "journey_step_name"
	// FieldConversionStatus holds the string denoting the conversion_status field in the database.
	FieldConversionStatus = "conversion_status"
	// FieldAPIMethod holds the string denoting the api_method field in the database.
	FieldAPIMethod = "api_method"
	// FieldAPIPath holds the string denoting the api_path field in the database.
	FieldAPIPath = "api_path"
	// FieldAPIStatusCode holds the string denoting the api_status_code field in the database.
	FieldAPIStatusCode = "api_status_code"
	// FieldAPIDurationMs holds the string denoting the api_duration_ms field in the database.
	FieldAPIDurationMs = "api_duration_ms"
	// FieldErrorType holds the string denoting the error_type field in the database.
	FieldErrorType = "error_type"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldErrorStack holds the string denoting the error_stack field in the database.
	FieldErrorStack = "error_stack"
	// FieldErrorComponent holds the string denoting the error_component field in the database.
	FieldErrorComponent = "error_component"
	// FieldPerformanceLcpMs holds the string denoting the performance_lcp_ms field in the database.
	FieldPerformanceLcpMs = "performance_lcp_ms"
	// FieldPerformanceFidMs holds the string denoting the performance_fid_ms field in the database.
	FieldPerformanceFidMs = "performance_fid_ms"
	// FieldPerformanceCls holds the string denoting the performance_cls field in the database.
	FieldPerformanceCls = "performance_cls"
	// FieldPerformanceTtfbMs holds the string denoting the performance_ttfb_ms field in the database.
	FieldPerformanceTtfbMs = "performance_ttfb_ms"
	// FieldSnapshotURL holds the string denoting the snapshot_url field in the database.
	FieldSnapshotURL = "snapshot_url"
	// FieldSnapshotViewport holds the string denoting the snapshot_viewport field in the database.
	FieldSnapshotViewport = "snapshot_viewport"
	// FieldDurationMs holds the string denoting the duration_ms field in the database.
	FieldDurationMs = "duration_ms"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeProduct holds the string denoting the product edge name in mutations.
	EdgeProduct = "product"
	// EdgeJourney holds the string denoting the journey edge name in mutations.
	EdgeJourney = "journey"
	// Table holds the table name of the event in the database.
	Table = "events"
	// ProductTable is the table that holds the product relation/edge.
	ProductTable = "events"
	// ProductInverseTable is the table name for the Product entity.
	// It exists in this package in order to avoid circular dependency with the "product" package.
	ProductInverseTable = "products"
	// ProductColumn is the table column denoting the product relation/edge.
	ProductColumn = "product_id"
	// JourneyTable is the table that holds the journey relation/edge.
	JourneyTable = "events"
	// JourneyInverseTable is the table name for the Journey entity.
	// It exists in this package in order to avoid circular dependency with the "journey" package.
	JourneyInverseTable = "journeys"
	// JourneyColumn is the table column denoting the journey relation/edge.
	JourneyColumn = "journey_id"
)

// Columns holds all SQL columns for event fields.
var Columns = []string{
	FieldID,
	FieldOrgID,
	FieldProductID,
	FieldEventID,
	FieldSessionID,
	FieldUserID,
	FieldEventType,
	FieldEventName,
	FieldTimestamp,
	FieldSequence,
	FieldPagePath,
	FieldPageTitle,
	FieldPageURL,
	FieldPageReferrer,
	FieldUIComponentName,
	FieldUIComponentPath,
	FieldUIComponentType,
	FieldUIAction,
	FieldUIElement,
	FieldUIElementText,
	FieldUIViewport,
	FieldUIScrollPosition,
	FieldUIStateKey,
	FieldUIStateBefore,
	FieldUIStateAfter,
	FieldUIStateChangeType,
	FieldJourneyID,
	FieldJourneyStepID,
	FieldJourneyStepName,
	FieldConversionStatus,
	FieldAPIMethod,
	FieldAPIPath,
	FieldAPIStatusCode,
	FieldAPIDurationMs,
	FieldErrorType,
	FieldErrorMessage,
	FieldErrorStack,
	FieldErrorComponent,
	FieldPerformanceLcpMs,
	FieldPerformanceFidMs,
	FieldPerformanceCls,
	FieldPerformanceTtfbMs,
	FieldSnapshotURL,
	FieldSnapshotViewport,
	FieldDurationMs,
	FieldMetadata,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// EventIDValidator is a validator for the "event_id" field. It is called by the builders before save.
	EventIDValidator func(string) error
	// SessionIDValidator is a validator for the "session_id" field. It is called by the builders before save.
	SessionIDValidator func(string) error
	// UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	UserIDValidator func(string) error
	// EventNameValidator is a validator for the "event_name" field. It is called by the builders before save.
	EventNameValidator func(string) error
	// DefaultSequence holds the default value on creation for the "sequence" field.
	DefaultSequence int64
	// PagePathValidator is a validator for the "page_path" field. It is called by the builders before save.
	PagePathValidator func(string) error
	// PageTitleValidator is a validator for the "page_title" field. It is called by the builders before save.
	PageTitleValidator func(string) error
	// PageURLValidator is a validator for the "page_url" field. It is called by the builders before save.
	PageURLValidator func(string) error
	// PageReferrerValidator is a validator for the "page_referrer" field. It is called by the builders before save.
	PageReferrerValidator func(string) error
	// UIComponentNameValidator is a validator for the "ui_component_name" field. It is called by the builders before save.
	UIComponentNameValidator func(string) error
	// UIComponentPathValidator is a validator for the "ui_component_path" field. It is called by the builders before save.
	UIComponentPathValidator func(string) error
	// UIComponentTypeValidator is a validator for the "ui_component_type" field. It is called by the builders before save.
	UIComponentTypeValidator func(string) error
	// UIActionValidator is a validator for the "ui_action" field. It is called by the builders before save.
	UIActionValidator func(string) error
	// UIElementValidator is a validator for the "ui_element" field. It is called by the builders before save.
	UIElementValidator func(string) error
	// UIElementTextValidator is a validator for the "ui_element_text" field. It is called by the builders before save.
	UIElementTextValidator func(string) error
	// UIViewportValidator is a validator for the "ui_viewport" field. It is called by the builders before save.
	UIViewportValidator func(string) error
	// UIStateKeyValidator is a validator for the "ui_state_key" field. It is called by the builders before save.
	UIStateKeyValidator func(string) error
	// UIStateChangeTypeValidator is a validator for the "ui_state_change_type" field. It is called by the builders before save.
	UIStateChangeTypeValidator func(string) error
	// JourneyStepIDValidator is a validator for the "journey_step_id" field. It is called by the builders before save.
	JourneyStepIDValidator func(string) error
	// JourneyStepNameValidator is a validator for the "journey_step_name" field. It is called by the builders before save.
	JourneyStepNameValidator func(string) error
	// ConversionStatusValidator is a validator for the "conversion_status" field. It is called by the builders before save.
	ConversionStatusValidator func(string) error
	// APIMethodValidator is a validator for the "api_method" field. It is called by the builders before save.
	APIMethodValidator func(string) error
	// APIPathValidator is a validator for the "api_path" field. It is called by the builders before save.
	APIPathValidator func(string) error
	// ErrorTypeValidator is a validator for the "error_type" field. It is called by the builders before save.
	ErrorTypeValidator func(string) error
	// ErrorComponentValidator is a validator for the "error_component" field. It is called by the builders before save.
	ErrorComponentValidator func(string) error
	// SnapshotURLValidator is a validator for the "snapshot_url" field. It is called by the builders before save.
	SnapshotURLValidator func(string) error
	// SnapshotViewportValidator is a validator for the "snapshot_viewport" field. It is called by the builders before save.
	SnapshotViewportValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// EventType defines the type for the "event_type" enum field.
type EventType string

// EventType values.
const (
	EventTypePageView    EventType = "page_view"
	EventTypePageLeave   EventType = "page_leave"
	EventTypeUIClick     EventType = "ui_click"
	EventTypeUIInput     EventType = "ui_input"
	EventTypeUIScroll    EventType = "ui_scroll"
	EventTypeUIFocus     EventType = "ui_focus"
	EventTypeUIBlur      EventType = "ui_blur"
	EventTypeUISubmit    EventType = "ui_submit"
	EventTypeStateChange EventType = "state_change"
	EventTypeAPIRequest  EventType = "api_request"
	EventTypeAPIResponse EventType = "api_response"
	EventTypeJourneyStep EventType = "journey_step"
	EventTypeError       EventType = "error"
	EventTypePerformance EventType = "performance"
	EventTypeCustom      EventType = "custom"
)

func (et EventType) String() string {
	return string(et)
}

// EventTypeValidator is a validator for the "event_type" field enum values. It is called by the builders before save.
func EventTypeValidator(et EventType) error {
	switch et {
	case EventTypePageView, EventTypePageLeave, EventTypeUIClick, EventTypeUIInput, EventTypeUIScroll, EventTypeUIFocus, EventTypeUIBlur, EventTypeUISubmit, EventTypeStateChange, EventTypeAPIRequest, EventTypeAPIResponse, EventTypeJourneyStep, EventTypeError, EventTypePerformance, EventTypeCustom:
		return nil
	default:
		return fmt.Errorf("event: invalid enum value for event_type field: %q", et)
	}
}

// OrderOption defines the ordering options for the Event queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOrgID orders the results by the org_id field.
func ByOrgID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrgID, opts...).ToFunc()
}

// ByProductID orders the results by the product_id field.
func ByProductID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProductID, opts...).ToFunc()
}

// ByEventID orders the results by the event_id field.
func ByEventID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventID, opts...).ToFunc()
}

// BySessionID orders the results by the session_id field.
func BySessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByEventType orders the results by the event_type field.
func ByEventType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventType, opts...).ToFunc()
}

// ByEventName orders the results by the event_name field.
func ByEventName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventName, opts...).ToFunc()
}

// ByTimestamp orders the results by the timestamp field.
func ByTimestamp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimestamp, opts...).ToFunc()
}

// BySequence orders the results by the sequence field.
func BySequence(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSequence, opts...).ToFunc()
}

// ByPagePath orders the results by the page_path field.
func ByPagePath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPagePath, opts...).ToFunc()
}

// ByPageTitle orders the results by the page_title field.
func ByPageTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPageTitle, opts...).ToFunc()
}

// ByPageURL orders the results by the page_url field.
func ByPageURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPageURL, opts...).ToFunc()
}

// ByPageReferrer orders the results by the page_referrer field.
func ByPageReferrer(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPageReferrer, opts...).ToFunc()
}

// ByUIComponentName orders the results by the ui_component_name field.
func ByUIComponentName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUIComponentName, opts...).ToFunc()
}

// ByUIComponentPath orders the results by the ui_component_path field.
func ByUIComponentPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUIComponentPath, opts...).ToFunc()
}

// ByUIComponentType orders the results by the ui_component_type field.
func ByUIComponentType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUIComponentType, opts...).ToFunc()
}

// ByUIAction orders the results by the ui_action field.
func ByUIAction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUIAction, opts...).ToFunc()
}

// ByUIElement orders the results by the ui_element field.
func ByUIElement(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUIElement, opts...).ToFunc()
}

// ByUIElementText orders the results by the ui_element_text field.
func ByUIElementText(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUIElementText, opts...).ToFunc()
}

// ByUIViewport orders the results by the ui_viewport field.
func ByUIViewport(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUIViewport, opts...).ToFunc()
}

// ByUIScrollPosition orders the results by the ui_scroll_position field.
func ByUIScrollPosition(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUIScrollPosition, opts...).ToFunc()
}

// ByUIStateKey orders the results by the ui_state_key field.
func ByUIStateKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUIStateKey, opts...).ToFunc()
}

// ByUIStateBefore orders the results by the ui_state_before field.
func ByUIStateBefore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUIStateBefore, opts...).ToFunc()
}

// ByUIStateAfter orders the results by the ui_state_after field.
func ByUIStateAfter(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUIStateAfter, opts...).ToFunc()
}

// ByUIStateChangeType orders the results by the ui_state_change_type field.
func ByUIStateChangeType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUIStateChangeType, opts...).ToFunc()
}

// ByJourneyID orders the results by the journey_id field.
func ByJourneyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJourneyID, opts...).ToFunc()
}

// ByJourneyStepID orders the results by the journey_step_id field.
func ByJourneyStepID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJourneyStepID, opts...).ToFunc()
}

// ByJourneyStepName orders the results by the journey_step_name field.
func ByJourneyStepName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJourneyStepName, opts...).ToFunc()
}

// ByConversionStatus orders the results by the conversion_status field.
func ByConversionStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConversionStatus, opts...).ToFunc()
}

// ByAPIMethod orders the results by the api_method field.
func ByAPIMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIMethod, opts...).ToFunc()
}

// ByAPIPath orders the results by the api_path field.
func ByAPIPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIPath, opts...).ToFunc()
}

// ByAPIStatusCode orders the results by the api_status_code field.
func ByAPIStatusCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIStatusCode, opts...).ToFunc()
}

// ByAPIDurationMs orders the results by the api_duration_ms field.
func ByAPIDurationMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIDurationMs, opts...).ToFunc()
}

// ByErrorType orders the results by the error_type field.
func ByErrorType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorType, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByErrorStack orders the results by the error_stack field.
func ByErrorStack(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorStack, opts...).ToFunc()
}

// ByErrorComponent orders the results by the error_component field.
func ByErrorComponent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorComponent, opts...).ToFunc()
}

// ByPerformanceLcpMs orders the results by the performance_lcp_ms field.
func ByPerformanceLcpMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPerformanceLcpMs, opts...).ToFunc()
}

// ByPerformanceFidMs orders the results by the performance_fid_ms field.
func ByPerformanceFidMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPerformanceFidMs, opts...).ToFunc()
}

// ByPerformanceCls orders the results by the performance_cls field.
func ByPerformanceCls(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPerformanceCls, opts...).ToFunc()
}

// ByPerformanceTtfbMs orders the results by the performance_ttfb_ms field.
func ByPerformanceTtfbMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPerformanceTtfbMs, opts...).ToFunc()
}

// BySnapshotURL orders the results by the snapshot_url field.
func BySnapshotURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSnapshotURL, opts...).ToFunc()
}

// BySnapshotViewport orders the results by the snapshot_viewport field.
func BySnapshotViewport(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSnapshotViewport, opts...).ToFunc()
}

// ByDurationMs orders the results by the duration_ms field.
func ByDurationMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDurationMs, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByProductField orders the results by product field.
func ByProductField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProductStep(), sql.OrderByField(field, opts...))
	}
}

// ByJourneyField orders the results by journey field.
func ByJourneyField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newJourneyStep(), sql.OrderByField(field, opts...))
	}
}
func newProductStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProductInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProductTable, ProductColumn),
	)
}
func newJourneyStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(JourneyInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, JourneyTable, JourneyColumn),
	)
}
