// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/plexusone/productgraph/ent/capability"
	"github.com/plexusone/productgraph/ent/feature"
	"github.com/plexusone/productgraph/ent/predicate"
	"github.com/plexusone/productgraph/ent/product"
)

// CapabilityQuery is the builder for querying Capability entities.
type CapabilityQuery struct {
	config
	ctx          *QueryContext
	order        []capability.OrderOption
	inters       []Interceptor
	predicates   []predicate.Capability
	withProduct  *ProductQuery
	withFeatures *FeatureQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CapabilityQuery builder.
func (_q *CapabilityQuery) Where(ps ...predicate.Capability) *CapabilityQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *CapabilityQuery) Limit(limit int) *CapabilityQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *CapabilityQuery) Offset(offset int) *CapabilityQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *CapabilityQuery) Unique(unique bool) *CapabilityQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *CapabilityQuery) Order(o ...capability.OrderOption) *CapabilityQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryProduct chains the current query on the "product" edge.
func (_q *CapabilityQuery) QueryProduct() *ProductQuery {
	query := (&ProductClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(capability.Table, capability.FieldID, selector),
			sqlgraph.To(product.Table, product.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, capability.ProductTable, capability.ProductColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryFeatures chains the current query on the "features" edge.
func (_q *CapabilityQuery) QueryFeatures() *FeatureQuery {
	query := (&FeatureClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(capability.Table, capability.FieldID, selector),
			sqlgraph.To(feature.Table, feature.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, capability.FeaturesTable, capability.FeaturesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Capability entity from the query.
// Returns a *NotFoundError when no Capability was found.
func (_q *CapabilityQuery) First(ctx context.Context) (*Capability, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{capability.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *CapabilityQuery) FirstX(ctx context.Context) *Capability {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Capability ID from the query.
// Returns a *NotFoundError when no Capability ID was found.
func (_q *CapabilityQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{capability.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *CapabilityQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Capability entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Capability entity is found.
// Returns a *NotFoundError when no Capability entities are found.
func (_q *CapabilityQuery) Only(ctx context.Context) (*Capability, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{capability.Label}
	default:
		return nil, &NotSingularError{capability.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *CapabilityQuery) OnlyX(ctx context.Context) *Capability {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Capability ID in the query.
// Returns a *NotSingularError when more than one Capability ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *CapabilityQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{capability.Label}
	default:
		err = &NotSingularError{capability.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *CapabilityQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Capabilities.
func (_q *CapabilityQuery) All(ctx context.Context) ([]*Capability, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Capability, *CapabilityQuery]()
	return withInterceptors[[]*Capability](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *CapabilityQuery) AllX(ctx context.Context) []*Capability {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Capability IDs.
func (_q *CapabilityQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(capability.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *CapabilityQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *CapabilityQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*CapabilityQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *CapabilityQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *CapabilityQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *CapabilityQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CapabilityQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *CapabilityQuery) Clone() *CapabilityQuery {
	if _q == nil {
		return nil
	}
	return &CapabilityQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]capability.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.Capability{}, _q.predicates...),
		withProduct:  _q.withProduct.Clone(),
		withFeatures: _q.withFeatures.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithProduct tells the query-builder to eager-load the nodes that are connected to
// the "product" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CapabilityQuery) WithProduct(opts ...func(*ProductQuery)) *CapabilityQuery {
	query := (&ProductClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProduct = query
	return _q
}

// WithFeatures tells the query-builder to eager-load the nodes that are connected to
// the "features" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CapabilityQuery) WithFeatures(opts ...func(*FeatureQuery)) *CapabilityQuery {
	query := (&FeatureClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withFeatures = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		OrgID uuid.UUID `json:"org_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Capability.Query().
//		GroupBy(capability.FieldOrgID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *CapabilityQuery) GroupBy(field string, fields ...string) *CapabilityGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CapabilityGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = capability.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		OrgID uuid.UUID `json:"org_id,omitempty"`
//	}
//
//	client.Capability.Query().
//		Select(capability.FieldOrgID).
//		Scan(ctx, &v)
func (_q *CapabilityQuery) Select(fields ...string) *CapabilitySelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &CapabilitySelect{CapabilityQuery: _q}
	sbuild.label = capability.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CapabilitySelect configured with the given aggregations.
func (_q *CapabilityQuery) Aggregate(fns ...AggregateFunc) *CapabilitySelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *CapabilityQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !capability.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *CapabilityQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Capability, error) {
	var (
		nodes       = []*Capability{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withProduct != nil,
			_q.withFeatures != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Capability).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Capability{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withProduct; query != nil {
		if err := _q.loadProduct(ctx, query, nodes, nil,
			func(n *Capability, e *Product) { n.Edges.Product = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withFeatures; query != nil {
		if err := _q.loadFeatures(ctx, query, nodes,
			func(n *Capability) { n.Edges.Features = []*Feature{} },
			func(n *Capability, e *Feature) { n.Edges.Features = append(n.Edges.Features, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *CapabilityQuery) loadProduct(ctx context.Context, query *ProductQuery, nodes []*Capability, init func(*Capability), assign func(*Capability, *Product)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Capability)
	for i := range nodes {
		fk := nodes[i].ProductID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(product.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "product_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *CapabilityQuery) loadFeatures(ctx context.Context, query *FeatureQuery, nodes []*Capability, init func(*Capability), assign func(*Capability, *Feature)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Capability)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(feature.FieldCapabilityID)
	}
	query.Where(predicate.Feature(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(capability.FeaturesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.CapabilityID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "capability_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *CapabilityQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *CapabilityQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(capability.Table, capability.Columns, sqlgraph.NewFieldSpec(capability.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, capability.FieldID)
		for i := range fields {
			if fields[i] != capability.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withProduct != nil {
			_spec.Node.AddColumnOnce(capability.FieldProductID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *CapabilityQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(capability.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = capability.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CapabilityGroupBy is the group-by builder for Capability entities.
type CapabilityGroupBy struct {
	selector
	build *CapabilityQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *CapabilityGroupBy) Aggregate(fns ...AggregateFunc) *CapabilityGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *CapabilityGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CapabilityQuery, *CapabilityGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *CapabilityGroupBy) sqlScan(ctx context.Context, root *CapabilityQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CapabilitySelect is the builder for selecting fields of Capability entities.
type CapabilitySelect struct {
	*CapabilityQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *CapabilitySelect) Aggregate(fns ...AggregateFunc) *CapabilitySelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *CapabilitySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CapabilityQuery, *CapabilitySelect](ctx, _s.CapabilityQuery, _s, _s.inters, v)
}

func (_s *CapabilitySelect) sqlScan(ctx context.Context, root *CapabilityQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
