// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/plexusone/productgraph/ent/capability"
	"github.com/plexusone/productgraph/ent/feature"
	"github.com/plexusone/productgraph/ent/predicate"
	"github.com/plexusone/productgraph/ent/product"
)

// CapabilityUpdate is the builder for updating Capability entities.
type CapabilityUpdate struct {
	config
	hooks    []Hook
	mutation *CapabilityMutation
}

// Where appends a list predicates to the CapabilityUpdate builder.
func (_u *CapabilityUpdate) Where(ps ...predicate.Capability) *CapabilityUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOrgID sets the "org_id" field.
func (_u *CapabilityUpdate) SetOrgID(v uuid.UUID) *CapabilityUpdate {
	_u.mutation.SetOrgID(v)
	return _u
}

// SetNillableOrgID sets the "org_id" field if the given value is not nil.
func (_u *CapabilityUpdate) SetNillableOrgID(v *uuid.UUID) *CapabilityUpdate {
	if v != nil {
		_u.SetOrgID(*v)
	}
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *CapabilityUpdate) SetProductID(v uuid.UUID) *CapabilityUpdate {
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *CapabilityUpdate) SetNillableProductID(v *uuid.UUID) *CapabilityUpdate {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *CapabilityUpdate) SetName(v string) *CapabilityUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CapabilityUpdate) SetNillableName(v *string) *CapabilityUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *CapabilityUpdate) SetDescription(v string) *CapabilityUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *CapabilityUpdate) SetNillableDescription(v *string) *CapabilityUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *CapabilityUpdate) ClearDescription() *CapabilityUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetDisplayOrder sets the "display_order" field.
func (_u *CapabilityUpdate) SetDisplayOrder(v int) *CapabilityUpdate {
	_u.mutation.ResetDisplayOrder()
	_u.mutation.SetDisplayOrder(v)
	return _u
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_u *CapabilityUpdate) SetNillableDisplayOrder(v *int) *CapabilityUpdate {
	if v != nil {
		_u.SetDisplayOrder(*v)
	}
	return _u
}

// AddDisplayOrder adds value to the "display_order" field.
func (_u *CapabilityUpdate) AddDisplayOrder(v int) *CapabilityUpdate {
	_u.mutation.AddDisplayOrder(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CapabilityUpdate) SetUpdatedAt(v time.Time) *CapabilityUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProduct sets the "product" edge to the Product entity.
func (_u *CapabilityUpdate) SetProduct(v *Product) *CapabilityUpdate {
	return _u.SetProductID(v.ID)
}

// AddFeatureIDs adds the "features" edge to the Feature entity by IDs.
func (_u *CapabilityUpdate) AddFeatureIDs(ids ...uuid.UUID) *CapabilityUpdate {
	_u.mutation.AddFeatureIDs(ids...)
	return _u
}

// AddFeatures adds the "features" edges to the Feature entity.
func (_u *CapabilityUpdate) AddFeatures(v ...*Feature) *CapabilityUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFeatureIDs(ids...)
}

// Mutation returns the CapabilityMutation object of the builder.
func (_u *CapabilityUpdate) Mutation() *CapabilityMutation {
	return _u.mutation
}

// ClearProduct clears the "product" edge to the Product entity.
func (_u *CapabilityUpdate) ClearProduct() *CapabilityUpdate {
	_u.mutation.ClearProduct()
	return _u
}

// ClearFeatures clears all "features" edges to the Feature entity.
func (_u *CapabilityUpdate) ClearFeatures() *CapabilityUpdate {
	_u.mutation.ClearFeatures()
	return _u
}

// RemoveFeatureIDs removes the "features" edge to Feature entities by IDs.
func (_u *CapabilityUpdate) RemoveFeatureIDs(ids ...uuid.UUID) *CapabilityUpdate {
	_u.mutation.RemoveFeatureIDs(ids...)
	return _u
}

// RemoveFeatures removes "features" edges to Feature entities.
func (_u *CapabilityUpdate) RemoveFeatures(v ...*Feature) *CapabilityUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFeatureIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CapabilityUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CapabilityUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CapabilityUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CapabilityUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CapabilityUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := capability.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CapabilityUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := capability.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Capability.name": %w`, err)}
		}
	}
	if _u.mutation.ProductCleared() && len(_u.mutation.ProductIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Capability.product"`)
	}
	return nil
}

func (_u *CapabilityUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(capability.Table, capability.Columns, sqlgraph.NewFieldSpec(capability.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrgID(); ok {
		_spec.SetField(capability.FieldOrgID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(capability.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(capability.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(capability.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.DisplayOrder(); ok {
		_spec.SetField(capability.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDisplayOrder(); ok {
		_spec.AddField(capability.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(capability.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ProductCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   capability.ProductTable,
			Columns: []string{capability.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   capability.ProductTable,
			Columns: []string{capability.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FeaturesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   capability.FeaturesTable,
			Columns: []string{capability.FeaturesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(feature.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFeaturesIDs(); len(nodes) > 0 && !_u.mutation.FeaturesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   capability.FeaturesTable,
			Columns: []string{capability.FeaturesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(feature.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FeaturesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   capability.FeaturesTable,
			Columns: []string{capability.FeaturesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(feature.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{capability.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CapabilityUpdateOne is the builder for updating a single Capability entity.
type CapabilityUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CapabilityMutation
}

// SetOrgID sets the "org_id" field.
func (_u *CapabilityUpdateOne) SetOrgID(v uuid.UUID) *CapabilityUpdateOne {
	_u.mutation.SetOrgID(v)
	return _u
}

// SetNillableOrgID sets the "org_id" field if the given value is not nil.
func (_u *CapabilityUpdateOne) SetNillableOrgID(v *uuid.UUID) *CapabilityUpdateOne {
	if v != nil {
		_u.SetOrgID(*v)
	}
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *CapabilityUpdateOne) SetProductID(v uuid.UUID) *CapabilityUpdateOne {
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *CapabilityUpdateOne) SetNillableProductID(v *uuid.UUID) *CapabilityUpdateOne {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *CapabilityUpdateOne) SetName(v string) *CapabilityUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CapabilityUpdateOne) SetNillableName(v *string) *CapabilityUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *CapabilityUpdateOne) SetDescription(v string) *CapabilityUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *CapabilityUpdateOne) SetNillableDescription(v *string) *CapabilityUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *CapabilityUpdateOne) ClearDescription() *CapabilityUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetDisplayOrder sets the "display_order" field.
func (_u *CapabilityUpdateOne) SetDisplayOrder(v int) *CapabilityUpdateOne {
	_u.mutation.ResetDisplayOrder()
	_u.mutation.SetDisplayOrder(v)
	return _u
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_u *CapabilityUpdateOne) SetNillableDisplayOrder(v *int) *CapabilityUpdateOne {
	if v != nil {
		_u.SetDisplayOrder(*v)
	}
	return _u
}

// AddDisplayOrder adds value to the "display_order" field.
func (_u *CapabilityUpdateOne) AddDisplayOrder(v int) *CapabilityUpdateOne {
	_u.mutation.AddDisplayOrder(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CapabilityUpdateOne) SetUpdatedAt(v time.Time) *CapabilityUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProduct sets the "product" edge to the Product entity.
func (_u *CapabilityUpdateOne) SetProduct(v *Product) *CapabilityUpdateOne {
	return _u.SetProductID(v.ID)
}

// AddFeatureIDs adds the "features" edge to the Feature entity by IDs.
func (_u *CapabilityUpdateOne) AddFeatureIDs(ids ...uuid.UUID) *CapabilityUpdateOne {
	_u.mutation.AddFeatureIDs(ids...)
	return _u
}

// AddFeatures adds the "features" edges to the Feature entity.
func (_u *CapabilityUpdateOne) AddFeatures(v ...*Feature) *CapabilityUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFeatureIDs(ids...)
}

// Mutation returns the CapabilityMutation object of the builder.
func (_u *CapabilityUpdateOne) Mutation() *CapabilityMutation {
	return _u.mutation
}

// ClearProduct clears the "product" edge to the Product entity.
func (_u *CapabilityUpdateOne) ClearProduct() *CapabilityUpdateOne {
	_u.mutation.ClearProduct()
	return _u
}

// ClearFeatures clears all "features" edges to the Feature entity.
func (_u *CapabilityUpdateOne) ClearFeatures() *CapabilityUpdateOne {
	_u.mutation.ClearFeatures()
	return _u
}

// RemoveFeatureIDs removes the "features" edge to Feature entities by IDs.
func (_u *CapabilityUpdateOne) RemoveFeatureIDs(ids ...uuid.UUID) *CapabilityUpdateOne {
	_u.mutation.RemoveFeatureIDs(ids...)
	return _u
}

// RemoveFeatures removes "features" edges to Feature entities.
func (_u *CapabilityUpdateOne) RemoveFeatures(v ...*Feature) *CapabilityUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFeatureIDs(ids...)
}

// Where appends a list predicates to the CapabilityUpdate builder.
func (_u *CapabilityUpdateOne) Where(ps ...predicate.Capability) *CapabilityUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CapabilityUpdateOne) Select(field string, fields ...string) *CapabilityUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Capability entity.
func (_u *CapabilityUpdateOne) Save(ctx context.Context) (*Capability, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CapabilityUpdateOne) SaveX(ctx context.Context) *Capability {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CapabilityUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CapabilityUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CapabilityUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := capability.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CapabilityUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := capability.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Capability.name": %w`, err)}
		}
	}
	if _u.mutation.ProductCleared() && len(_u.mutation.ProductIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Capability.product"`)
	}
	return nil
}

func (_u *CapabilityUpdateOne) sqlSave(ctx context.Context) (_node *Capability, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(capability.Table, capability.Columns, sqlgraph.NewFieldSpec(capability.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Capability.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, capability.FieldID)
		for _, f := range fields {
			if !capability.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != capability.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrgID(); ok {
		_spec.SetField(capability.FieldOrgID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(capability.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(capability.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(capability.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.DisplayOrder(); ok {
		_spec.SetField(capability.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDisplayOrder(); ok {
		_spec.AddField(capability.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(capability.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ProductCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   capability.ProductTable,
			Columns: []string{capability.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   capability.ProductTable,
			Columns: []string{capability.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FeaturesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   capability.FeaturesTable,
			Columns: []string{capability.FeaturesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(feature.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFeaturesIDs(); len(nodes) > 0 && !_u.mutation.FeaturesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   capability.FeaturesTable,
			Columns: []string{capability.FeaturesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(feature.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FeaturesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   capability.FeaturesTable,
			Columns: []string{capability.FeaturesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(feature.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Capability{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{capability.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
