// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/plexusone/productgraph/ent/event"
	"github.com/plexusone/productgraph/ent/journey"
	"github.com/plexusone/productgraph/ent/predicate"
	"github.com/plexusone/productgraph/ent/project"
)

// EventUpdate is the builder for updating Event entities.
type EventUpdate struct {
	config
	hooks    []Hook
	mutation *EventMutation
}

// Where appends a list predicates to the EventUpdate builder.
func (_u *EventUpdate) Where(ps ...predicate.Event) *EventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOrgID sets the "org_id" field.
func (_u *EventUpdate) SetOrgID(v uuid.UUID) *EventUpdate {
	_u.mutation.SetOrgID(v)
	return _u
}

// SetNillableOrgID sets the "org_id" field if the given value is not nil.
func (_u *EventUpdate) SetNillableOrgID(v *uuid.UUID) *EventUpdate {
	if v != nil {
		_u.SetOrgID(*v)
	}
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *EventUpdate) SetProjectID(v uuid.UUID) *EventUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *EventUpdate) SetNillableProjectID(v *uuid.UUID) *EventUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetEventID sets the "event_id" field.
func (_u *EventUpdate) SetEventID(v string) *EventUpdate {
	_u.mutation.SetEventID(v)
	return _u
}

// SetNillableEventID sets the "event_id" field if the given value is not nil.
func (_u *EventUpdate) SetNillableEventID(v *string) *EventUpdate {
	if v != nil {
		_u.SetEventID(*v)
	}
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *EventUpdate) SetSessionID(v string) *EventUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *EventUpdate) SetNillableSessionID(v *string) *EventUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *EventUpdate) SetUserID(v string) *EventUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *EventUpdate) SetNillableUserID(v *string) *EventUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *EventUpdate) ClearUserID() *EventUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *EventUpdate) SetEventType(v event.EventType) *EventUpdate {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *EventUpdate) SetNillableEventType(v *event.EventType) *EventUpdate {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetEventName sets the "event_name" field.
func (_u *EventUpdate) SetEventName(v string) *EventUpdate {
	_u.mutation.SetEventName(v)
	return _u
}

// SetNillableEventName sets the "event_name" field if the given value is not nil.
func (_u *EventUpdate) SetNillableEventName(v *string) *EventUpdate {
	if v != nil {
		_u.SetEventName(*v)
	}
	return _u
}

// ClearEventName clears the value of the "event_name" field.
func (_u *EventUpdate) ClearEventName() *EventUpdate {
	_u.mutation.ClearEventName()
	return _u
}

// SetTimestamp sets the "timestamp" field.
func (_u *EventUpdate) SetTimestamp(v time.Time) *EventUpdate {
	_u.mutation.SetTimestamp(v)
	return _u
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_u *EventUpdate) SetNillableTimestamp(v *time.Time) *EventUpdate {
	if v != nil {
		_u.SetTimestamp(*v)
	}
	return _u
}

// SetSequence sets the "sequence" field.
func (_u *EventUpdate) SetSequence(v int64) *EventUpdate {
	_u.mutation.ResetSequence()
	_u.mutation.SetSequence(v)
	return _u
}

// SetNillableSequence sets the "sequence" field if the given value is not nil.
func (_u *EventUpdate) SetNillableSequence(v *int64) *EventUpdate {
	if v != nil {
		_u.SetSequence(*v)
	}
	return _u
}

// AddSequence adds value to the "sequence" field.
func (_u *EventUpdate) AddSequence(v int64) *EventUpdate {
	_u.mutation.AddSequence(v)
	return _u
}

// SetPagePath sets the "page_path" field.
func (_u *EventUpdate) SetPagePath(v string) *EventUpdate {
	_u.mutation.SetPagePath(v)
	return _u
}

// SetNillablePagePath sets the "page_path" field if the given value is not nil.
func (_u *EventUpdate) SetNillablePagePath(v *string) *EventUpdate {
	if v != nil {
		_u.SetPagePath(*v)
	}
	return _u
}

// ClearPagePath clears the value of the "page_path" field.
func (_u *EventUpdate) ClearPagePath() *EventUpdate {
	_u.mutation.ClearPagePath()
	return _u
}

// SetPageTitle sets the "page_title" field.
func (_u *EventUpdate) SetPageTitle(v string) *EventUpdate {
	_u.mutation.SetPageTitle(v)
	return _u
}

// SetNillablePageTitle sets the "page_title" field if the given value is not nil.
func (_u *EventUpdate) SetNillablePageTitle(v *string) *EventUpdate {
	if v != nil {
		_u.SetPageTitle(*v)
	}
	return _u
}

// ClearPageTitle clears the value of the "page_title" field.
func (_u *EventUpdate) ClearPageTitle() *EventUpdate {
	_u.mutation.ClearPageTitle()
	return _u
}

// SetPageURL sets the "page_url" field.
func (_u *EventUpdate) SetPageURL(v string) *EventUpdate {
	_u.mutation.SetPageURL(v)
	return _u
}

// SetNillablePageURL sets the "page_url" field if the given value is not nil.
func (_u *EventUpdate) SetNillablePageURL(v *string) *EventUpdate {
	if v != nil {
		_u.SetPageURL(*v)
	}
	return _u
}

// ClearPageURL clears the value of the "page_url" field.
func (_u *EventUpdate) ClearPageURL() *EventUpdate {
	_u.mutation.ClearPageURL()
	return _u
}

// SetPageReferrer sets the "page_referrer" field.
func (_u *EventUpdate) SetPageReferrer(v string) *EventUpdate {
	_u.mutation.SetPageReferrer(v)
	return _u
}

// SetNillablePageReferrer sets the "page_referrer" field if the given value is not nil.
func (_u *EventUpdate) SetNillablePageReferrer(v *string) *EventUpdate {
	if v != nil {
		_u.SetPageReferrer(*v)
	}
	return _u
}

// ClearPageReferrer clears the value of the "page_referrer" field.
func (_u *EventUpdate) ClearPageReferrer() *EventUpdate {
	_u.mutation.ClearPageReferrer()
	return _u
}

// SetUIComponentName sets the "ui_component_name" field.
func (_u *EventUpdate) SetUIComponentName(v string) *EventUpdate {
	_u.mutation.SetUIComponentName(v)
	return _u
}

// SetNillableUIComponentName sets the "ui_component_name" field if the given value is not nil.
func (_u *EventUpdate) SetNillableUIComponentName(v *string) *EventUpdate {
	if v != nil {
		_u.SetUIComponentName(*v)
	}
	return _u
}

// ClearUIComponentName clears the value of the "ui_component_name" field.
func (_u *EventUpdate) ClearUIComponentName() *EventUpdate {
	_u.mutation.ClearUIComponentName()
	return _u
}

// SetUIComponentPath sets the "ui_component_path" field.
func (_u *EventUpdate) SetUIComponentPath(v string) *EventUpdate {
	_u.mutation.SetUIComponentPath(v)
	return _u
}

// SetNillableUIComponentPath sets the "ui_component_path" field if the given value is not nil.
func (_u *EventUpdate) SetNillableUIComponentPath(v *string) *EventUpdate {
	if v != nil {
		_u.SetUIComponentPath(*v)
	}
	return _u
}

// ClearUIComponentPath clears the value of the "ui_component_path" field.
func (_u *EventUpdate) ClearUIComponentPath() *EventUpdate {
	_u.mutation.ClearUIComponentPath()
	return _u
}

// SetUIComponentType sets the "ui_component_type" field.
func (_u *EventUpdate) SetUIComponentType(v string) *EventUpdate {
	_u.mutation.SetUIComponentType(v)
	return _u
}

// SetNillableUIComponentType sets the "ui_component_type" field if the given value is not nil.
func (_u *EventUpdate) SetNillableUIComponentType(v *string) *EventUpdate {
	if v != nil {
		_u.SetUIComponentType(*v)
	}
	return _u
}

// ClearUIComponentType clears the value of the "ui_component_type" field.
func (_u *EventUpdate) ClearUIComponentType() *EventUpdate {
	_u.mutation.ClearUIComponentType()
	return _u
}

// SetUIAction sets the "ui_action" field.
func (_u *EventUpdate) SetUIAction(v string) *EventUpdate {
	_u.mutation.SetUIAction(v)
	return _u
}

// SetNillableUIAction sets the "ui_action" field if the given value is not nil.
func (_u *EventUpdate) SetNillableUIAction(v *string) *EventUpdate {
	if v != nil {
		_u.SetUIAction(*v)
	}
	return _u
}

// ClearUIAction clears the value of the "ui_action" field.
func (_u *EventUpdate) ClearUIAction() *EventUpdate {
	_u.mutation.ClearUIAction()
	return _u
}

// SetUIElement sets the "ui_element" field.
func (_u *EventUpdate) SetUIElement(v string) *EventUpdate {
	_u.mutation.SetUIElement(v)
	return _u
}

// SetNillableUIElement sets the "ui_element" field if the given value is not nil.
func (_u *EventUpdate) SetNillableUIElement(v *string) *EventUpdate {
	if v != nil {
		_u.SetUIElement(*v)
	}
	return _u
}

// ClearUIElement clears the value of the "ui_element" field.
func (_u *EventUpdate) ClearUIElement() *EventUpdate {
	_u.mutation.ClearUIElement()
	return _u
}

// SetUIElementText sets the "ui_element_text" field.
func (_u *EventUpdate) SetUIElementText(v string) *EventUpdate {
	_u.mutation.SetUIElementText(v)
	return _u
}

// SetNillableUIElementText sets the "ui_element_text" field if the given value is not nil.
func (_u *EventUpdate) SetNillableUIElementText(v *string) *EventUpdate {
	if v != nil {
		_u.SetUIElementText(*v)
	}
	return _u
}

// ClearUIElementText clears the value of the "ui_element_text" field.
func (_u *EventUpdate) ClearUIElementText() *EventUpdate {
	_u.mutation.ClearUIElementText()
	return _u
}

// SetUIViewport sets the "ui_viewport" field.
func (_u *EventUpdate) SetUIViewport(v string) *EventUpdate {
	_u.mutation.SetUIViewport(v)
	return _u
}

// SetNillableUIViewport sets the "ui_viewport" field if the given value is not nil.
func (_u *EventUpdate) SetNillableUIViewport(v *string) *EventUpdate {
	if v != nil {
		_u.SetUIViewport(*v)
	}
	return _u
}

// ClearUIViewport clears the value of the "ui_viewport" field.
func (_u *EventUpdate) ClearUIViewport() *EventUpdate {
	_u.mutation.ClearUIViewport()
	return _u
}

// SetUIScrollPosition sets the "ui_scroll_position" field.
func (_u *EventUpdate) SetUIScrollPosition(v float64) *EventUpdate {
	_u.mutation.ResetUIScrollPosition()
	_u.mutation.SetUIScrollPosition(v)
	return _u
}

// SetNillableUIScrollPosition sets the "ui_scroll_position" field if the given value is not nil.
func (_u *EventUpdate) SetNillableUIScrollPosition(v *float64) *EventUpdate {
	if v != nil {
		_u.SetUIScrollPosition(*v)
	}
	return _u
}

// AddUIScrollPosition adds value to the "ui_scroll_position" field.
func (_u *EventUpdate) AddUIScrollPosition(v float64) *EventUpdate {
	_u.mutation.AddUIScrollPosition(v)
	return _u
}

// ClearUIScrollPosition clears the value of the "ui_scroll_position" field.
func (_u *EventUpdate) ClearUIScrollPosition() *EventUpdate {
	_u.mutation.ClearUIScrollPosition()
	return _u
}

// SetUIStateKey sets the "ui_state_key" field.
func (_u *EventUpdate) SetUIStateKey(v string) *EventUpdate {
	_u.mutation.SetUIStateKey(v)
	return _u
}

// SetNillableUIStateKey sets the "ui_state_key" field if the given value is not nil.
func (_u *EventUpdate) SetNillableUIStateKey(v *string) *EventUpdate {
	if v != nil {
		_u.SetUIStateKey(*v)
	}
	return _u
}

// ClearUIStateKey clears the value of the "ui_state_key" field.
func (_u *EventUpdate) ClearUIStateKey() *EventUpdate {
	_u.mutation.ClearUIStateKey()
	return _u
}

// SetUIStateBefore sets the "ui_state_before" field.
func (_u *EventUpdate) SetUIStateBefore(v string) *EventUpdate {
	_u.mutation.SetUIStateBefore(v)
	return _u
}

// SetNillableUIStateBefore sets the "ui_state_before" field if the given value is not nil.
func (_u *EventUpdate) SetNillableUIStateBefore(v *string) *EventUpdate {
	if v != nil {
		_u.SetUIStateBefore(*v)
	}
	return _u
}

// ClearUIStateBefore clears the value of the "ui_state_before" field.
func (_u *EventUpdate) ClearUIStateBefore() *EventUpdate {
	_u.mutation.ClearUIStateBefore()
	return _u
}

// SetUIStateAfter sets the "ui_state_after" field.
func (_u *EventUpdate) SetUIStateAfter(v string) *EventUpdate {
	_u.mutation.SetUIStateAfter(v)
	return _u
}

// SetNillableUIStateAfter sets the "ui_state_after" field if the given value is not nil.
func (_u *EventUpdate) SetNillableUIStateAfter(v *string) *EventUpdate {
	if v != nil {
		_u.SetUIStateAfter(*v)
	}
	return _u
}

// ClearUIStateAfter clears the value of the "ui_state_after" field.
func (_u *EventUpdate) ClearUIStateAfter() *EventUpdate {
	_u.mutation.ClearUIStateAfter()
	return _u
}

// SetUIStateChangeType sets the "ui_state_change_type" field.
func (_u *EventUpdate) SetUIStateChangeType(v string) *EventUpdate {
	_u.mutation.SetUIStateChangeType(v)
	return _u
}

// SetNillableUIStateChangeType sets the "ui_state_change_type" field if the given value is not nil.
func (_u *EventUpdate) SetNillableUIStateChangeType(v *string) *EventUpdate {
	if v != nil {
		_u.SetUIStateChangeType(*v)
	}
	return _u
}

// ClearUIStateChangeType clears the value of the "ui_state_change_type" field.
func (_u *EventUpdate) ClearUIStateChangeType() *EventUpdate {
	_u.mutation.ClearUIStateChangeType()
	return _u
}

// SetJourneyID sets the "journey_id" field.
func (_u *EventUpdate) SetJourneyID(v uuid.UUID) *EventUpdate {
	_u.mutation.SetJourneyID(v)
	return _u
}

// SetNillableJourneyID sets the "journey_id" field if the given value is not nil.
func (_u *EventUpdate) SetNillableJourneyID(v *uuid.UUID) *EventUpdate {
	if v != nil {
		_u.SetJourneyID(*v)
	}
	return _u
}

// ClearJourneyID clears the value of the "journey_id" field.
func (_u *EventUpdate) ClearJourneyID() *EventUpdate {
	_u.mutation.ClearJourneyID()
	return _u
}

// SetJourneyStepID sets the "journey_step_id" field.
func (_u *EventUpdate) SetJourneyStepID(v string) *EventUpdate {
	_u.mutation.SetJourneyStepID(v)
	return _u
}

// SetNillableJourneyStepID sets the "journey_step_id" field if the given value is not nil.
func (_u *EventUpdate) SetNillableJourneyStepID(v *string) *EventUpdate {
	if v != nil {
		_u.SetJourneyStepID(*v)
	}
	return _u
}

// ClearJourneyStepID clears the value of the "journey_step_id" field.
func (_u *EventUpdate) ClearJourneyStepID() *EventUpdate {
	_u.mutation.ClearJourneyStepID()
	return _u
}

// SetJourneyStepName sets the "journey_step_name" field.
func (_u *EventUpdate) SetJourneyStepName(v string) *EventUpdate {
	_u.mutation.SetJourneyStepName(v)
	return _u
}

// SetNillableJourneyStepName sets the "journey_step_name" field if the given value is not nil.
func (_u *EventUpdate) SetNillableJourneyStepName(v *string) *EventUpdate {
	if v != nil {
		_u.SetJourneyStepName(*v)
	}
	return _u
}

// ClearJourneyStepName clears the value of the "journey_step_name" field.
func (_u *EventUpdate) ClearJourneyStepName() *EventUpdate {
	_u.mutation.ClearJourneyStepName()
	return _u
}

// SetConversionStatus sets the "conversion_status" field.
func (_u *EventUpdate) SetConversionStatus(v string) *EventUpdate {
	_u.mutation.SetConversionStatus(v)
	return _u
}

// SetNillableConversionStatus sets the "conversion_status" field if the given value is not nil.
func (_u *EventUpdate) SetNillableConversionStatus(v *string) *EventUpdate {
	if v != nil {
		_u.SetConversionStatus(*v)
	}
	return _u
}

// ClearConversionStatus clears the value of the "conversion_status" field.
func (_u *EventUpdate) ClearConversionStatus() *EventUpdate {
	_u.mutation.ClearConversionStatus()
	return _u
}

// SetAPIMethod sets the "api_method" field.
func (_u *EventUpdate) SetAPIMethod(v string) *EventUpdate {
	_u.mutation.SetAPIMethod(v)
	return _u
}

// SetNillableAPIMethod sets the "api_method" field if the given value is not nil.
func (_u *EventUpdate) SetNillableAPIMethod(v *string) *EventUpdate {
	if v != nil {
		_u.SetAPIMethod(*v)
	}
	return _u
}

// ClearAPIMethod clears the value of the "api_method" field.
func (_u *EventUpdate) ClearAPIMethod() *EventUpdate {
	_u.mutation.ClearAPIMethod()
	return _u
}

// SetAPIPath sets the "api_path" field.
func (_u *EventUpdate) SetAPIPath(v string) *EventUpdate {
	_u.mutation.SetAPIPath(v)
	return _u
}

// SetNillableAPIPath sets the "api_path" field if the given value is not nil.
func (_u *EventUpdate) SetNillableAPIPath(v *string) *EventUpdate {
	if v != nil {
		_u.SetAPIPath(*v)
	}
	return _u
}

// ClearAPIPath clears the value of the "api_path" field.
func (_u *EventUpdate) ClearAPIPath() *EventUpdate {
	_u.mutation.ClearAPIPath()
	return _u
}

// SetAPIStatusCode sets the "api_status_code" field.
func (_u *EventUpdate) SetAPIStatusCode(v int) *EventUpdate {
	_u.mutation.ResetAPIStatusCode()
	_u.mutation.SetAPIStatusCode(v)
	return _u
}

// SetNillableAPIStatusCode sets the "api_status_code" field if the given value is not nil.
func (_u *EventUpdate) SetNillableAPIStatusCode(v *int) *EventUpdate {
	if v != nil {
		_u.SetAPIStatusCode(*v)
	}
	return _u
}

// AddAPIStatusCode adds value to the "api_status_code" field.
func (_u *EventUpdate) AddAPIStatusCode(v int) *EventUpdate {
	_u.mutation.AddAPIStatusCode(v)
	return _u
}

// ClearAPIStatusCode clears the value of the "api_status_code" field.
func (_u *EventUpdate) ClearAPIStatusCode() *EventUpdate {
	_u.mutation.ClearAPIStatusCode()
	return _u
}

// SetAPIDurationMs sets the "api_duration_ms" field.
func (_u *EventUpdate) SetAPIDurationMs(v int64) *EventUpdate {
	_u.mutation.ResetAPIDurationMs()
	_u.mutation.SetAPIDurationMs(v)
	return _u
}

// SetNillableAPIDurationMs sets the "api_duration_ms" field if the given value is not nil.
func (_u *EventUpdate) SetNillableAPIDurationMs(v *int64) *EventUpdate {
	if v != nil {
		_u.SetAPIDurationMs(*v)
	}
	return _u
}

// AddAPIDurationMs adds value to the "api_duration_ms" field.
func (_u *EventUpdate) AddAPIDurationMs(v int64) *EventUpdate {
	_u.mutation.AddAPIDurationMs(v)
	return _u
}

// ClearAPIDurationMs clears the value of the "api_duration_ms" field.
func (_u *EventUpdate) ClearAPIDurationMs() *EventUpdate {
	_u.mutation.ClearAPIDurationMs()
	return _u
}

// SetErrorType sets the "error_type" field.
func (_u *EventUpdate) SetErrorType(v string) *EventUpdate {
	_u.mutation.SetErrorType(v)
	return _u
}

// SetNillableErrorType sets the "error_type" field if the given value is not nil.
func (_u *EventUpdate) SetNillableErrorType(v *string) *EventUpdate {
	if v != nil {
		_u.SetErrorType(*v)
	}
	return _u
}

// ClearErrorType clears the value of the "error_type" field.
func (_u *EventUpdate) ClearErrorType() *EventUpdate {
	_u.mutation.ClearErrorType()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *EventUpdate) SetErrorMessage(v string) *EventUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *EventUpdate) SetNillableErrorMessage(v *string) *EventUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *EventUpdate) ClearErrorMessage() *EventUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetErrorStack sets the "error_stack" field.
func (_u *EventUpdate) SetErrorStack(v string) *EventUpdate {
	_u.mutation.SetErrorStack(v)
	return _u
}

// SetNillableErrorStack sets the "error_stack" field if the given value is not nil.
func (_u *EventUpdate) SetNillableErrorStack(v *string) *EventUpdate {
	if v != nil {
		_u.SetErrorStack(*v)
	}
	return _u
}

// ClearErrorStack clears the value of the "error_stack" field.
func (_u *EventUpdate) ClearErrorStack() *EventUpdate {
	_u.mutation.ClearErrorStack()
	return _u
}

// SetErrorComponent sets the "error_component" field.
func (_u *EventUpdate) SetErrorComponent(v string) *EventUpdate {
	_u.mutation.SetErrorComponent(v)
	return _u
}

// SetNillableErrorComponent sets the "error_component" field if the given value is not nil.
func (_u *EventUpdate) SetNillableErrorComponent(v *string) *EventUpdate {
	if v != nil {
		_u.SetErrorComponent(*v)
	}
	return _u
}

// ClearErrorComponent clears the value of the "error_component" field.
func (_u *EventUpdate) ClearErrorComponent() *EventUpdate {
	_u.mutation.ClearErrorComponent()
	return _u
}

// SetPerformanceLcpMs sets the "performance_lcp_ms" field.
func (_u *EventUpdate) SetPerformanceLcpMs(v float64) *EventUpdate {
	_u.mutation.ResetPerformanceLcpMs()
	_u.mutation.SetPerformanceLcpMs(v)
	return _u
}

// SetNillablePerformanceLcpMs sets the "performance_lcp_ms" field if the given value is not nil.
func (_u *EventUpdate) SetNillablePerformanceLcpMs(v *float64) *EventUpdate {
	if v != nil {
		_u.SetPerformanceLcpMs(*v)
	}
	return _u
}

// AddPerformanceLcpMs adds value to the "performance_lcp_ms" field.
func (_u *EventUpdate) AddPerformanceLcpMs(v float64) *EventUpdate {
	_u.mutation.AddPerformanceLcpMs(v)
	return _u
}

// ClearPerformanceLcpMs clears the value of the "performance_lcp_ms" field.
func (_u *EventUpdate) ClearPerformanceLcpMs() *EventUpdate {
	_u.mutation.ClearPerformanceLcpMs()
	return _u
}

// SetPerformanceFidMs sets the "performance_fid_ms" field.
func (_u *EventUpdate) SetPerformanceFidMs(v float64) *EventUpdate {
	_u.mutation.ResetPerformanceFidMs()
	_u.mutation.SetPerformanceFidMs(v)
	return _u
}

// SetNillablePerformanceFidMs sets the "performance_fid_ms" field if the given value is not nil.
func (_u *EventUpdate) SetNillablePerformanceFidMs(v *float64) *EventUpdate {
	if v != nil {
		_u.SetPerformanceFidMs(*v)
	}
	return _u
}

// AddPerformanceFidMs adds value to the "performance_fid_ms" field.
func (_u *EventUpdate) AddPerformanceFidMs(v float64) *EventUpdate {
	_u.mutation.AddPerformanceFidMs(v)
	return _u
}

// ClearPerformanceFidMs clears the value of the "performance_fid_ms" field.
func (_u *EventUpdate) ClearPerformanceFidMs() *EventUpdate {
	_u.mutation.ClearPerformanceFidMs()
	return _u
}

// SetPerformanceCls sets the "performance_cls" field.
func (_u *EventUpdate) SetPerformanceCls(v float64) *EventUpdate {
	_u.mutation.ResetPerformanceCls()
	_u.mutation.SetPerformanceCls(v)
	return _u
}

// SetNillablePerformanceCls sets the "performance_cls" field if the given value is not nil.
func (_u *EventUpdate) SetNillablePerformanceCls(v *float64) *EventUpdate {
	if v != nil {
		_u.SetPerformanceCls(*v)
	}
	return _u
}

// AddPerformanceCls adds value to the "performance_cls" field.
func (_u *EventUpdate) AddPerformanceCls(v float64) *EventUpdate {
	_u.mutation.AddPerformanceCls(v)
	return _u
}

// ClearPerformanceCls clears the value of the "performance_cls" field.
func (_u *EventUpdate) ClearPerformanceCls() *EventUpdate {
	_u.mutation.ClearPerformanceCls()
	return _u
}

// SetPerformanceTtfbMs sets the "performance_ttfb_ms" field.
func (_u *EventUpdate) SetPerformanceTtfbMs(v float64) *EventUpdate {
	_u.mutation.ResetPerformanceTtfbMs()
	_u.mutation.SetPerformanceTtfbMs(v)
	return _u
}

// SetNillablePerformanceTtfbMs sets the "performance_ttfb_ms" field if the given value is not nil.
func (_u *EventUpdate) SetNillablePerformanceTtfbMs(v *float64) *EventUpdate {
	if v != nil {
		_u.SetPerformanceTtfbMs(*v)
	}
	return _u
}

// AddPerformanceTtfbMs adds value to the "performance_ttfb_ms" field.
func (_u *EventUpdate) AddPerformanceTtfbMs(v float64) *EventUpdate {
	_u.mutation.AddPerformanceTtfbMs(v)
	return _u
}

// ClearPerformanceTtfbMs clears the value of the "performance_ttfb_ms" field.
func (_u *EventUpdate) ClearPerformanceTtfbMs() *EventUpdate {
	_u.mutation.ClearPerformanceTtfbMs()
	return _u
}

// SetSnapshotURL sets the "snapshot_url" field.
func (_u *EventUpdate) SetSnapshotURL(v string) *EventUpdate {
	_u.mutation.SetSnapshotURL(v)
	return _u
}

// SetNillableSnapshotURL sets the "snapshot_url" field if the given value is not nil.
func (_u *EventUpdate) SetNillableSnapshotURL(v *string) *EventUpdate {
	if v != nil {
		_u.SetSnapshotURL(*v)
	}
	return _u
}

// ClearSnapshotURL clears the value of the "snapshot_url" field.
func (_u *EventUpdate) ClearSnapshotURL() *EventUpdate {
	_u.mutation.ClearSnapshotURL()
	return _u
}

// SetSnapshotViewport sets the "snapshot_viewport" field.
func (_u *EventUpdate) SetSnapshotViewport(v string) *EventUpdate {
	_u.mutation.SetSnapshotViewport(v)
	return _u
}

// SetNillableSnapshotViewport sets the "snapshot_viewport" field if the given value is not nil.
func (_u *EventUpdate) SetNillableSnapshotViewport(v *string) *EventUpdate {
	if v != nil {
		_u.SetSnapshotViewport(*v)
	}
	return _u
}

// ClearSnapshotViewport clears the value of the "snapshot_viewport" field.
func (_u *EventUpdate) ClearSnapshotViewport() *EventUpdate {
	_u.mutation.ClearSnapshotViewport()
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *EventUpdate) SetDurationMs(v int64) *EventUpdate {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *EventUpdate) SetNillableDurationMs(v *int64) *EventUpdate {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *EventUpdate) AddDurationMs(v int64) *EventUpdate {
	_u.mutation.AddDurationMs(v)
	return _u
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (_u *EventUpdate) ClearDurationMs() *EventUpdate {
	_u.mutation.ClearDurationMs()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *EventUpdate) SetMetadata(v map[string]interface{}) *EventUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *EventUpdate) ClearMetadata() *EventUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *EventUpdate) SetProject(v *Project) *EventUpdate {
	return _u.SetProjectID(v.ID)
}

// SetJourney sets the "journey" edge to the Journey entity.
func (_u *EventUpdate) SetJourney(v *Journey) *EventUpdate {
	return _u.SetJourneyID(v.ID)
}

// Mutation returns the EventMutation object of the builder.
func (_u *EventUpdate) Mutation() *EventMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *EventUpdate) ClearProject() *EventUpdate {
	_u.mutation.ClearProject()
	return _u
}

// ClearJourney clears the "journey" edge to the Journey entity.
func (_u *EventUpdate) ClearJourney() *EventUpdate {
	_u.mutation.ClearJourney()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EventUpdate) check() error {
	if v, ok := _u.mutation.EventID(); ok {
		if err := event.EventIDValidator(v); err != nil {
			return &ValidationError{Name: "event_id", err: fmt.Errorf(`ent: validator failed for field "Event.event_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SessionID(); ok {
		if err := event.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "Event.session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserID(); ok {
		if err := event.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Event.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EventType(); ok {
		if err := event.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "Event.event_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EventName(); ok {
		if err := event.EventNameValidator(v); err != nil {
			return &ValidationError{Name: "event_name", err: fmt.Errorf(`ent: validator failed for field "Event.event_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PagePath(); ok {
		if err := event.PagePathValidator(v); err != nil {
			return &ValidationError{Name: "page_path", err: fmt.Errorf(`ent: validator failed for field "Event.page_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PageTitle(); ok {
		if err := event.PageTitleValidator(v); err != nil {
			return &ValidationError{Name: "page_title", err: fmt.Errorf(`ent: validator failed for field "Event.page_title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PageURL(); ok {
		if err := event.PageURLValidator(v); err != nil {
			return &ValidationError{Name: "page_url", err: fmt.Errorf(`ent: validator failed for field "Event.page_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PageReferrer(); ok {
		if err := event.PageReferrerValidator(v); err != nil {
			return &ValidationError{Name: "page_referrer", err: fmt.Errorf(`ent: validator failed for field "Event.page_referrer": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UIComponentName(); ok {
		if err := event.UIComponentNameValidator(v); err != nil {
			return &ValidationError{Name: "ui_component_name", err: fmt.Errorf(`ent: validator failed for field "Event.ui_component_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UIComponentPath(); ok {
		if err := event.UIComponentPathValidator(v); err != nil {
			return &ValidationError{Name: "ui_component_path", err: fmt.Errorf(`ent: validator failed for field "Event.ui_component_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UIComponentType(); ok {
		if err := event.UIComponentTypeValidator(v); err != nil {
			return &ValidationError{Name: "ui_component_type", err: fmt.Errorf(`ent: validator failed for field "Event.ui_component_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UIAction(); ok {
		if err := event.UIActionValidator(v); err != nil {
			return &ValidationError{Name: "ui_action", err: fmt.Errorf(`ent: validator failed for field "Event.ui_action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UIElement(); ok {
		if err := event.UIElementValidator(v); err != nil {
			return &ValidationError{Name: "ui_element", err: fmt.Errorf(`ent: validator failed for field "Event.ui_element": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UIElementText(); ok {
		if err := event.UIElementTextValidator(v); err != nil {
			return &ValidationError{Name: "ui_element_text", err: fmt.Errorf(`ent: validator failed for field "Event.ui_element_text": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UIViewport(); ok {
		if err := event.UIViewportValidator(v); err != nil {
			return &ValidationError{Name: "ui_viewport", err: fmt.Errorf(`ent: validator failed for field "Event.ui_viewport": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UIStateKey(); ok {
		if err := event.UIStateKeyValidator(v); err != nil {
			return &ValidationError{Name: "ui_state_key", err: fmt.Errorf(`ent: validator failed for field "Event.ui_state_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UIStateChangeType(); ok {
		if err := event.UIStateChangeTypeValidator(v); err != nil {
			return &ValidationError{Name: "ui_state_change_type", err: fmt.Errorf(`ent: validator failed for field "Event.ui_state_change_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.JourneyStepID(); ok {
		if err := event.JourneyStepIDValidator(v); err != nil {
			return &ValidationError{Name: "journey_step_id", err: fmt.Errorf(`ent: validator failed for field "Event.journey_step_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.JourneyStepName(); ok {
		if err := event.JourneyStepNameValidator(v); err != nil {
			return &ValidationError{Name: "journey_step_name", err: fmt.Errorf(`ent: validator failed for field "Event.journey_step_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConversionStatus(); ok {
		if err := event.ConversionStatusValidator(v); err != nil {
			return &ValidationError{Name: "conversion_status", err: fmt.Errorf(`ent: validator failed for field "Event.conversion_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIMethod(); ok {
		if err := event.APIMethodValidator(v); err != nil {
			return &ValidationError{Name: "api_method", err: fmt.Errorf(`ent: validator failed for field "Event.api_method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIPath(); ok {
		if err := event.APIPathValidator(v); err != nil {
			return &ValidationError{Name: "api_path", err: fmt.Errorf(`ent: validator failed for field "Event.api_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorType(); ok {
		if err := event.ErrorTypeValidator(v); err != nil {
			return &ValidationError{Name: "error_type", err: fmt.Errorf(`ent: validator failed for field "Event.error_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorComponent(); ok {
		if err := event.ErrorComponentValidator(v); err != nil {
			return &ValidationError{Name: "error_component", err: fmt.Errorf(`ent: validator failed for field "Event.error_component": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SnapshotURL(); ok {
		if err := event.SnapshotURLValidator(v); err != nil {
			return &ValidationError{Name: "snapshot_url", err: fmt.Errorf(`ent: validator failed for field "Event.snapshot_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SnapshotViewport(); ok {
		if err := event.SnapshotViewportValidator(v); err != nil {
			return &ValidationError{Name: "snapshot_viewport", err: fmt.Errorf(`ent: validator failed for field "Event.snapshot_viewport": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Event.project"`)
	}
	return nil
}

func (_u *EventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(event.Table, event.Columns, sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrgID(); ok {
		_spec.SetField(event.FieldOrgID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.EventID(); ok {
		_spec.SetField(event.FieldEventID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(event.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(event.FieldUserID, field.TypeString, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(event.FieldUserID, field.TypeString)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(event.FieldEventType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.EventName(); ok {
		_spec.SetField(event.FieldEventName, field.TypeString, value)
	}
	if _u.mutation.EventNameCleared() {
		_spec.ClearField(event.FieldEventName, field.TypeString)
	}
	if value, ok := _u.mutation.Timestamp(); ok {
		_spec.SetField(event.FieldTimestamp, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Sequence(); ok {
		_spec.SetField(event.FieldSequence, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSequence(); ok {
		_spec.AddField(event.FieldSequence, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PagePath(); ok {
		_spec.SetField(event.FieldPagePath, field.TypeString, value)
	}
	if _u.mutation.PagePathCleared() {
		_spec.ClearField(event.FieldPagePath, field.TypeString)
	}
	if value, ok := _u.mutation.PageTitle(); ok {
		_spec.SetField(event.FieldPageTitle, field.TypeString, value)
	}
	if _u.mutation.PageTitleCleared() {
		_spec.ClearField(event.FieldPageTitle, field.TypeString)
	}
	if value, ok := _u.mutation.PageURL(); ok {
		_spec.SetField(event.FieldPageURL, field.TypeString, value)
	}
	if _u.mutation.PageURLCleared() {
		_spec.ClearField(event.FieldPageURL, field.TypeString)
	}
	if value, ok := _u.mutation.PageReferrer(); ok {
		_spec.SetField(event.FieldPageReferrer, field.TypeString, value)
	}
	if _u.mutation.PageReferrerCleared() {
		_spec.ClearField(event.FieldPageReferrer, field.TypeString)
	}
	if value, ok := _u.mutation.UIComponentName(); ok {
		_spec.SetField(event.FieldUIComponentName, field.TypeString, value)
	}
	if _u.mutation.UIComponentNameCleared() {
		_spec.ClearField(event.FieldUIComponentName, field.TypeString)
	}
	if value, ok := _u.mutation.UIComponentPath(); ok {
		_spec.SetField(event.FieldUIComponentPath, field.TypeString, value)
	}
	if _u.mutation.UIComponentPathCleared() {
		_spec.ClearField(event.FieldUIComponentPath, field.TypeString)
	}
	if value, ok := _u.mutation.UIComponentType(); ok {
		_spec.SetField(event.FieldUIComponentType, field.TypeString, value)
	}
	if _u.mutation.UIComponentTypeCleared() {
		_spec.ClearField(event.FieldUIComponentType, field.TypeString)
	}
	if value, ok := _u.mutation.UIAction(); ok {
		_spec.SetField(event.FieldUIAction, field.TypeString, value)
	}
	if _u.mutation.UIActionCleared() {
		_spec.ClearField(event.FieldUIAction, field.TypeString)
	}
	if value, ok := _u.mutation.UIElement(); ok {
		_spec.SetField(event.FieldUIElement, field.TypeString, value)
	}
	if _u.mutation.UIElementCleared() {
		_spec.ClearField(event.FieldUIElement, field.TypeString)
	}
	if value, ok := _u.mutation.UIElementText(); ok {
		_spec.SetField(event.FieldUIElementText, field.TypeString, value)
	}
	if _u.mutation.UIElementTextCleared() {
		_spec.ClearField(event.FieldUIElementText, field.TypeString)
	}
	if value, ok := _u.mutation.UIViewport(); ok {
		_spec.SetField(event.FieldUIViewport, field.TypeString, value)
	}
	if _u.mutation.UIViewportCleared() {
		_spec.ClearField(event.FieldUIViewport, field.TypeString)
	}
	if value, ok := _u.mutation.UIScrollPosition(); ok {
		_spec.SetField(event.FieldUIScrollPosition, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUIScrollPosition(); ok {
		_spec.AddField(event.FieldUIScrollPosition, field.TypeFloat64, value)
	}
	if _u.mutation.UIScrollPositionCleared() {
		_spec.ClearField(event.FieldUIScrollPosition, field.TypeFloat64)
	}
	if value, ok := _u.mutation.UIStateKey(); ok {
		_spec.SetField(event.FieldUIStateKey, field.TypeString, value)
	}
	if _u.mutation.UIStateKeyCleared() {
		_spec.ClearField(event.FieldUIStateKey, field.TypeString)
	}
	if value, ok := _u.mutation.UIStateBefore(); ok {
		_spec.SetField(event.FieldUIStateBefore, field.TypeString, value)
	}
	if _u.mutation.UIStateBeforeCleared() {
		_spec.ClearField(event.FieldUIStateBefore, field.TypeString)
	}
	if value, ok := _u.mutation.UIStateAfter(); ok {
		_spec.SetField(event.FieldUIStateAfter, field.TypeString, value)
	}
	if _u.mutation.UIStateAfterCleared() {
		_spec.ClearField(event.FieldUIStateAfter, field.TypeString)
	}
	if value, ok := _u.mutation.UIStateChangeType(); ok {
		_spec.SetField(event.FieldUIStateChangeType, field.TypeString, value)
	}
	if _u.mutation.UIStateChangeTypeCleared() {
		_spec.ClearField(event.FieldUIStateChangeType, field.TypeString)
	}
	if value, ok := _u.mutation.JourneyStepID(); ok {
		_spec.SetField(event.FieldJourneyStepID, field.TypeString, value)
	}
	if _u.mutation.JourneyStepIDCleared() {
		_spec.ClearField(event.FieldJourneyStepID, field.TypeString)
	}
	if value, ok := _u.mutation.JourneyStepName(); ok {
		_spec.SetField(event.FieldJourneyStepName, field.TypeString, value)
	}
	if _u.mutation.JourneyStepNameCleared() {
		_spec.ClearField(event.FieldJourneyStepName, field.TypeString)
	}
	if value, ok := _u.mutation.ConversionStatus(); ok {
		_spec.SetField(event.FieldConversionStatus, field.TypeString, value)
	}
	if _u.mutation.ConversionStatusCleared() {
		_spec.ClearField(event.FieldConversionStatus, field.TypeString)
	}
	if value, ok := _u.mutation.APIMethod(); ok {
		_spec.SetField(event.FieldAPIMethod, field.TypeString, value)
	}
	if _u.mutation.APIMethodCleared() {
		_spec.ClearField(event.FieldAPIMethod, field.TypeString)
	}
	if value, ok := _u.mutation.APIPath(); ok {
		_spec.SetField(event.FieldAPIPath, field.TypeString, value)
	}
	if _u.mutation.APIPathCleared() {
		_spec.ClearField(event.FieldAPIPath, field.TypeString)
	}
	if value, ok := _u.mutation.APIStatusCode(); ok {
		_spec.SetField(event.FieldAPIStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAPIStatusCode(); ok {
		_spec.AddField(event.FieldAPIStatusCode, field.TypeInt, value)
	}
	if _u.mutation.APIStatusCodeCleared() {
		_spec.ClearField(event.FieldAPIStatusCode, field.TypeInt)
	}
	if value, ok := _u.mutation.APIDurationMs(); ok {
		_spec.SetField(event.FieldAPIDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIDurationMs(); ok {
		_spec.AddField(event.FieldAPIDurationMs, field.TypeInt64, value)
	}
	if _u.mutation.APIDurationMsCleared() {
		_spec.ClearField(event.FieldAPIDurationMs, field.TypeInt64)
	}
	if value, ok := _u.mutation.ErrorType(); ok {
		_spec.SetField(event.FieldErrorType, field.TypeString, value)
	}
	if _u.mutation.ErrorTypeCleared() {
		_spec.ClearField(event.FieldErrorType, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(event.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(event.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorStack(); ok {
		_spec.SetField(event.FieldErrorStack, field.TypeString, value)
	}
	if _u.mutation.ErrorStackCleared() {
		_spec.ClearField(event.FieldErrorStack, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorComponent(); ok {
		_spec.SetField(event.FieldErrorComponent, field.TypeString, value)
	}
	if _u.mutation.ErrorComponentCleared() {
		_spec.ClearField(event.FieldErrorComponent, field.TypeString)
	}
	if value, ok := _u.mutation.PerformanceLcpMs(); ok {
		_spec.SetField(event.FieldPerformanceLcpMs, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPerformanceLcpMs(); ok {
		_spec.AddField(event.FieldPerformanceLcpMs, field.TypeFloat64, value)
	}
	if _u.mutation.PerformanceLcpMsCleared() {
		_spec.ClearField(event.FieldPerformanceLcpMs, field.TypeFloat64)
	}
	if value, ok := _u.mutation.PerformanceFidMs(); ok {
		_spec.SetField(event.FieldPerformanceFidMs, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPerformanceFidMs(); ok {
		_spec.AddField(event.FieldPerformanceFidMs, field.TypeFloat64, value)
	}
	if _u.mutation.PerformanceFidMsCleared() {
		_spec.ClearField(event.FieldPerformanceFidMs, field.TypeFloat64)
	}
	if value, ok := _u.mutation.PerformanceCls(); ok {
		_spec.SetField(event.FieldPerformanceCls, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPerformanceCls(); ok {
		_spec.AddField(event.FieldPerformanceCls, field.TypeFloat64, value)
	}
	if _u.mutation.PerformanceClsCleared() {
		_spec.ClearField(event.FieldPerformanceCls, field.TypeFloat64)
	}
	if value, ok := _u.mutation.PerformanceTtfbMs(); ok {
		_spec.SetField(event.FieldPerformanceTtfbMs, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPerformanceTtfbMs(); ok {
		_spec.AddField(event.FieldPerformanceTtfbMs, field.TypeFloat64, value)
	}
	if _u.mutation.PerformanceTtfbMsCleared() {
		_spec.ClearField(event.FieldPerformanceTtfbMs, field.TypeFloat64)
	}
	if value, ok := _u.mutation.SnapshotURL(); ok {
		_spec.SetField(event.FieldSnapshotURL, field.TypeString, value)
	}
	if _u.mutation.SnapshotURLCleared() {
		_spec.ClearField(event.FieldSnapshotURL, field.TypeString)
	}
	if value, ok := _u.mutation.SnapshotViewport(); ok {
		_spec.SetField(event.FieldSnapshotViewport, field.TypeString, value)
	}
	if _u.mutation.SnapshotViewportCleared() {
		_spec.ClearField(event.FieldSnapshotViewport, field.TypeString)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(event.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(event.FieldDurationMs, field.TypeInt64, value)
	}
	if _u.mutation.DurationMsCleared() {
		_spec.ClearField(event.FieldDurationMs, field.TypeInt64)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(event.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(event.FieldMetadata, field.TypeJSON)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.ProjectTable,
			Columns: []string{event.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.ProjectTable,
			Columns: []string{event.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.JourneyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.JourneyTable,
			Columns: []string{event.JourneyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(journey.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.JourneyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.JourneyTable,
			Columns: []string{event.JourneyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(journey.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{event.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EventUpdateOne is the builder for updating a single Event entity.
type EventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EventMutation
}

// SetOrgID sets the "org_id" field.
func (_u *EventUpdateOne) SetOrgID(v uuid.UUID) *EventUpdateOne {
	_u.mutation.SetOrgID(v)
	return _u
}

// SetNillableOrgID sets the "org_id" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableOrgID(v *uuid.UUID) *EventUpdateOne {
	if v != nil {
		_u.SetOrgID(*v)
	}
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *EventUpdateOne) SetProjectID(v uuid.UUID) *EventUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableProjectID(v *uuid.UUID) *EventUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetEventID sets the "event_id" field.
func (_u *EventUpdateOne) SetEventID(v string) *EventUpdateOne {
	_u.mutation.SetEventID(v)
	return _u
}

// SetNillableEventID sets the "event_id" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableEventID(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetEventID(*v)
	}
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *EventUpdateOne) SetSessionID(v string) *EventUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableSessionID(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *EventUpdateOne) SetUserID(v string) *EventUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableUserID(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *EventUpdateOne) ClearUserID() *EventUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *EventUpdateOne) SetEventType(v event.EventType) *EventUpdateOne {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableEventType(v *event.EventType) *EventUpdateOne {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetEventName sets the "event_name" field.
func (_u *EventUpdateOne) SetEventName(v string) *EventUpdateOne {
	_u.mutation.SetEventName(v)
	return _u
}

// SetNillableEventName sets the "event_name" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableEventName(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetEventName(*v)
	}
	return _u
}

// ClearEventName clears the value of the "event_name" field.
func (_u *EventUpdateOne) ClearEventName() *EventUpdateOne {
	_u.mutation.ClearEventName()
	return _u
}

// SetTimestamp sets the "timestamp" field.
func (_u *EventUpdateOne) SetTimestamp(v time.Time) *EventUpdateOne {
	_u.mutation.SetTimestamp(v)
	return _u
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableTimestamp(v *time.Time) *EventUpdateOne {
	if v != nil {
		_u.SetTimestamp(*v)
	}
	return _u
}

// SetSequence sets the "sequence" field.
func (_u *EventUpdateOne) SetSequence(v int64) *EventUpdateOne {
	_u.mutation.ResetSequence()
	_u.mutation.SetSequence(v)
	return _u
}

// SetNillableSequence sets the "sequence" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableSequence(v *int64) *EventUpdateOne {
	if v != nil {
		_u.SetSequence(*v)
	}
	return _u
}

// AddSequence adds value to the "sequence" field.
func (_u *EventUpdateOne) AddSequence(v int64) *EventUpdateOne {
	_u.mutation.AddSequence(v)
	return _u
}

// SetPagePath sets the "page_path" field.
func (_u *EventUpdateOne) SetPagePath(v string) *EventUpdateOne {
	_u.mutation.SetPagePath(v)
	return _u
}

// SetNillablePagePath sets the "page_path" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillablePagePath(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetPagePath(*v)
	}
	return _u
}

// ClearPagePath clears the value of the "page_path" field.
func (_u *EventUpdateOne) ClearPagePath() *EventUpdateOne {
	_u.mutation.ClearPagePath()
	return _u
}

// SetPageTitle sets the "page_title" field.
func (_u *EventUpdateOne) SetPageTitle(v string) *EventUpdateOne {
	_u.mutation.SetPageTitle(v)
	return _u
}

// SetNillablePageTitle sets the "page_title" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillablePageTitle(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetPageTitle(*v)
	}
	return _u
}

// ClearPageTitle clears the value of the "page_title" field.
func (_u *EventUpdateOne) ClearPageTitle() *EventUpdateOne {
	_u.mutation.ClearPageTitle()
	return _u
}

// SetPageURL sets the "page_url" field.
func (_u *EventUpdateOne) SetPageURL(v string) *EventUpdateOne {
	_u.mutation.SetPageURL(v)
	return _u
}

// SetNillablePageURL sets the "page_url" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillablePageURL(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetPageURL(*v)
	}
	return _u
}

// ClearPageURL clears the value of the "page_url" field.
func (_u *EventUpdateOne) ClearPageURL() *EventUpdateOne {
	_u.mutation.ClearPageURL()
	return _u
}

// SetPageReferrer sets the "page_referrer" field.
func (_u *EventUpdateOne) SetPageReferrer(v string) *EventUpdateOne {
	_u.mutation.SetPageReferrer(v)
	return _u
}

// SetNillablePageReferrer sets the "page_referrer" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillablePageReferrer(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetPageReferrer(*v)
	}
	return _u
}

// ClearPageReferrer clears the value of the "page_referrer" field.
func (_u *EventUpdateOne) ClearPageReferrer() *EventUpdateOne {
	_u.mutation.ClearPageReferrer()
	return _u
}

// SetUIComponentName sets the "ui_component_name" field.
func (_u *EventUpdateOne) SetUIComponentName(v string) *EventUpdateOne {
	_u.mutation.SetUIComponentName(v)
	return _u
}

// SetNillableUIComponentName sets the "ui_component_name" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableUIComponentName(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetUIComponentName(*v)
	}
	return _u
}

// ClearUIComponentName clears the value of the "ui_component_name" field.
func (_u *EventUpdateOne) ClearUIComponentName() *EventUpdateOne {
	_u.mutation.ClearUIComponentName()
	return _u
}

// SetUIComponentPath sets the "ui_component_path" field.
func (_u *EventUpdateOne) SetUIComponentPath(v string) *EventUpdateOne {
	_u.mutation.SetUIComponentPath(v)
	return _u
}

// SetNillableUIComponentPath sets the "ui_component_path" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableUIComponentPath(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetUIComponentPath(*v)
	}
	return _u
}

// ClearUIComponentPath clears the value of the "ui_component_path" field.
func (_u *EventUpdateOne) ClearUIComponentPath() *EventUpdateOne {
	_u.mutation.ClearUIComponentPath()
	return _u
}

// SetUIComponentType sets the "ui_component_type" field.
func (_u *EventUpdateOne) SetUIComponentType(v string) *EventUpdateOne {
	_u.mutation.SetUIComponentType(v)
	return _u
}

// SetNillableUIComponentType sets the "ui_component_type" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableUIComponentType(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetUIComponentType(*v)
	}
	return _u
}

// ClearUIComponentType clears the value of the "ui_component_type" field.
func (_u *EventUpdateOne) ClearUIComponentType() *EventUpdateOne {
	_u.mutation.ClearUIComponentType()
	return _u
}

// SetUIAction sets the "ui_action" field.
func (_u *EventUpdateOne) SetUIAction(v string) *EventUpdateOne {
	_u.mutation.SetUIAction(v)
	return _u
}

// SetNillableUIAction sets the "ui_action" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableUIAction(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetUIAction(*v)
	}
	return _u
}

// ClearUIAction clears the value of the "ui_action" field.
func (_u *EventUpdateOne) ClearUIAction() *EventUpdateOne {
	_u.mutation.ClearUIAction()
	return _u
}

// SetUIElement sets the "ui_element" field.
func (_u *EventUpdateOne) SetUIElement(v string) *EventUpdateOne {
	_u.mutation.SetUIElement(v)
	return _u
}

// SetNillableUIElement sets the "ui_element" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableUIElement(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetUIElement(*v)
	}
	return _u
}

// ClearUIElement clears the value of the "ui_element" field.
func (_u *EventUpdateOne) ClearUIElement() *EventUpdateOne {
	_u.mutation.ClearUIElement()
	return _u
}

// SetUIElementText sets the "ui_element_text" field.
func (_u *EventUpdateOne) SetUIElementText(v string) *EventUpdateOne {
	_u.mutation.SetUIElementText(v)
	return _u
}

// SetNillableUIElementText sets the "ui_element_text" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableUIElementText(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetUIElementText(*v)
	}
	return _u
}

// ClearUIElementText clears the value of the "ui_element_text" field.
func (_u *EventUpdateOne) ClearUIElementText() *EventUpdateOne {
	_u.mutation.ClearUIElementText()
	return _u
}

// SetUIViewport sets the "ui_viewport" field.
func (_u *EventUpdateOne) SetUIViewport(v string) *EventUpdateOne {
	_u.mutation.SetUIViewport(v)
	return _u
}

// SetNillableUIViewport sets the "ui_viewport" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableUIViewport(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetUIViewport(*v)
	}
	return _u
}

// ClearUIViewport clears the value of the "ui_viewport" field.
func (_u *EventUpdateOne) ClearUIViewport() *EventUpdateOne {
	_u.mutation.ClearUIViewport()
	return _u
}

// SetUIScrollPosition sets the "ui_scroll_position" field.
func (_u *EventUpdateOne) SetUIScrollPosition(v float64) *EventUpdateOne {
	_u.mutation.ResetUIScrollPosition()
	_u.mutation.SetUIScrollPosition(v)
	return _u
}

// SetNillableUIScrollPosition sets the "ui_scroll_position" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableUIScrollPosition(v *float64) *EventUpdateOne {
	if v != nil {
		_u.SetUIScrollPosition(*v)
	}
	return _u
}

// AddUIScrollPosition adds value to the "ui_scroll_position" field.
func (_u *EventUpdateOne) AddUIScrollPosition(v float64) *EventUpdateOne {
	_u.mutation.AddUIScrollPosition(v)
	return _u
}

// ClearUIScrollPosition clears the value of the "ui_scroll_position" field.
func (_u *EventUpdateOne) ClearUIScrollPosition() *EventUpdateOne {
	_u.mutation.ClearUIScrollPosition()
	return _u
}

// SetUIStateKey sets the "ui_state_key" field.
func (_u *EventUpdateOne) SetUIStateKey(v string) *EventUpdateOne {
	_u.mutation.SetUIStateKey(v)
	return _u
}

// SetNillableUIStateKey sets the "ui_state_key" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableUIStateKey(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetUIStateKey(*v)
	}
	return _u
}

// ClearUIStateKey clears the value of the "ui_state_key" field.
func (_u *EventUpdateOne) ClearUIStateKey() *EventUpdateOne {
	_u.mutation.ClearUIStateKey()
	return _u
}

// SetUIStateBefore sets the "ui_state_before" field.
func (_u *EventUpdateOne) SetUIStateBefore(v string) *EventUpdateOne {
	_u.mutation.SetUIStateBefore(v)
	return _u
}

// SetNillableUIStateBefore sets the "ui_state_before" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableUIStateBefore(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetUIStateBefore(*v)
	}
	return _u
}

// ClearUIStateBefore clears the value of the "ui_state_before" field.
func (_u *EventUpdateOne) ClearUIStateBefore() *EventUpdateOne {
	_u.mutation.ClearUIStateBefore()
	return _u
}

// SetUIStateAfter sets the "ui_state_after" field.
func (_u *EventUpdateOne) SetUIStateAfter(v string) *EventUpdateOne {
	_u.mutation.SetUIStateAfter(v)
	return _u
}

// SetNillableUIStateAfter sets the "ui_state_after" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableUIStateAfter(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetUIStateAfter(*v)
	}
	return _u
}

// ClearUIStateAfter clears the value of the "ui_state_after" field.
func (_u *EventUpdateOne) ClearUIStateAfter() *EventUpdateOne {
	_u.mutation.ClearUIStateAfter()
	return _u
}

// SetUIStateChangeType sets the "ui_state_change_type" field.
func (_u *EventUpdateOne) SetUIStateChangeType(v string) *EventUpdateOne {
	_u.mutation.SetUIStateChangeType(v)
	return _u
}

// SetNillableUIStateChangeType sets the "ui_state_change_type" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableUIStateChangeType(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetUIStateChangeType(*v)
	}
	return _u
}

// ClearUIStateChangeType clears the value of the "ui_state_change_type" field.
func (_u *EventUpdateOne) ClearUIStateChangeType() *EventUpdateOne {
	_u.mutation.ClearUIStateChangeType()
	return _u
}

// SetJourneyID sets the "journey_id" field.
func (_u *EventUpdateOne) SetJourneyID(v uuid.UUID) *EventUpdateOne {
	_u.mutation.SetJourneyID(v)
	return _u
}

// SetNillableJourneyID sets the "journey_id" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableJourneyID(v *uuid.UUID) *EventUpdateOne {
	if v != nil {
		_u.SetJourneyID(*v)
	}
	return _u
}

// ClearJourneyID clears the value of the "journey_id" field.
func (_u *EventUpdateOne) ClearJourneyID() *EventUpdateOne {
	_u.mutation.ClearJourneyID()
	return _u
}

// SetJourneyStepID sets the "journey_step_id" field.
func (_u *EventUpdateOne) SetJourneyStepID(v string) *EventUpdateOne {
	_u.mutation.SetJourneyStepID(v)
	return _u
}

// SetNillableJourneyStepID sets the "journey_step_id" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableJourneyStepID(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetJourneyStepID(*v)
	}
	return _u
}

// ClearJourneyStepID clears the value of the "journey_step_id" field.
func (_u *EventUpdateOne) ClearJourneyStepID() *EventUpdateOne {
	_u.mutation.ClearJourneyStepID()
	return _u
}

// SetJourneyStepName sets the "journey_step_name" field.
func (_u *EventUpdateOne) SetJourneyStepName(v string) *EventUpdateOne {
	_u.mutation.SetJourneyStepName(v)
	return _u
}

// SetNillableJourneyStepName sets the "journey_step_name" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableJourneyStepName(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetJourneyStepName(*v)
	}
	return _u
}

// ClearJourneyStepName clears the value of the "journey_step_name" field.
func (_u *EventUpdateOne) ClearJourneyStepName() *EventUpdateOne {
	_u.mutation.ClearJourneyStepName()
	return _u
}

// SetConversionStatus sets the "conversion_status" field.
func (_u *EventUpdateOne) SetConversionStatus(v string) *EventUpdateOne {
	_u.mutation.SetConversionStatus(v)
	return _u
}

// SetNillableConversionStatus sets the "conversion_status" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableConversionStatus(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetConversionStatus(*v)
	}
	return _u
}

// ClearConversionStatus clears the value of the "conversion_status" field.
func (_u *EventUpdateOne) ClearConversionStatus() *EventUpdateOne {
	_u.mutation.ClearConversionStatus()
	return _u
}

// SetAPIMethod sets the "api_method" field.
func (_u *EventUpdateOne) SetAPIMethod(v string) *EventUpdateOne {
	_u.mutation.SetAPIMethod(v)
	return _u
}

// SetNillableAPIMethod sets the "api_method" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableAPIMethod(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetAPIMethod(*v)
	}
	return _u
}

// ClearAPIMethod clears the value of the "api_method" field.
func (_u *EventUpdateOne) ClearAPIMethod() *EventUpdateOne {
	_u.mutation.ClearAPIMethod()
	return _u
}

// SetAPIPath sets the "api_path" field.
func (_u *EventUpdateOne) SetAPIPath(v string) *EventUpdateOne {
	_u.mutation.SetAPIPath(v)
	return _u
}

// SetNillableAPIPath sets the "api_path" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableAPIPath(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetAPIPath(*v)
	}
	return _u
}

// ClearAPIPath clears the value of the "api_path" field.
func (_u *EventUpdateOne) ClearAPIPath() *EventUpdateOne {
	_u.mutation.ClearAPIPath()
	return _u
}

// SetAPIStatusCode sets the "api_status_code" field.
func (_u *EventUpdateOne) SetAPIStatusCode(v int) *EventUpdateOne {
	_u.mutation.ResetAPIStatusCode()
	_u.mutation.SetAPIStatusCode(v)
	return _u
}

// SetNillableAPIStatusCode sets the "api_status_code" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableAPIStatusCode(v *int) *EventUpdateOne {
	if v != nil {
		_u.SetAPIStatusCode(*v)
	}
	return _u
}

// AddAPIStatusCode adds value to the "api_status_code" field.
func (_u *EventUpdateOne) AddAPIStatusCode(v int) *EventUpdateOne {
	_u.mutation.AddAPIStatusCode(v)
	return _u
}

// ClearAPIStatusCode clears the value of the "api_status_code" field.
func (_u *EventUpdateOne) ClearAPIStatusCode() *EventUpdateOne {
	_u.mutation.ClearAPIStatusCode()
	return _u
}

// SetAPIDurationMs sets the "api_duration_ms" field.
func (_u *EventUpdateOne) SetAPIDurationMs(v int64) *EventUpdateOne {
	_u.mutation.ResetAPIDurationMs()
	_u.mutation.SetAPIDurationMs(v)
	return _u
}

// SetNillableAPIDurationMs sets the "api_duration_ms" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableAPIDurationMs(v *int64) *EventUpdateOne {
	if v != nil {
		_u.SetAPIDurationMs(*v)
	}
	return _u
}

// AddAPIDurationMs adds value to the "api_duration_ms" field.
func (_u *EventUpdateOne) AddAPIDurationMs(v int64) *EventUpdateOne {
	_u.mutation.AddAPIDurationMs(v)
	return _u
}

// ClearAPIDurationMs clears the value of the "api_duration_ms" field.
func (_u *EventUpdateOne) ClearAPIDurationMs() *EventUpdateOne {
	_u.mutation.ClearAPIDurationMs()
	return _u
}

// SetErrorType sets the "error_type" field.
func (_u *EventUpdateOne) SetErrorType(v string) *EventUpdateOne {
	_u.mutation.SetErrorType(v)
	return _u
}

// SetNillableErrorType sets the "error_type" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableErrorType(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetErrorType(*v)
	}
	return _u
}

// ClearErrorType clears the value of the "error_type" field.
func (_u *EventUpdateOne) ClearErrorType() *EventUpdateOne {
	_u.mutation.ClearErrorType()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *EventUpdateOne) SetErrorMessage(v string) *EventUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableErrorMessage(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *EventUpdateOne) ClearErrorMessage() *EventUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetErrorStack sets the "error_stack" field.
func (_u *EventUpdateOne) SetErrorStack(v string) *EventUpdateOne {
	_u.mutation.SetErrorStack(v)
	return _u
}

// SetNillableErrorStack sets the "error_stack" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableErrorStack(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetErrorStack(*v)
	}
	return _u
}

// ClearErrorStack clears the value of the "error_stack" field.
func (_u *EventUpdateOne) ClearErrorStack() *EventUpdateOne {
	_u.mutation.ClearErrorStack()
	return _u
}

// SetErrorComponent sets the "error_component" field.
func (_u *EventUpdateOne) SetErrorComponent(v string) *EventUpdateOne {
	_u.mutation.SetErrorComponent(v)
	return _u
}

// SetNillableErrorComponent sets the "error_component" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableErrorComponent(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetErrorComponent(*v)
	}
	return _u
}

// ClearErrorComponent clears the value of the "error_component" field.
func (_u *EventUpdateOne) ClearErrorComponent() *EventUpdateOne {
	_u.mutation.ClearErrorComponent()
	return _u
}

// SetPerformanceLcpMs sets the "performance_lcp_ms" field.
func (_u *EventUpdateOne) SetPerformanceLcpMs(v float64) *EventUpdateOne {
	_u.mutation.ResetPerformanceLcpMs()
	_u.mutation.SetPerformanceLcpMs(v)
	return _u
}

// SetNillablePerformanceLcpMs sets the "performance_lcp_ms" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillablePerformanceLcpMs(v *float64) *EventUpdateOne {
	if v != nil {
		_u.SetPerformanceLcpMs(*v)
	}
	return _u
}

// AddPerformanceLcpMs adds value to the "performance_lcp_ms" field.
func (_u *EventUpdateOne) AddPerformanceLcpMs(v float64) *EventUpdateOne {
	_u.mutation.AddPerformanceLcpMs(v)
	return _u
}

// ClearPerformanceLcpMs clears the value of the "performance_lcp_ms" field.
func (_u *EventUpdateOne) ClearPerformanceLcpMs() *EventUpdateOne {
	_u.mutation.ClearPerformanceLcpMs()
	return _u
}

// SetPerformanceFidMs sets the "performance_fid_ms" field.
func (_u *EventUpdateOne) SetPerformanceFidMs(v float64) *EventUpdateOne {
	_u.mutation.ResetPerformanceFidMs()
	_u.mutation.SetPerformanceFidMs(v)
	return _u
}

// SetNillablePerformanceFidMs sets the "performance_fid_ms" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillablePerformanceFidMs(v *float64) *EventUpdateOne {
	if v != nil {
		_u.SetPerformanceFidMs(*v)
	}
	return _u
}

// AddPerformanceFidMs adds value to the "performance_fid_ms" field.
func (_u *EventUpdateOne) AddPerformanceFidMs(v float64) *EventUpdateOne {
	_u.mutation.AddPerformanceFidMs(v)
	return _u
}

// ClearPerformanceFidMs clears the value of the "performance_fid_ms" field.
func (_u *EventUpdateOne) ClearPerformanceFidMs() *EventUpdateOne {
	_u.mutation.ClearPerformanceFidMs()
	return _u
}

// SetPerformanceCls sets the "performance_cls" field.
func (_u *EventUpdateOne) SetPerformanceCls(v float64) *EventUpdateOne {
	_u.mutation.ResetPerformanceCls()
	_u.mutation.SetPerformanceCls(v)
	return _u
}

// SetNillablePerformanceCls sets the "performance_cls" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillablePerformanceCls(v *float64) *EventUpdateOne {
	if v != nil {
		_u.SetPerformanceCls(*v)
	}
	return _u
}

// AddPerformanceCls adds value to the "performance_cls" field.
func (_u *EventUpdateOne) AddPerformanceCls(v float64) *EventUpdateOne {
	_u.mutation.AddPerformanceCls(v)
	return _u
}

// ClearPerformanceCls clears the value of the "performance_cls" field.
func (_u *EventUpdateOne) ClearPerformanceCls() *EventUpdateOne {
	_u.mutation.ClearPerformanceCls()
	return _u
}

// SetPerformanceTtfbMs sets the "performance_ttfb_ms" field.
func (_u *EventUpdateOne) SetPerformanceTtfbMs(v float64) *EventUpdateOne {
	_u.mutation.ResetPerformanceTtfbMs()
	_u.mutation.SetPerformanceTtfbMs(v)
	return _u
}

// SetNillablePerformanceTtfbMs sets the "performance_ttfb_ms" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillablePerformanceTtfbMs(v *float64) *EventUpdateOne {
	if v != nil {
		_u.SetPerformanceTtfbMs(*v)
	}
	return _u
}

// AddPerformanceTtfbMs adds value to the "performance_ttfb_ms" field.
func (_u *EventUpdateOne) AddPerformanceTtfbMs(v float64) *EventUpdateOne {
	_u.mutation.AddPerformanceTtfbMs(v)
	return _u
}

// ClearPerformanceTtfbMs clears the value of the "performance_ttfb_ms" field.
func (_u *EventUpdateOne) ClearPerformanceTtfbMs() *EventUpdateOne {
	_u.mutation.ClearPerformanceTtfbMs()
	return _u
}

// SetSnapshotURL sets the "snapshot_url" field.
func (_u *EventUpdateOne) SetSnapshotURL(v string) *EventUpdateOne {
	_u.mutation.SetSnapshotURL(v)
	return _u
}

// SetNillableSnapshotURL sets the "snapshot_url" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableSnapshotURL(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetSnapshotURL(*v)
	}
	return _u
}

// ClearSnapshotURL clears the value of the "snapshot_url" field.
func (_u *EventUpdateOne) ClearSnapshotURL() *EventUpdateOne {
	_u.mutation.ClearSnapshotURL()
	return _u
}

// SetSnapshotViewport sets the "snapshot_viewport" field.
func (_u *EventUpdateOne) SetSnapshotViewport(v string) *EventUpdateOne {
	_u.mutation.SetSnapshotViewport(v)
	return _u
}

// SetNillableSnapshotViewport sets the "snapshot_viewport" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableSnapshotViewport(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetSnapshotViewport(*v)
	}
	return _u
}

// ClearSnapshotViewport clears the value of the "snapshot_viewport" field.
func (_u *EventUpdateOne) ClearSnapshotViewport() *EventUpdateOne {
	_u.mutation.ClearSnapshotViewport()
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *EventUpdateOne) SetDurationMs(v int64) *EventUpdateOne {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableDurationMs(v *int64) *EventUpdateOne {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *EventUpdateOne) AddDurationMs(v int64) *EventUpdateOne {
	_u.mutation.AddDurationMs(v)
	return _u
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (_u *EventUpdateOne) ClearDurationMs() *EventUpdateOne {
	_u.mutation.ClearDurationMs()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *EventUpdateOne) SetMetadata(v map[string]interface{}) *EventUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *EventUpdateOne) ClearMetadata() *EventUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *EventUpdateOne) SetProject(v *Project) *EventUpdateOne {
	return _u.SetProjectID(v.ID)
}

// SetJourney sets the "journey" edge to the Journey entity.
func (_u *EventUpdateOne) SetJourney(v *Journey) *EventUpdateOne {
	return _u.SetJourneyID(v.ID)
}

// Mutation returns the EventMutation object of the builder.
func (_u *EventUpdateOne) Mutation() *EventMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *EventUpdateOne) ClearProject() *EventUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// ClearJourney clears the "journey" edge to the Journey entity.
func (_u *EventUpdateOne) ClearJourney() *EventUpdateOne {
	_u.mutation.ClearJourney()
	return _u
}

// Where appends a list predicates to the EventUpdate builder.
func (_u *EventUpdateOne) Where(ps ...predicate.Event) *EventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EventUpdateOne) Select(field string, fields ...string) *EventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Event entity.
func (_u *EventUpdateOne) Save(ctx context.Context) (*Event, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EventUpdateOne) SaveX(ctx context.Context) *Event {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EventUpdateOne) check() error {
	if v, ok := _u.mutation.EventID(); ok {
		if err := event.EventIDValidator(v); err != nil {
			return &ValidationError{Name: "event_id", err: fmt.Errorf(`ent: validator failed for field "Event.event_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SessionID(); ok {
		if err := event.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "Event.session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserID(); ok {
		if err := event.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Event.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EventType(); ok {
		if err := event.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "Event.event_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EventName(); ok {
		if err := event.EventNameValidator(v); err != nil {
			return &ValidationError{Name: "event_name", err: fmt.Errorf(`ent: validator failed for field "Event.event_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PagePath(); ok {
		if err := event.PagePathValidator(v); err != nil {
			return &ValidationError{Name: "page_path", err: fmt.Errorf(`ent: validator failed for field "Event.page_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PageTitle(); ok {
		if err := event.PageTitleValidator(v); err != nil {
			return &ValidationError{Name: "page_title", err: fmt.Errorf(`ent: validator failed for field "Event.page_title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PageURL(); ok {
		if err := event.PageURLValidator(v); err != nil {
			return &ValidationError{Name: "page_url", err: fmt.Errorf(`ent: validator failed for field "Event.page_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PageReferrer(); ok {
		if err := event.PageReferrerValidator(v); err != nil {
			return &ValidationError{Name: "page_referrer", err: fmt.Errorf(`ent: validator failed for field "Event.page_referrer": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UIComponentName(); ok {
		if err := event.UIComponentNameValidator(v); err != nil {
			return &ValidationError{Name: "ui_component_name", err: fmt.Errorf(`ent: validator failed for field "Event.ui_component_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UIComponentPath(); ok {
		if err := event.UIComponentPathValidator(v); err != nil {
			return &ValidationError{Name: "ui_component_path", err: fmt.Errorf(`ent: validator failed for field "Event.ui_component_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UIComponentType(); ok {
		if err := event.UIComponentTypeValidator(v); err != nil {
			return &ValidationError{Name: "ui_component_type", err: fmt.Errorf(`ent: validator failed for field "Event.ui_component_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UIAction(); ok {
		if err := event.UIActionValidator(v); err != nil {
			return &ValidationError{Name: "ui_action", err: fmt.Errorf(`ent: validator failed for field "Event.ui_action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UIElement(); ok {
		if err := event.UIElementValidator(v); err != nil {
			return &ValidationError{Name: "ui_element", err: fmt.Errorf(`ent: validator failed for field "Event.ui_element": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UIElementText(); ok {
		if err := event.UIElementTextValidator(v); err != nil {
			return &ValidationError{Name: "ui_element_text", err: fmt.Errorf(`ent: validator failed for field "Event.ui_element_text": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UIViewport(); ok {
		if err := event.UIViewportValidator(v); err != nil {
			return &ValidationError{Name: "ui_viewport", err: fmt.Errorf(`ent: validator failed for field "Event.ui_viewport": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UIStateKey(); ok {
		if err := event.UIStateKeyValidator(v); err != nil {
			return &ValidationError{Name: "ui_state_key", err: fmt.Errorf(`ent: validator failed for field "Event.ui_state_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UIStateChangeType(); ok {
		if err := event.UIStateChangeTypeValidator(v); err != nil {
			return &ValidationError{Name: "ui_state_change_type", err: fmt.Errorf(`ent: validator failed for field "Event.ui_state_change_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.JourneyStepID(); ok {
		if err := event.JourneyStepIDValidator(v); err != nil {
			return &ValidationError{Name: "journey_step_id", err: fmt.Errorf(`ent: validator failed for field "Event.journey_step_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.JourneyStepName(); ok {
		if err := event.JourneyStepNameValidator(v); err != nil {
			return &ValidationError{Name: "journey_step_name", err: fmt.Errorf(`ent: validator failed for field "Event.journey_step_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConversionStatus(); ok {
		if err := event.ConversionStatusValidator(v); err != nil {
			return &ValidationError{Name: "conversion_status", err: fmt.Errorf(`ent: validator failed for field "Event.conversion_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIMethod(); ok {
		if err := event.APIMethodValidator(v); err != nil {
			return &ValidationError{Name: "api_method", err: fmt.Errorf(`ent: validator failed for field "Event.api_method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIPath(); ok {
		if err := event.APIPathValidator(v); err != nil {
			return &ValidationError{Name: "api_path", err: fmt.Errorf(`ent: validator failed for field "Event.api_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorType(); ok {
		if err := event.ErrorTypeValidator(v); err != nil {
			return &ValidationError{Name: "error_type", err: fmt.Errorf(`ent: validator failed for field "Event.error_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorComponent(); ok {
		if err := event.ErrorComponentValidator(v); err != nil {
			return &ValidationError{Name: "error_component", err: fmt.Errorf(`ent: validator failed for field "Event.error_component": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SnapshotURL(); ok {
		if err := event.SnapshotURLValidator(v); err != nil {
			return &ValidationError{Name: "snapshot_url", err: fmt.Errorf(`ent: validator failed for field "Event.snapshot_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SnapshotViewport(); ok {
		if err := event.SnapshotViewportValidator(v); err != nil {
			return &ValidationError{Name: "snapshot_viewport", err: fmt.Errorf(`ent: validator failed for field "Event.snapshot_viewport": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Event.project"`)
	}
	return nil
}

func (_u *EventUpdateOne) sqlSave(ctx context.Context) (_node *Event, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(event.Table, event.Columns, sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Event.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, event.FieldID)
		for _, f := range fields {
			if !event.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != event.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrgID(); ok {
		_spec.SetField(event.FieldOrgID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.EventID(); ok {
		_spec.SetField(event.FieldEventID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(event.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(event.FieldUserID, field.TypeString, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(event.FieldUserID, field.TypeString)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(event.FieldEventType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.EventName(); ok {
		_spec.SetField(event.FieldEventName, field.TypeString, value)
	}
	if _u.mutation.EventNameCleared() {
		_spec.ClearField(event.FieldEventName, field.TypeString)
	}
	if value, ok := _u.mutation.Timestamp(); ok {
		_spec.SetField(event.FieldTimestamp, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Sequence(); ok {
		_spec.SetField(event.FieldSequence, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSequence(); ok {
		_spec.AddField(event.FieldSequence, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PagePath(); ok {
		_spec.SetField(event.FieldPagePath, field.TypeString, value)
	}
	if _u.mutation.PagePathCleared() {
		_spec.ClearField(event.FieldPagePath, field.TypeString)
	}
	if value, ok := _u.mutation.PageTitle(); ok {
		_spec.SetField(event.FieldPageTitle, field.TypeString, value)
	}
	if _u.mutation.PageTitleCleared() {
		_spec.ClearField(event.FieldPageTitle, field.TypeString)
	}
	if value, ok := _u.mutation.PageURL(); ok {
		_spec.SetField(event.FieldPageURL, field.TypeString, value)
	}
	if _u.mutation.PageURLCleared() {
		_spec.ClearField(event.FieldPageURL, field.TypeString)
	}
	if value, ok := _u.mutation.PageReferrer(); ok {
		_spec.SetField(event.FieldPageReferrer, field.TypeString, value)
	}
	if _u.mutation.PageReferrerCleared() {
		_spec.ClearField(event.FieldPageReferrer, field.TypeString)
	}
	if value, ok := _u.mutation.UIComponentName(); ok {
		_spec.SetField(event.FieldUIComponentName, field.TypeString, value)
	}
	if _u.mutation.UIComponentNameCleared() {
		_spec.ClearField(event.FieldUIComponentName, field.TypeString)
	}
	if value, ok := _u.mutation.UIComponentPath(); ok {
		_spec.SetField(event.FieldUIComponentPath, field.TypeString, value)
	}
	if _u.mutation.UIComponentPathCleared() {
		_spec.ClearField(event.FieldUIComponentPath, field.TypeString)
	}
	if value, ok := _u.mutation.UIComponentType(); ok {
		_spec.SetField(event.FieldUIComponentType, field.TypeString, value)
	}
	if _u.mutation.UIComponentTypeCleared() {
		_spec.ClearField(event.FieldUIComponentType, field.TypeString)
	}
	if value, ok := _u.mutation.UIAction(); ok {
		_spec.SetField(event.FieldUIAction, field.TypeString, value)
	}
	if _u.mutation.UIActionCleared() {
		_spec.ClearField(event.FieldUIAction, field.TypeString)
	}
	if value, ok := _u.mutation.UIElement(); ok {
		_spec.SetField(event.FieldUIElement, field.TypeString, value)
	}
	if _u.mutation.UIElementCleared() {
		_spec.ClearField(event.FieldUIElement, field.TypeString)
	}
	if value, ok := _u.mutation.UIElementText(); ok {
		_spec.SetField(event.FieldUIElementText, field.TypeString, value)
	}
	if _u.mutation.UIElementTextCleared() {
		_spec.ClearField(event.FieldUIElementText, field.TypeString)
	}
	if value, ok := _u.mutation.UIViewport(); ok {
		_spec.SetField(event.FieldUIViewport, field.TypeString, value)
	}
	if _u.mutation.UIViewportCleared() {
		_spec.ClearField(event.FieldUIViewport, field.TypeString)
	}
	if value, ok := _u.mutation.UIScrollPosition(); ok {
		_spec.SetField(event.FieldUIScrollPosition, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUIScrollPosition(); ok {
		_spec.AddField(event.FieldUIScrollPosition, field.TypeFloat64, value)
	}
	if _u.mutation.UIScrollPositionCleared() {
		_spec.ClearField(event.FieldUIScrollPosition, field.TypeFloat64)
	}
	if value, ok := _u.mutation.UIStateKey(); ok {
		_spec.SetField(event.FieldUIStateKey, field.TypeString, value)
	}
	if _u.mutation.UIStateKeyCleared() {
		_spec.ClearField(event.FieldUIStateKey, field.TypeString)
	}
	if value, ok := _u.mutation.UIStateBefore(); ok {
		_spec.SetField(event.FieldUIStateBefore, field.TypeString, value)
	}
	if _u.mutation.UIStateBeforeCleared() {
		_spec.ClearField(event.FieldUIStateBefore, field.TypeString)
	}
	if value, ok := _u.mutation.UIStateAfter(); ok {
		_spec.SetField(event.FieldUIStateAfter, field.TypeString, value)
	}
	if _u.mutation.UIStateAfterCleared() {
		_spec.ClearField(event.FieldUIStateAfter, field.TypeString)
	}
	if value, ok := _u.mutation.UIStateChangeType(); ok {
		_spec.SetField(event.FieldUIStateChangeType, field.TypeString, value)
	}
	if _u.mutation.UIStateChangeTypeCleared() {
		_spec.ClearField(event.FieldUIStateChangeType, field.TypeString)
	}
	if value, ok := _u.mutation.JourneyStepID(); ok {
		_spec.SetField(event.FieldJourneyStepID, field.TypeString, value)
	}
	if _u.mutation.JourneyStepIDCleared() {
		_spec.ClearField(event.FieldJourneyStepID, field.TypeString)
	}
	if value, ok := _u.mutation.JourneyStepName(); ok {
		_spec.SetField(event.FieldJourneyStepName, field.TypeString, value)
	}
	if _u.mutation.JourneyStepNameCleared() {
		_spec.ClearField(event.FieldJourneyStepName, field.TypeString)
	}
	if value, ok := _u.mutation.ConversionStatus(); ok {
		_spec.SetField(event.FieldConversionStatus, field.TypeString, value)
	}
	if _u.mutation.ConversionStatusCleared() {
		_spec.ClearField(event.FieldConversionStatus, field.TypeString)
	}
	if value, ok := _u.mutation.APIMethod(); ok {
		_spec.SetField(event.FieldAPIMethod, field.TypeString, value)
	}
	if _u.mutation.APIMethodCleared() {
		_spec.ClearField(event.FieldAPIMethod, field.TypeString)
	}
	if value, ok := _u.mutation.APIPath(); ok {
		_spec.SetField(event.FieldAPIPath, field.TypeString, value)
	}
	if _u.mutation.APIPathCleared() {
		_spec.ClearField(event.FieldAPIPath, field.TypeString)
	}
	if value, ok := _u.mutation.APIStatusCode(); ok {
		_spec.SetField(event.FieldAPIStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAPIStatusCode(); ok {
		_spec.AddField(event.FieldAPIStatusCode, field.TypeInt, value)
	}
	if _u.mutation.APIStatusCodeCleared() {
		_spec.ClearField(event.FieldAPIStatusCode, field.TypeInt)
	}
	if value, ok := _u.mutation.APIDurationMs(); ok {
		_spec.SetField(event.FieldAPIDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIDurationMs(); ok {
		_spec.AddField(event.FieldAPIDurationMs, field.TypeInt64, value)
	}
	if _u.mutation.APIDurationMsCleared() {
		_spec.ClearField(event.FieldAPIDurationMs, field.TypeInt64)
	}
	if value, ok := _u.mutation.ErrorType(); ok {
		_spec.SetField(event.FieldErrorType, field.TypeString, value)
	}
	if _u.mutation.ErrorTypeCleared() {
		_spec.ClearField(event.FieldErrorType, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(event.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(event.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorStack(); ok {
		_spec.SetField(event.FieldErrorStack, field.TypeString, value)
	}
	if _u.mutation.ErrorStackCleared() {
		_spec.ClearField(event.FieldErrorStack, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorComponent(); ok {
		_spec.SetField(event.FieldErrorComponent, field.TypeString, value)
	}
	if _u.mutation.ErrorComponentCleared() {
		_spec.ClearField(event.FieldErrorComponent, field.TypeString)
	}
	if value, ok := _u.mutation.PerformanceLcpMs(); ok {
		_spec.SetField(event.FieldPerformanceLcpMs, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPerformanceLcpMs(); ok {
		_spec.AddField(event.FieldPerformanceLcpMs, field.TypeFloat64, value)
	}
	if _u.mutation.PerformanceLcpMsCleared() {
		_spec.ClearField(event.FieldPerformanceLcpMs, field.TypeFloat64)
	}
	if value, ok := _u.mutation.PerformanceFidMs(); ok {
		_spec.SetField(event.FieldPerformanceFidMs, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPerformanceFidMs(); ok {
		_spec.AddField(event.FieldPerformanceFidMs, field.TypeFloat64, value)
	}
	if _u.mutation.PerformanceFidMsCleared() {
		_spec.ClearField(event.FieldPerformanceFidMs, field.TypeFloat64)
	}
	if value, ok := _u.mutation.PerformanceCls(); ok {
		_spec.SetField(event.FieldPerformanceCls, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPerformanceCls(); ok {
		_spec.AddField(event.FieldPerformanceCls, field.TypeFloat64, value)
	}
	if _u.mutation.PerformanceClsCleared() {
		_spec.ClearField(event.FieldPerformanceCls, field.TypeFloat64)
	}
	if value, ok := _u.mutation.PerformanceTtfbMs(); ok {
		_spec.SetField(event.FieldPerformanceTtfbMs, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPerformanceTtfbMs(); ok {
		_spec.AddField(event.FieldPerformanceTtfbMs, field.TypeFloat64, value)
	}
	if _u.mutation.PerformanceTtfbMsCleared() {
		_spec.ClearField(event.FieldPerformanceTtfbMs, field.TypeFloat64)
	}
	if value, ok := _u.mutation.SnapshotURL(); ok {
		_spec.SetField(event.FieldSnapshotURL, field.TypeString, value)
	}
	if _u.mutation.SnapshotURLCleared() {
		_spec.ClearField(event.FieldSnapshotURL, field.TypeString)
	}
	if value, ok := _u.mutation.SnapshotViewport(); ok {
		_spec.SetField(event.FieldSnapshotViewport, field.TypeString, value)
	}
	if _u.mutation.SnapshotViewportCleared() {
		_spec.ClearField(event.FieldSnapshotViewport, field.TypeString)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(event.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(event.FieldDurationMs, field.TypeInt64, value)
	}
	if _u.mutation.DurationMsCleared() {
		_spec.ClearField(event.FieldDurationMs, field.TypeInt64)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(event.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(event.FieldMetadata, field.TypeJSON)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.ProjectTable,
			Columns: []string{event.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.ProjectTable,
			Columns: []string{event.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.JourneyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.JourneyTable,
			Columns: []string{event.JourneyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(journey.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.JourneyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.JourneyTable,
			Columns: []string{event.JourneyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(journey.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Event{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{event.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
