// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/plexusone/productgraph/ent/capability"
	"github.com/plexusone/productgraph/ent/feature"
	"github.com/plexusone/productgraph/ent/journey"
	"github.com/plexusone/productgraph/ent/predicate"
	"github.com/plexusone/productgraph/ent/schema"
)

// FeatureUpdate is the builder for updating Feature entities.
type FeatureUpdate struct {
	config
	hooks    []Hook
	mutation *FeatureMutation
}

// Where appends a list predicates to the FeatureUpdate builder.
func (_u *FeatureUpdate) Where(ps ...predicate.Feature) *FeatureUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOrgID sets the "org_id" field.
func (_u *FeatureUpdate) SetOrgID(v uuid.UUID) *FeatureUpdate {
	_u.mutation.SetOrgID(v)
	return _u
}

// SetNillableOrgID sets the "org_id" field if the given value is not nil.
func (_u *FeatureUpdate) SetNillableOrgID(v *uuid.UUID) *FeatureUpdate {
	if v != nil {
		_u.SetOrgID(*v)
	}
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *FeatureUpdate) SetProductID(v uuid.UUID) *FeatureUpdate {
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *FeatureUpdate) SetNillableProductID(v *uuid.UUID) *FeatureUpdate {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// SetCapabilityID sets the "capability_id" field.
func (_u *FeatureUpdate) SetCapabilityID(v uuid.UUID) *FeatureUpdate {
	_u.mutation.SetCapabilityID(v)
	return _u
}

// SetNillableCapabilityID sets the "capability_id" field if the given value is not nil.
func (_u *FeatureUpdate) SetNillableCapabilityID(v *uuid.UUID) *FeatureUpdate {
	if v != nil {
		_u.SetCapabilityID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *FeatureUpdate) SetName(v string) *FeatureUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *FeatureUpdate) SetNillableName(v *string) *FeatureUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *FeatureUpdate) SetDescription(v string) *FeatureUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *FeatureUpdate) SetNillableDescription(v *string) *FeatureUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *FeatureUpdate) ClearDescription() *FeatureUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetAdminPath sets the "admin_path" field.
func (_u *FeatureUpdate) SetAdminPath(v string) *FeatureUpdate {
	_u.mutation.SetAdminPath(v)
	return _u
}

// SetNillableAdminPath sets the "admin_path" field if the given value is not nil.
func (_u *FeatureUpdate) SetNillableAdminPath(v *string) *FeatureUpdate {
	if v != nil {
		_u.SetAdminPath(*v)
	}
	return _u
}

// ClearAdminPath clears the value of the "admin_path" field.
func (_u *FeatureUpdate) ClearAdminPath() *FeatureUpdate {
	_u.mutation.ClearAdminPath()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *FeatureUpdate) SetNotes(v string) *FeatureUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *FeatureUpdate) SetNillableNotes(v *string) *FeatureUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *FeatureUpdate) ClearNotes() *FeatureUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetDocumentation sets the "documentation" field.
func (_u *FeatureUpdate) SetDocumentation(v []schema.DocumentationLink) *FeatureUpdate {
	_u.mutation.SetDocumentation(v)
	return _u
}

// AppendDocumentation appends value to the "documentation" field.
func (_u *FeatureUpdate) AppendDocumentation(v []schema.DocumentationLink) *FeatureUpdate {
	_u.mutation.AppendDocumentation(v)
	return _u
}

// ClearDocumentation clears the value of the "documentation" field.
func (_u *FeatureUpdate) ClearDocumentation() *FeatureUpdate {
	_u.mutation.ClearDocumentation()
	return _u
}

// SetDisplayOrder sets the "display_order" field.
func (_u *FeatureUpdate) SetDisplayOrder(v int) *FeatureUpdate {
	_u.mutation.ResetDisplayOrder()
	_u.mutation.SetDisplayOrder(v)
	return _u
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_u *FeatureUpdate) SetNillableDisplayOrder(v *int) *FeatureUpdate {
	if v != nil {
		_u.SetDisplayOrder(*v)
	}
	return _u
}

// AddDisplayOrder adds value to the "display_order" field.
func (_u *FeatureUpdate) AddDisplayOrder(v int) *FeatureUpdate {
	_u.mutation.AddDisplayOrder(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FeatureUpdate) SetUpdatedAt(v time.Time) *FeatureUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCapability sets the "capability" edge to the Capability entity.
func (_u *FeatureUpdate) SetCapability(v *Capability) *FeatureUpdate {
	return _u.SetCapabilityID(v.ID)
}

// AddJourneyIDs adds the "journeys" edge to the Journey entity by IDs.
func (_u *FeatureUpdate) AddJourneyIDs(ids ...uuid.UUID) *FeatureUpdate {
	_u.mutation.AddJourneyIDs(ids...)
	return _u
}

// AddJourneys adds the "journeys" edges to the Journey entity.
func (_u *FeatureUpdate) AddJourneys(v ...*Journey) *FeatureUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddJourneyIDs(ids...)
}

// Mutation returns the FeatureMutation object of the builder.
func (_u *FeatureUpdate) Mutation() *FeatureMutation {
	return _u.mutation
}

// ClearCapability clears the "capability" edge to the Capability entity.
func (_u *FeatureUpdate) ClearCapability() *FeatureUpdate {
	_u.mutation.ClearCapability()
	return _u
}

// ClearJourneys clears all "journeys" edges to the Journey entity.
func (_u *FeatureUpdate) ClearJourneys() *FeatureUpdate {
	_u.mutation.ClearJourneys()
	return _u
}

// RemoveJourneyIDs removes the "journeys" edge to Journey entities by IDs.
func (_u *FeatureUpdate) RemoveJourneyIDs(ids ...uuid.UUID) *FeatureUpdate {
	_u.mutation.RemoveJourneyIDs(ids...)
	return _u
}

// RemoveJourneys removes "journeys" edges to Journey entities.
func (_u *FeatureUpdate) RemoveJourneys(v ...*Journey) *FeatureUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveJourneyIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FeatureUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FeatureUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FeatureUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FeatureUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FeatureUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := feature.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FeatureUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := feature.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Feature.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AdminPath(); ok {
		if err := feature.AdminPathValidator(v); err != nil {
			return &ValidationError{Name: "admin_path", err: fmt.Errorf(`ent: validator failed for field "Feature.admin_path": %w`, err)}
		}
	}
	if _u.mutation.CapabilityCleared() && len(_u.mutation.CapabilityIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Feature.capability"`)
	}
	return nil
}

func (_u *FeatureUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(feature.Table, feature.Columns, sqlgraph.NewFieldSpec(feature.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrgID(); ok {
		_spec.SetField(feature.FieldOrgID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ProductID(); ok {
		_spec.SetField(feature.FieldProductID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(feature.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(feature.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(feature.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.AdminPath(); ok {
		_spec.SetField(feature.FieldAdminPath, field.TypeString, value)
	}
	if _u.mutation.AdminPathCleared() {
		_spec.ClearField(feature.FieldAdminPath, field.TypeString)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(feature.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(feature.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.Documentation(); ok {
		_spec.SetField(feature.FieldDocumentation, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDocumentation(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, feature.FieldDocumentation, value)
		})
	}
	if _u.mutation.DocumentationCleared() {
		_spec.ClearField(feature.FieldDocumentation, field.TypeJSON)
	}
	if value, ok := _u.mutation.DisplayOrder(); ok {
		_spec.SetField(feature.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDisplayOrder(); ok {
		_spec.AddField(feature.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(feature.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CapabilityCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   feature.CapabilityTable,
			Columns: []string{feature.CapabilityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(capability.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CapabilityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   feature.CapabilityTable,
			Columns: []string{feature.CapabilityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(capability.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.JourneysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   feature.JourneysTable,
			Columns: []string{feature.JourneysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(journey.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedJourneysIDs(); len(nodes) > 0 && !_u.mutation.JourneysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   feature.JourneysTable,
			Columns: []string{feature.JourneysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(journey.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.JourneysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   feature.JourneysTable,
			Columns: []string{feature.JourneysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(journey.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{feature.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FeatureUpdateOne is the builder for updating a single Feature entity.
type FeatureUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FeatureMutation
}

// SetOrgID sets the "org_id" field.
func (_u *FeatureUpdateOne) SetOrgID(v uuid.UUID) *FeatureUpdateOne {
	_u.mutation.SetOrgID(v)
	return _u
}

// SetNillableOrgID sets the "org_id" field if the given value is not nil.
func (_u *FeatureUpdateOne) SetNillableOrgID(v *uuid.UUID) *FeatureUpdateOne {
	if v != nil {
		_u.SetOrgID(*v)
	}
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *FeatureUpdateOne) SetProductID(v uuid.UUID) *FeatureUpdateOne {
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *FeatureUpdateOne) SetNillableProductID(v *uuid.UUID) *FeatureUpdateOne {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// SetCapabilityID sets the "capability_id" field.
func (_u *FeatureUpdateOne) SetCapabilityID(v uuid.UUID) *FeatureUpdateOne {
	_u.mutation.SetCapabilityID(v)
	return _u
}

// SetNillableCapabilityID sets the "capability_id" field if the given value is not nil.
func (_u *FeatureUpdateOne) SetNillableCapabilityID(v *uuid.UUID) *FeatureUpdateOne {
	if v != nil {
		_u.SetCapabilityID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *FeatureUpdateOne) SetName(v string) *FeatureUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *FeatureUpdateOne) SetNillableName(v *string) *FeatureUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *FeatureUpdateOne) SetDescription(v string) *FeatureUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *FeatureUpdateOne) SetNillableDescription(v *string) *FeatureUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *FeatureUpdateOne) ClearDescription() *FeatureUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetAdminPath sets the "admin_path" field.
func (_u *FeatureUpdateOne) SetAdminPath(v string) *FeatureUpdateOne {
	_u.mutation.SetAdminPath(v)
	return _u
}

// SetNillableAdminPath sets the "admin_path" field if the given value is not nil.
func (_u *FeatureUpdateOne) SetNillableAdminPath(v *string) *FeatureUpdateOne {
	if v != nil {
		_u.SetAdminPath(*v)
	}
	return _u
}

// ClearAdminPath clears the value of the "admin_path" field.
func (_u *FeatureUpdateOne) ClearAdminPath() *FeatureUpdateOne {
	_u.mutation.ClearAdminPath()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *FeatureUpdateOne) SetNotes(v string) *FeatureUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *FeatureUpdateOne) SetNillableNotes(v *string) *FeatureUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *FeatureUpdateOne) ClearNotes() *FeatureUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetDocumentation sets the "documentation" field.
func (_u *FeatureUpdateOne) SetDocumentation(v []schema.DocumentationLink) *FeatureUpdateOne {
	_u.mutation.SetDocumentation(v)
	return _u
}

// AppendDocumentation appends value to the "documentation" field.
func (_u *FeatureUpdateOne) AppendDocumentation(v []schema.DocumentationLink) *FeatureUpdateOne {
	_u.mutation.AppendDocumentation(v)
	return _u
}

// ClearDocumentation clears the value of the "documentation" field.
func (_u *FeatureUpdateOne) ClearDocumentation() *FeatureUpdateOne {
	_u.mutation.ClearDocumentation()
	return _u
}

// SetDisplayOrder sets the "display_order" field.
func (_u *FeatureUpdateOne) SetDisplayOrder(v int) *FeatureUpdateOne {
	_u.mutation.ResetDisplayOrder()
	_u.mutation.SetDisplayOrder(v)
	return _u
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_u *FeatureUpdateOne) SetNillableDisplayOrder(v *int) *FeatureUpdateOne {
	if v != nil {
		_u.SetDisplayOrder(*v)
	}
	return _u
}

// AddDisplayOrder adds value to the "display_order" field.
func (_u *FeatureUpdateOne) AddDisplayOrder(v int) *FeatureUpdateOne {
	_u.mutation.AddDisplayOrder(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FeatureUpdateOne) SetUpdatedAt(v time.Time) *FeatureUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCapability sets the "capability" edge to the Capability entity.
func (_u *FeatureUpdateOne) SetCapability(v *Capability) *FeatureUpdateOne {
	return _u.SetCapabilityID(v.ID)
}

// AddJourneyIDs adds the "journeys" edge to the Journey entity by IDs.
func (_u *FeatureUpdateOne) AddJourneyIDs(ids ...uuid.UUID) *FeatureUpdateOne {
	_u.mutation.AddJourneyIDs(ids...)
	return _u
}

// AddJourneys adds the "journeys" edges to the Journey entity.
func (_u *FeatureUpdateOne) AddJourneys(v ...*Journey) *FeatureUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddJourneyIDs(ids...)
}

// Mutation returns the FeatureMutation object of the builder.
func (_u *FeatureUpdateOne) Mutation() *FeatureMutation {
	return _u.mutation
}

// ClearCapability clears the "capability" edge to the Capability entity.
func (_u *FeatureUpdateOne) ClearCapability() *FeatureUpdateOne {
	_u.mutation.ClearCapability()
	return _u
}

// ClearJourneys clears all "journeys" edges to the Journey entity.
func (_u *FeatureUpdateOne) ClearJourneys() *FeatureUpdateOne {
	_u.mutation.ClearJourneys()
	return _u
}

// RemoveJourneyIDs removes the "journeys" edge to Journey entities by IDs.
func (_u *FeatureUpdateOne) RemoveJourneyIDs(ids ...uuid.UUID) *FeatureUpdateOne {
	_u.mutation.RemoveJourneyIDs(ids...)
	return _u
}

// RemoveJourneys removes "journeys" edges to Journey entities.
func (_u *FeatureUpdateOne) RemoveJourneys(v ...*Journey) *FeatureUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveJourneyIDs(ids...)
}

// Where appends a list predicates to the FeatureUpdate builder.
func (_u *FeatureUpdateOne) Where(ps ...predicate.Feature) *FeatureUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FeatureUpdateOne) Select(field string, fields ...string) *FeatureUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Feature entity.
func (_u *FeatureUpdateOne) Save(ctx context.Context) (*Feature, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FeatureUpdateOne) SaveX(ctx context.Context) *Feature {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FeatureUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FeatureUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FeatureUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := feature.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FeatureUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := feature.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Feature.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AdminPath(); ok {
		if err := feature.AdminPathValidator(v); err != nil {
			return &ValidationError{Name: "admin_path", err: fmt.Errorf(`ent: validator failed for field "Feature.admin_path": %w`, err)}
		}
	}
	if _u.mutation.CapabilityCleared() && len(_u.mutation.CapabilityIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Feature.capability"`)
	}
	return nil
}

func (_u *FeatureUpdateOne) sqlSave(ctx context.Context) (_node *Feature, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(feature.Table, feature.Columns, sqlgraph.NewFieldSpec(feature.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Feature.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, feature.FieldID)
		for _, f := range fields {
			if !feature.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != feature.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrgID(); ok {
		_spec.SetField(feature.FieldOrgID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ProductID(); ok {
		_spec.SetField(feature.FieldProductID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(feature.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(feature.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(feature.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.AdminPath(); ok {
		_spec.SetField(feature.FieldAdminPath, field.TypeString, value)
	}
	if _u.mutation.AdminPathCleared() {
		_spec.ClearField(feature.FieldAdminPath, field.TypeString)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(feature.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(feature.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.Documentation(); ok {
		_spec.SetField(feature.FieldDocumentation, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDocumentation(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, feature.FieldDocumentation, value)
		})
	}
	if _u.mutation.DocumentationCleared() {
		_spec.ClearField(feature.FieldDocumentation, field.TypeJSON)
	}
	if value, ok := _u.mutation.DisplayOrder(); ok {
		_spec.SetField(feature.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDisplayOrder(); ok {
		_spec.AddField(feature.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(feature.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CapabilityCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   feature.CapabilityTable,
			Columns: []string{feature.CapabilityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(capability.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CapabilityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   feature.CapabilityTable,
			Columns: []string{feature.CapabilityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(capability.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.JourneysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   feature.JourneysTable,
			Columns: []string{feature.JourneysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(journey.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedJourneysIDs(); len(nodes) > 0 && !_u.mutation.JourneysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   feature.JourneysTable,
			Columns: []string{feature.JourneysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(journey.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.JourneysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   feature.JourneysTable,
			Columns: []string{feature.JourneysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(journey.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Feature{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{feature.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
