// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/plexusone/productgraph/ent/feature"
	"github.com/plexusone/productgraph/ent/journey"
	"github.com/plexusone/productgraph/ent/product"
)

// Journey is the model entity for the Journey schema.
type Journey struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// OrgID holds the value of the "org_id" field.
	OrgID uuid.UUID `json:"org_id,omitempty"`
	// ProductID holds the value of the "product_id" field.
	ProductID uuid.UUID `json:"product_id,omitempty"`
	// FeatureID holds the value of the "feature_id" field.
	FeatureID *uuid.UUID `json:"feature_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// EntryConditions holds the value of the "entry_conditions" field.
	EntryConditions []interface{} `json:"entry_conditions,omitempty"`
	// ExitConditions holds the value of the "exit_conditions" field.
	ExitConditions []interface{} `json:"exit_conditions,omitempty"`
	// Steps holds the value of the "steps" field.
	Steps []interface{} `json:"steps,omitempty"`
	// TimeoutMinutes holds the value of the "timeout_minutes" field.
	TimeoutMinutes int `json:"timeout_minutes,omitempty"`
	// TotalSessions holds the value of the "total_sessions" field.
	TotalSessions int64 `json:"total_sessions,omitempty"`
	// ConvertedSessions holds the value of the "converted_sessions" field.
	ConvertedSessions int64 `json:"converted_sessions,omitempty"`
	// ConversionRate holds the value of the "conversion_rate" field.
	ConversionRate float64 `json:"conversion_rate,omitempty"`
	// AvgDurationMs holds the value of the "avg_duration_ms" field.
	AvgDurationMs int64 `json:"avg_duration_ms,omitempty"`
	// IsActive holds the value of the "is_active" field.
	IsActive bool `json:"is_active,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the JourneyQuery when eager-loading is set.
	Edges        JourneyEdges `json:"edges"`
	selectValues sql.SelectValues
}

// JourneyEdges holds the relations/edges for other nodes in the graph.
type JourneyEdges struct {
	// Product holds the value of the product edge.
	Product *Product `json:"product,omitempty"`
	// Feature holds the value of the feature edge.
	Feature *Feature `json:"feature,omitempty"`
	// Events holds the value of the events edge.
	Events []*Event `json:"events,omitempty"`
	// Sessions holds the value of the sessions edge.
	Sessions []*Session `json:"sessions,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// ProductOrErr returns the Product value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e JourneyEdges) ProductOrErr() (*Product, error) {
	if e.Product != nil {
		return e.Product, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: product.Label}
	}
	return nil, &NotLoadedError{edge: "product"}
}

// FeatureOrErr returns the Feature value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e JourneyEdges) FeatureOrErr() (*Feature, error) {
	if e.Feature != nil {
		return e.Feature, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: feature.Label}
	}
	return nil, &NotLoadedError{edge: "feature"}
}

// EventsOrErr returns the Events value or an error if the edge
// was not loaded in eager-loading.
func (e JourneyEdges) EventsOrErr() ([]*Event, error) {
	if e.loadedTypes[2] {
		return e.Events, nil
	}
	return nil, &NotLoadedError{edge: "events"}
}

// SessionsOrErr returns the Sessions value or an error if the edge
// was not loaded in eager-loading.
func (e JourneyEdges) SessionsOrErr() ([]*Session, error) {
	if e.loadedTypes[3] {
		return e.Sessions, nil
	}
	return nil, &NotLoadedError{edge: "sessions"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Journey) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case journey.FieldFeatureID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case journey.FieldEntryConditions, journey.FieldExitConditions, journey.FieldSteps:
			values[i] = new([]byte)
		case journey.FieldIsActive:
			values[i] = new(sql.NullBool)
		case journey.FieldConversionRate:
			values[i] = new(sql.NullFloat64)
		case journey.FieldTimeoutMinutes, journey.FieldTotalSessions, journey.FieldConvertedSessions, journey.FieldAvgDurationMs:
			values[i] = new(sql.NullInt64)
		case journey.FieldName, journey.FieldDescription:
			values[i] = new(sql.NullString)
		case journey.FieldCreatedAt, journey.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case journey.FieldID, journey.FieldOrgID, journey.FieldProductID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Journey fields.
func (_m *Journey) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case journey.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case journey.FieldOrgID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field org_id", values[i])
			} else if value != nil {
				_m.OrgID = *value
			}
		case journey.FieldProductID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field product_id", values[i])
			} else if value != nil {
				_m.ProductID = *value
			}
		case journey.FieldFeatureID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field feature_id", values[i])
			} else if value.Valid {
				_m.FeatureID = new(uuid.UUID)
				*_m.FeatureID = *value.S.(*uuid.UUID)
			}
		case journey.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case journey.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case journey.FieldEntryConditions:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field entry_conditions", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.EntryConditions); err != nil {
					return fmt.Errorf("unmarshal field entry_conditions: %w", err)
				}
			}
		case journey.FieldExitConditions:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field exit_conditions", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ExitConditions); err != nil {
					return fmt.Errorf("unmarshal field exit_conditions: %w", err)
				}
			}
		case journey.FieldSteps:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field steps", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Steps); err != nil {
					return fmt.Errorf("unmarshal field steps: %w", err)
				}
			}
		case journey.FieldTimeoutMinutes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field timeout_minutes", values[i])
			} else if value.Valid {
				_m.TimeoutMinutes = int(value.Int64)
			}
		case journey.FieldTotalSessions:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_sessions", values[i])
			} else if value.Valid {
				_m.TotalSessions = value.Int64
			}
		case journey.FieldConvertedSessions:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field converted_sessions", values[i])
			} else if value.Valid {
				_m.ConvertedSessions = value.Int64
			}
		case journey.FieldConversionRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field conversion_rate", values[i])
			} else if value.Valid {
				_m.ConversionRate = value.Float64
			}
		case journey.FieldAvgDurationMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field avg_duration_ms", values[i])
			} else if value.Valid {
				_m.AvgDurationMs = value.Int64
			}
		case journey.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case journey.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case journey.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Journey.
// This includes values selected through modifiers, order, etc.
func (_m *Journey) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProduct queries the "product" edge of the Journey entity.
func (_m *Journey) QueryProduct() *ProductQuery {
	return NewJourneyClient(_m.config).QueryProduct(_m)
}

// QueryFeature queries the "feature" edge of the Journey entity.
func (_m *Journey) QueryFeature() *FeatureQuery {
	return NewJourneyClient(_m.config).QueryFeature(_m)
}

// QueryEvents queries the "events" edge of the Journey entity.
func (_m *Journey) QueryEvents() *EventQuery {
	return NewJourneyClient(_m.config).QueryEvents(_m)
}

// QuerySessions queries the "sessions" edge of the Journey entity.
func (_m *Journey) QuerySessions() *SessionQuery {
	return NewJourneyClient(_m.config).QuerySessions(_m)
}

// Update returns a builder for updating this Journey.
// Note that you need to call Journey.Unwrap() before calling this method if this Journey
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Journey) Update() *JourneyUpdateOne {
	return NewJourneyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Journey entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Journey) Unwrap() *Journey {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Journey is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Journey) String() string {
	var builder strings.Builder
	builder.WriteString("Journey(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("org_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OrgID))
	builder.WriteString(", ")
	builder.WriteString("product_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProductID))
	builder.WriteString(", ")
	if v := _m.FeatureID; v != nil {
		builder.WriteString("feature_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("entry_conditions=")
	builder.WriteString(fmt.Sprintf("%v", _m.EntryConditions))
	builder.WriteString(", ")
	builder.WriteString("exit_conditions=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExitConditions))
	builder.WriteString(", ")
	builder.WriteString("steps=")
	builder.WriteString(fmt.Sprintf("%v", _m.Steps))
	builder.WriteString(", ")
	builder.WriteString("timeout_minutes=")
	builder.WriteString(fmt.Sprintf("%v", _m.TimeoutMinutes))
	builder.WriteString(", ")
	builder.WriteString("total_sessions=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalSessions))
	builder.WriteString(", ")
	builder.WriteString("converted_sessions=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConvertedSessions))
	builder.WriteString(", ")
	builder.WriteString("conversion_rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConversionRate))
	builder.WriteString(", ")
	builder.WriteString("avg_duration_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.AvgDurationMs))
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Journeys is a parsable slice of Journey.
type Journeys []*Journey
