// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/plexusone/productgraph/ent/event"
	"github.com/plexusone/productgraph/ent/journey"
	"github.com/plexusone/productgraph/ent/project"
	"github.com/plexusone/productgraph/ent/session"
)

// JourneyCreate is the builder for creating a Journey entity.
type JourneyCreate struct {
	config
	mutation *JourneyMutation
	hooks    []Hook
}

// SetOrgID sets the "org_id" field.
func (_c *JourneyCreate) SetOrgID(v uuid.UUID) *JourneyCreate {
	_c.mutation.SetOrgID(v)
	return _c
}

// SetProjectID sets the "project_id" field.
func (_c *JourneyCreate) SetProjectID(v uuid.UUID) *JourneyCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *JourneyCreate) SetName(v string) *JourneyCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *JourneyCreate) SetDescription(v string) *JourneyCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *JourneyCreate) SetNillableDescription(v *string) *JourneyCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetEntryConditions sets the "entry_conditions" field.
func (_c *JourneyCreate) SetEntryConditions(v []interface{}) *JourneyCreate {
	_c.mutation.SetEntryConditions(v)
	return _c
}

// SetExitConditions sets the "exit_conditions" field.
func (_c *JourneyCreate) SetExitConditions(v []interface{}) *JourneyCreate {
	_c.mutation.SetExitConditions(v)
	return _c
}

// SetSteps sets the "steps" field.
func (_c *JourneyCreate) SetSteps(v []interface{}) *JourneyCreate {
	_c.mutation.SetSteps(v)
	return _c
}

// SetTimeoutMinutes sets the "timeout_minutes" field.
func (_c *JourneyCreate) SetTimeoutMinutes(v int) *JourneyCreate {
	_c.mutation.SetTimeoutMinutes(v)
	return _c
}

// SetNillableTimeoutMinutes sets the "timeout_minutes" field if the given value is not nil.
func (_c *JourneyCreate) SetNillableTimeoutMinutes(v *int) *JourneyCreate {
	if v != nil {
		_c.SetTimeoutMinutes(*v)
	}
	return _c
}

// SetTotalSessions sets the "total_sessions" field.
func (_c *JourneyCreate) SetTotalSessions(v int64) *JourneyCreate {
	_c.mutation.SetTotalSessions(v)
	return _c
}

// SetNillableTotalSessions sets the "total_sessions" field if the given value is not nil.
func (_c *JourneyCreate) SetNillableTotalSessions(v *int64) *JourneyCreate {
	if v != nil {
		_c.SetTotalSessions(*v)
	}
	return _c
}

// SetConvertedSessions sets the "converted_sessions" field.
func (_c *JourneyCreate) SetConvertedSessions(v int64) *JourneyCreate {
	_c.mutation.SetConvertedSessions(v)
	return _c
}

// SetNillableConvertedSessions sets the "converted_sessions" field if the given value is not nil.
func (_c *JourneyCreate) SetNillableConvertedSessions(v *int64) *JourneyCreate {
	if v != nil {
		_c.SetConvertedSessions(*v)
	}
	return _c
}

// SetConversionRate sets the "conversion_rate" field.
func (_c *JourneyCreate) SetConversionRate(v float64) *JourneyCreate {
	_c.mutation.SetConversionRate(v)
	return _c
}

// SetNillableConversionRate sets the "conversion_rate" field if the given value is not nil.
func (_c *JourneyCreate) SetNillableConversionRate(v *float64) *JourneyCreate {
	if v != nil {
		_c.SetConversionRate(*v)
	}
	return _c
}

// SetAvgDurationMs sets the "avg_duration_ms" field.
func (_c *JourneyCreate) SetAvgDurationMs(v int64) *JourneyCreate {
	_c.mutation.SetAvgDurationMs(v)
	return _c
}

// SetNillableAvgDurationMs sets the "avg_duration_ms" field if the given value is not nil.
func (_c *JourneyCreate) SetNillableAvgDurationMs(v *int64) *JourneyCreate {
	if v != nil {
		_c.SetAvgDurationMs(*v)
	}
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *JourneyCreate) SetIsActive(v bool) *JourneyCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *JourneyCreate) SetNillableIsActive(v *bool) *JourneyCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *JourneyCreate) SetCreatedAt(v time.Time) *JourneyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *JourneyCreate) SetNillableCreatedAt(v *time.Time) *JourneyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *JourneyCreate) SetUpdatedAt(v time.Time) *JourneyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *JourneyCreate) SetNillableUpdatedAt(v *time.Time) *JourneyCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *JourneyCreate) SetID(v uuid.UUID) *JourneyCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *JourneyCreate) SetNillableID(v *uuid.UUID) *JourneyCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetProject sets the "project" edge to the Project entity.
func (_c *JourneyCreate) SetProject(v *Project) *JourneyCreate {
	return _c.SetProjectID(v.ID)
}

// AddEventIDs adds the "events" edge to the Event entity by IDs.
func (_c *JourneyCreate) AddEventIDs(ids ...uuid.UUID) *JourneyCreate {
	_c.mutation.AddEventIDs(ids...)
	return _c
}

// AddEvents adds the "events" edges to the Event entity.
func (_c *JourneyCreate) AddEvents(v ...*Event) *JourneyCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddEventIDs(ids...)
}

// AddSessionIDs adds the "sessions" edge to the Session entity by IDs.
func (_c *JourneyCreate) AddSessionIDs(ids ...uuid.UUID) *JourneyCreate {
	_c.mutation.AddSessionIDs(ids...)
	return _c
}

// AddSessions adds the "sessions" edges to the Session entity.
func (_c *JourneyCreate) AddSessions(v ...*Session) *JourneyCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSessionIDs(ids...)
}

// Mutation returns the JourneyMutation object of the builder.
func (_c *JourneyCreate) Mutation() *JourneyMutation {
	return _c.mutation
}

// Save creates the Journey in the database.
func (_c *JourneyCreate) Save(ctx context.Context) (*Journey, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *JourneyCreate) SaveX(ctx context.Context) *Journey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *JourneyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *JourneyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *JourneyCreate) defaults() {
	if _, ok := _c.mutation.TimeoutMinutes(); !ok {
		v := journey.DefaultTimeoutMinutes
		_c.mutation.SetTimeoutMinutes(v)
	}
	if _, ok := _c.mutation.TotalSessions(); !ok {
		v := journey.DefaultTotalSessions
		_c.mutation.SetTotalSessions(v)
	}
	if _, ok := _c.mutation.ConvertedSessions(); !ok {
		v := journey.DefaultConvertedSessions
		_c.mutation.SetConvertedSessions(v)
	}
	if _, ok := _c.mutation.ConversionRate(); !ok {
		v := journey.DefaultConversionRate
		_c.mutation.SetConversionRate(v)
	}
	if _, ok := _c.mutation.AvgDurationMs(); !ok {
		v := journey.DefaultAvgDurationMs
		_c.mutation.SetAvgDurationMs(v)
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		v := journey.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := journey.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := journey.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := journey.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *JourneyCreate) check() error {
	if _, ok := _c.mutation.OrgID(); !ok {
		return &ValidationError{Name: "org_id", err: errors.New(`ent: missing required field "Journey.org_id"`)}
	}
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "Journey.project_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Journey.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := journey.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Journey.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TimeoutMinutes(); !ok {
		return &ValidationError{Name: "timeout_minutes", err: errors.New(`ent: missing required field "Journey.timeout_minutes"`)}
	}
	if _, ok := _c.mutation.TotalSessions(); !ok {
		return &ValidationError{Name: "total_sessions", err: errors.New(`ent: missing required field "Journey.total_sessions"`)}
	}
	if _, ok := _c.mutation.ConvertedSessions(); !ok {
		return &ValidationError{Name: "converted_sessions", err: errors.New(`ent: missing required field "Journey.converted_sessions"`)}
	}
	if _, ok := _c.mutation.ConversionRate(); !ok {
		return &ValidationError{Name: "conversion_rate", err: errors.New(`ent: missing required field "Journey.conversion_rate"`)}
	}
	if _, ok := _c.mutation.AvgDurationMs(); !ok {
		return &ValidationError{Name: "avg_duration_ms", err: errors.New(`ent: missing required field "Journey.avg_duration_ms"`)}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "Journey.is_active"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Journey.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Journey.updated_at"`)}
	}
	if len(_c.mutation.ProjectIDs()) == 0 {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required edge "Journey.project"`)}
	}
	return nil
}

func (_c *JourneyCreate) sqlSave(ctx context.Context) (*Journey, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *JourneyCreate) createSpec() (*Journey, *sqlgraph.CreateSpec) {
	var (
		_node = &Journey{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(journey.Table, sqlgraph.NewFieldSpec(journey.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.OrgID(); ok {
		_spec.SetField(journey.FieldOrgID, field.TypeUUID, value)
		_node.OrgID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(journey.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(journey.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.EntryConditions(); ok {
		_spec.SetField(journey.FieldEntryConditions, field.TypeJSON, value)
		_node.EntryConditions = value
	}
	if value, ok := _c.mutation.ExitConditions(); ok {
		_spec.SetField(journey.FieldExitConditions, field.TypeJSON, value)
		_node.ExitConditions = value
	}
	if value, ok := _c.mutation.Steps(); ok {
		_spec.SetField(journey.FieldSteps, field.TypeJSON, value)
		_node.Steps = value
	}
	if value, ok := _c.mutation.TimeoutMinutes(); ok {
		_spec.SetField(journey.FieldTimeoutMinutes, field.TypeInt, value)
		_node.TimeoutMinutes = value
	}
	if value, ok := _c.mutation.TotalSessions(); ok {
		_spec.SetField(journey.FieldTotalSessions, field.TypeInt64, value)
		_node.TotalSessions = value
	}
	if value, ok := _c.mutation.ConvertedSessions(); ok {
		_spec.SetField(journey.FieldConvertedSessions, field.TypeInt64, value)
		_node.ConvertedSessions = value
	}
	if value, ok := _c.mutation.ConversionRate(); ok {
		_spec.SetField(journey.FieldConversionRate, field.TypeFloat64, value)
		_node.ConversionRate = value
	}
	if value, ok := _c.mutation.AvgDurationMs(); ok {
		_spec.SetField(journey.FieldAvgDurationMs, field.TypeInt64, value)
		_node.AvgDurationMs = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(journey.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(journey.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(journey.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   journey.ProjectTable,
			Columns: []string{journey.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProjectID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   journey.EventsTable,
			Columns: []string{journey.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   journey.SessionsTable,
			Columns: []string{journey.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// JourneyCreateBulk is the builder for creating many Journey entities in bulk.
type JourneyCreateBulk struct {
	config
	err      error
	builders []*JourneyCreate
}

// Save creates the Journey entities in the database.
func (_c *JourneyCreateBulk) Save(ctx context.Context) ([]*Journey, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Journey, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*JourneyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *JourneyCreateBulk) SaveX(ctx context.Context) []*Journey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *JourneyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *JourneyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
