// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/plexusone/productgraph/ent/capability"
	"github.com/plexusone/productgraph/ent/event"
	"github.com/plexusone/productgraph/ent/feature"
	"github.com/plexusone/productgraph/ent/journey"
	"github.com/plexusone/productgraph/ent/organization"
	"github.com/plexusone/productgraph/ent/product"
	"github.com/plexusone/productgraph/ent/schema"
	"github.com/plexusone/productgraph/ent/session"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	capabilityFields := schema.Capability{}.Fields()
	_ = capabilityFields
	// capabilityDescName is the schema descriptor for name field.
	capabilityDescName := capabilityFields[3].Descriptor()
	// capability.NameValidator is a validator for the "name" field. It is called by the builders before save.
	capability.NameValidator = func() func(string) error {
		validators := capabilityDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// capabilityDescDisplayOrder is the schema descriptor for display_order field.
	capabilityDescDisplayOrder := capabilityFields[5].Descriptor()
	// capability.DefaultDisplayOrder holds the default value on creation for the display_order field.
	capability.DefaultDisplayOrder = capabilityDescDisplayOrder.Default.(int)
	// capabilityDescCreatedAt is the schema descriptor for created_at field.
	capabilityDescCreatedAt := capabilityFields[6].Descriptor()
	// capability.DefaultCreatedAt holds the default value on creation for the created_at field.
	capability.DefaultCreatedAt = capabilityDescCreatedAt.Default.(func() time.Time)
	// capabilityDescUpdatedAt is the schema descriptor for updated_at field.
	capabilityDescUpdatedAt := capabilityFields[7].Descriptor()
	// capability.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	capability.DefaultUpdatedAt = capabilityDescUpdatedAt.Default.(func() time.Time)
	// capability.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	capability.UpdateDefaultUpdatedAt = capabilityDescUpdatedAt.UpdateDefault.(func() time.Time)
	// capabilityDescID is the schema descriptor for id field.
	capabilityDescID := capabilityFields[0].Descriptor()
	// capability.DefaultID holds the default value on creation for the id field.
	capability.DefaultID = capabilityDescID.Default.(func() uuid.UUID)
	eventFields := schema.Event{}.Fields()
	_ = eventFields
	// eventDescEventID is the schema descriptor for event_id field.
	eventDescEventID := eventFields[3].Descriptor()
	// event.EventIDValidator is a validator for the "event_id" field. It is called by the builders before save.
	event.EventIDValidator = func() func(string) error {
		validators := eventDescEventID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(event_id string) error {
			for _, fn := range fns {
				if err := fn(event_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// eventDescSessionID is the schema descriptor for session_id field.
	eventDescSessionID := eventFields[4].Descriptor()
	// event.SessionIDValidator is a validator for the "session_id" field. It is called by the builders before save.
	event.SessionIDValidator = func() func(string) error {
		validators := eventDescSessionID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(session_id string) error {
			for _, fn := range fns {
				if err := fn(session_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// eventDescUserID is the schema descriptor for user_id field.
	eventDescUserID := eventFields[5].Descriptor()
	// event.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	event.UserIDValidator = eventDescUserID.Validators[0].(func(string) error)
	// eventDescEventName is the schema descriptor for event_name field.
	eventDescEventName := eventFields[7].Descriptor()
	// event.EventNameValidator is a validator for the "event_name" field. It is called by the builders before save.
	event.EventNameValidator = eventDescEventName.Validators[0].(func(string) error)
	// eventDescSequence is the schema descriptor for sequence field.
	eventDescSequence := eventFields[9].Descriptor()
	// event.DefaultSequence holds the default value on creation for the sequence field.
	event.DefaultSequence = eventDescSequence.Default.(int64)
	// eventDescPagePath is the schema descriptor for page_path field.
	eventDescPagePath := eventFields[10].Descriptor()
	// event.PagePathValidator is a validator for the "page_path" field. It is called by the builders before save.
	event.PagePathValidator = eventDescPagePath.Validators[0].(func(string) error)
	// eventDescPageTitle is the schema descriptor for page_title field.
	eventDescPageTitle := eventFields[11].Descriptor()
	// event.PageTitleValidator is a validator for the "page_title" field. It is called by the builders before save.
	event.PageTitleValidator = eventDescPageTitle.Validators[0].(func(string) error)
	// eventDescPageURL is the schema descriptor for page_url field.
	eventDescPageURL := eventFields[12].Descriptor()
	// event.PageURLValidator is a validator for the "page_url" field. It is called by the builders before save.
	event.PageURLValidator = eventDescPageURL.Validators[0].(func(string) error)
	// eventDescPageReferrer is the schema descriptor for page_referrer field.
	eventDescPageReferrer := eventFields[13].Descriptor()
	// event.PageReferrerValidator is a validator for the "page_referrer" field. It is called by the builders before save.
	event.PageReferrerValidator = eventDescPageReferrer.Validators[0].(func(string) error)
	// eventDescUIComponentName is the schema descriptor for ui_component_name field.
	eventDescUIComponentName := eventFields[14].Descriptor()
	// event.UIComponentNameValidator is a validator for the "ui_component_name" field. It is called by the builders before save.
	event.UIComponentNameValidator = eventDescUIComponentName.Validators[0].(func(string) error)
	// eventDescUIComponentPath is the schema descriptor for ui_component_path field.
	eventDescUIComponentPath := eventFields[15].Descriptor()
	// event.UIComponentPathValidator is a validator for the "ui_component_path" field. It is called by the builders before save.
	event.UIComponentPathValidator = eventDescUIComponentPath.Validators[0].(func(string) error)
	// eventDescUIComponentType is the schema descriptor for ui_component_type field.
	eventDescUIComponentType := eventFields[16].Descriptor()
	// event.UIComponentTypeValidator is a validator for the "ui_component_type" field. It is called by the builders before save.
	event.UIComponentTypeValidator = eventDescUIComponentType.Validators[0].(func(string) error)
	// eventDescUIAction is the schema descriptor for ui_action field.
	eventDescUIAction := eventFields[17].Descriptor()
	// event.UIActionValidator is a validator for the "ui_action" field. It is called by the builders before save.
	event.UIActionValidator = eventDescUIAction.Validators[0].(func(string) error)
	// eventDescUIElement is the schema descriptor for ui_element field.
	eventDescUIElement := eventFields[18].Descriptor()
	// event.UIElementValidator is a validator for the "ui_element" field. It is called by the builders before save.
	event.UIElementValidator = eventDescUIElement.Validators[0].(func(string) error)
	// eventDescUIElementText is the schema descriptor for ui_element_text field.
	eventDescUIElementText := eventFields[19].Descriptor()
	// event.UIElementTextValidator is a validator for the "ui_element_text" field. It is called by the builders before save.
	event.UIElementTextValidator = eventDescUIElementText.Validators[0].(func(string) error)
	// eventDescUIViewport is the schema descriptor for ui_viewport field.
	eventDescUIViewport := eventFields[20].Descriptor()
	// event.UIViewportValidator is a validator for the "ui_viewport" field. It is called by the builders before save.
	event.UIViewportValidator = eventDescUIViewport.Validators[0].(func(string) error)
	// eventDescUIStateKey is the schema descriptor for ui_state_key field.
	eventDescUIStateKey := eventFields[22].Descriptor()
	// event.UIStateKeyValidator is a validator for the "ui_state_key" field. It is called by the builders before save.
	event.UIStateKeyValidator = eventDescUIStateKey.Validators[0].(func(string) error)
	// eventDescUIStateChangeType is the schema descriptor for ui_state_change_type field.
	eventDescUIStateChangeType := eventFields[25].Descriptor()
	// event.UIStateChangeTypeValidator is a validator for the "ui_state_change_type" field. It is called by the builders before save.
	event.UIStateChangeTypeValidator = eventDescUIStateChangeType.Validators[0].(func(string) error)
	// eventDescJourneyStepID is the schema descriptor for journey_step_id field.
	eventDescJourneyStepID := eventFields[27].Descriptor()
	// event.JourneyStepIDValidator is a validator for the "journey_step_id" field. It is called by the builders before save.
	event.JourneyStepIDValidator = eventDescJourneyStepID.Validators[0].(func(string) error)
	// eventDescJourneyStepName is the schema descriptor for journey_step_name field.
	eventDescJourneyStepName := eventFields[28].Descriptor()
	// event.JourneyStepNameValidator is a validator for the "journey_step_name" field. It is called by the builders before save.
	event.JourneyStepNameValidator = eventDescJourneyStepName.Validators[0].(func(string) error)
	// eventDescConversionStatus is the schema descriptor for conversion_status field.
	eventDescConversionStatus := eventFields[29].Descriptor()
	// event.ConversionStatusValidator is a validator for the "conversion_status" field. It is called by the builders before save.
	event.ConversionStatusValidator = eventDescConversionStatus.Validators[0].(func(string) error)
	// eventDescAPIMethod is the schema descriptor for api_method field.
	eventDescAPIMethod := eventFields[30].Descriptor()
	// event.APIMethodValidator is a validator for the "api_method" field. It is called by the builders before save.
	event.APIMethodValidator = eventDescAPIMethod.Validators[0].(func(string) error)
	// eventDescAPIPath is the schema descriptor for api_path field.
	eventDescAPIPath := eventFields[31].Descriptor()
	// event.APIPathValidator is a validator for the "api_path" field. It is called by the builders before save.
	event.APIPathValidator = eventDescAPIPath.Validators[0].(func(string) error)
	// eventDescErrorType is the schema descriptor for error_type field.
	eventDescErrorType := eventFields[34].Descriptor()
	// event.ErrorTypeValidator is a validator for the "error_type" field. It is called by the builders before save.
	event.ErrorTypeValidator = eventDescErrorType.Validators[0].(func(string) error)
	// eventDescErrorComponent is the schema descriptor for error_component field.
	eventDescErrorComponent := eventFields[37].Descriptor()
	// event.ErrorComponentValidator is a validator for the "error_component" field. It is called by the builders before save.
	event.ErrorComponentValidator = eventDescErrorComponent.Validators[0].(func(string) error)
	// eventDescSnapshotURL is the schema descriptor for snapshot_url field.
	eventDescSnapshotURL := eventFields[42].Descriptor()
	// event.SnapshotURLValidator is a validator for the "snapshot_url" field. It is called by the builders before save.
	event.SnapshotURLValidator = eventDescSnapshotURL.Validators[0].(func(string) error)
	// eventDescSnapshotViewport is the schema descriptor for snapshot_viewport field.
	eventDescSnapshotViewport := eventFields[43].Descriptor()
	// event.SnapshotViewportValidator is a validator for the "snapshot_viewport" field. It is called by the builders before save.
	event.SnapshotViewportValidator = eventDescSnapshotViewport.Validators[0].(func(string) error)
	// eventDescCreatedAt is the schema descriptor for created_at field.
	eventDescCreatedAt := eventFields[46].Descriptor()
	// event.DefaultCreatedAt holds the default value on creation for the created_at field.
	event.DefaultCreatedAt = eventDescCreatedAt.Default.(func() time.Time)
	// eventDescID is the schema descriptor for id field.
	eventDescID := eventFields[0].Descriptor()
	// event.DefaultID holds the default value on creation for the id field.
	event.DefaultID = eventDescID.Default.(func() uuid.UUID)
	featureFields := schema.Feature{}.Fields()
	_ = featureFields
	// featureDescName is the schema descriptor for name field.
	featureDescName := featureFields[4].Descriptor()
	// feature.NameValidator is a validator for the "name" field. It is called by the builders before save.
	feature.NameValidator = func() func(string) error {
		validators := featureDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// featureDescAdminPath is the schema descriptor for admin_path field.
	featureDescAdminPath := featureFields[6].Descriptor()
	// feature.AdminPathValidator is a validator for the "admin_path" field. It is called by the builders before save.
	feature.AdminPathValidator = featureDescAdminPath.Validators[0].(func(string) error)
	// featureDescDisplayOrder is the schema descriptor for display_order field.
	featureDescDisplayOrder := featureFields[9].Descriptor()
	// feature.DefaultDisplayOrder holds the default value on creation for the display_order field.
	feature.DefaultDisplayOrder = featureDescDisplayOrder.Default.(int)
	// featureDescCreatedAt is the schema descriptor for created_at field.
	featureDescCreatedAt := featureFields[10].Descriptor()
	// feature.DefaultCreatedAt holds the default value on creation for the created_at field.
	feature.DefaultCreatedAt = featureDescCreatedAt.Default.(func() time.Time)
	// featureDescUpdatedAt is the schema descriptor for updated_at field.
	featureDescUpdatedAt := featureFields[11].Descriptor()
	// feature.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	feature.DefaultUpdatedAt = featureDescUpdatedAt.Default.(func() time.Time)
	// feature.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	feature.UpdateDefaultUpdatedAt = featureDescUpdatedAt.UpdateDefault.(func() time.Time)
	// featureDescID is the schema descriptor for id field.
	featureDescID := featureFields[0].Descriptor()
	// feature.DefaultID holds the default value on creation for the id field.
	feature.DefaultID = featureDescID.Default.(func() uuid.UUID)
	journeyFields := schema.Journey{}.Fields()
	_ = journeyFields
	// journeyDescName is the schema descriptor for name field.
	journeyDescName := journeyFields[4].Descriptor()
	// journey.NameValidator is a validator for the "name" field. It is called by the builders before save.
	journey.NameValidator = func() func(string) error {
		validators := journeyDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// journeyDescTimeoutMinutes is the schema descriptor for timeout_minutes field.
	journeyDescTimeoutMinutes := journeyFields[9].Descriptor()
	// journey.DefaultTimeoutMinutes holds the default value on creation for the timeout_minutes field.
	journey.DefaultTimeoutMinutes = journeyDescTimeoutMinutes.Default.(int)
	// journeyDescTotalSessions is the schema descriptor for total_sessions field.
	journeyDescTotalSessions := journeyFields[10].Descriptor()
	// journey.DefaultTotalSessions holds the default value on creation for the total_sessions field.
	journey.DefaultTotalSessions = journeyDescTotalSessions.Default.(int64)
	// journeyDescConvertedSessions is the schema descriptor for converted_sessions field.
	journeyDescConvertedSessions := journeyFields[11].Descriptor()
	// journey.DefaultConvertedSessions holds the default value on creation for the converted_sessions field.
	journey.DefaultConvertedSessions = journeyDescConvertedSessions.Default.(int64)
	// journeyDescConversionRate is the schema descriptor for conversion_rate field.
	journeyDescConversionRate := journeyFields[12].Descriptor()
	// journey.DefaultConversionRate holds the default value on creation for the conversion_rate field.
	journey.DefaultConversionRate = journeyDescConversionRate.Default.(float64)
	// journeyDescAvgDurationMs is the schema descriptor for avg_duration_ms field.
	journeyDescAvgDurationMs := journeyFields[13].Descriptor()
	// journey.DefaultAvgDurationMs holds the default value on creation for the avg_duration_ms field.
	journey.DefaultAvgDurationMs = journeyDescAvgDurationMs.Default.(int64)
	// journeyDescIsActive is the schema descriptor for is_active field.
	journeyDescIsActive := journeyFields[14].Descriptor()
	// journey.DefaultIsActive holds the default value on creation for the is_active field.
	journey.DefaultIsActive = journeyDescIsActive.Default.(bool)
	// journeyDescCreatedAt is the schema descriptor for created_at field.
	journeyDescCreatedAt := journeyFields[15].Descriptor()
	// journey.DefaultCreatedAt holds the default value on creation for the created_at field.
	journey.DefaultCreatedAt = journeyDescCreatedAt.Default.(func() time.Time)
	// journeyDescUpdatedAt is the schema descriptor for updated_at field.
	journeyDescUpdatedAt := journeyFields[16].Descriptor()
	// journey.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	journey.DefaultUpdatedAt = journeyDescUpdatedAt.Default.(func() time.Time)
	// journey.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	journey.UpdateDefaultUpdatedAt = journeyDescUpdatedAt.UpdateDefault.(func() time.Time)
	// journeyDescID is the schema descriptor for id field.
	journeyDescID := journeyFields[0].Descriptor()
	// journey.DefaultID holds the default value on creation for the id field.
	journey.DefaultID = journeyDescID.Default.(func() uuid.UUID)
	organizationFields := schema.Organization{}.Fields()
	_ = organizationFields
	// organizationDescName is the schema descriptor for name field.
	organizationDescName := organizationFields[1].Descriptor()
	// organization.NameValidator is a validator for the "name" field. It is called by the builders before save.
	organization.NameValidator = func() func(string) error {
		validators := organizationDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// organizationDescSlug is the schema descriptor for slug field.
	organizationDescSlug := organizationFields[2].Descriptor()
	// organization.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	organization.SlugValidator = func() func(string) error {
		validators := organizationDescSlug.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(slug string) error {
			for _, fn := range fns {
				if err := fn(slug); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// organizationDescCreatedAt is the schema descriptor for created_at field.
	organizationDescCreatedAt := organizationFields[3].Descriptor()
	// organization.DefaultCreatedAt holds the default value on creation for the created_at field.
	organization.DefaultCreatedAt = organizationDescCreatedAt.Default.(func() time.Time)
	// organizationDescUpdatedAt is the schema descriptor for updated_at field.
	organizationDescUpdatedAt := organizationFields[4].Descriptor()
	// organization.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	organization.DefaultUpdatedAt = organizationDescUpdatedAt.Default.(func() time.Time)
	// organization.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	organization.UpdateDefaultUpdatedAt = organizationDescUpdatedAt.UpdateDefault.(func() time.Time)
	// organizationDescID is the schema descriptor for id field.
	organizationDescID := organizationFields[0].Descriptor()
	// organization.DefaultID holds the default value on creation for the id field.
	organization.DefaultID = organizationDescID.Default.(func() uuid.UUID)
	productFields := schema.Product{}.Fields()
	_ = productFields
	// productDescName is the schema descriptor for name field.
	productDescName := productFields[2].Descriptor()
	// product.NameValidator is a validator for the "name" field. It is called by the builders before save.
	product.NameValidator = func() func(string) error {
		validators := productDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// productDescSlug is the schema descriptor for slug field.
	productDescSlug := productFields[3].Descriptor()
	// product.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	product.SlugValidator = func() func(string) error {
		validators := productDescSlug.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(slug string) error {
			for _, fn := range fns {
				if err := fn(slug); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// productDescAPIKey is the schema descriptor for api_key field.
	productDescAPIKey := productFields[4].Descriptor()
	// product.APIKeyValidator is a validator for the "api_key" field. It is called by the builders before save.
	product.APIKeyValidator = func() func(string) error {
		validators := productDescAPIKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(api_key string) error {
			for _, fn := range fns {
				if err := fn(api_key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// productDescCreatedAt is the schema descriptor for created_at field.
	productDescCreatedAt := productFields[6].Descriptor()
	// product.DefaultCreatedAt holds the default value on creation for the created_at field.
	product.DefaultCreatedAt = productDescCreatedAt.Default.(func() time.Time)
	// productDescUpdatedAt is the schema descriptor for updated_at field.
	productDescUpdatedAt := productFields[7].Descriptor()
	// product.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	product.DefaultUpdatedAt = productDescUpdatedAt.Default.(func() time.Time)
	// product.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	product.UpdateDefaultUpdatedAt = productDescUpdatedAt.UpdateDefault.(func() time.Time)
	// productDescID is the schema descriptor for id field.
	productDescID := productFields[0].Descriptor()
	// product.DefaultID holds the default value on creation for the id field.
	product.DefaultID = productDescID.Default.(func() uuid.UUID)
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescSessionID is the schema descriptor for session_id field.
	sessionDescSessionID := sessionFields[3].Descriptor()
	// session.SessionIDValidator is a validator for the "session_id" field. It is called by the builders before save.
	session.SessionIDValidator = func() func(string) error {
		validators := sessionDescSessionID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(session_id string) error {
			for _, fn := range fns {
				if err := fn(session_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sessionDescUserID is the schema descriptor for user_id field.
	sessionDescUserID := sessionFields[4].Descriptor()
	// session.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	session.UserIDValidator = sessionDescUserID.Validators[0].(func(string) error)
	// sessionDescDurationMs is the schema descriptor for duration_ms field.
	sessionDescDurationMs := sessionFields[7].Descriptor()
	// session.DefaultDurationMs holds the default value on creation for the duration_ms field.
	session.DefaultDurationMs = sessionDescDurationMs.Default.(int64)
	// sessionDescEntryPage is the schema descriptor for entry_page field.
	sessionDescEntryPage := sessionFields[8].Descriptor()
	// session.EntryPageValidator is a validator for the "entry_page" field. It is called by the builders before save.
	session.EntryPageValidator = sessionDescEntryPage.Validators[0].(func(string) error)
	// sessionDescExitPage is the schema descriptor for exit_page field.
	sessionDescExitPage := sessionFields[9].Descriptor()
	// session.ExitPageValidator is a validator for the "exit_page" field. It is called by the builders before save.
	session.ExitPageValidator = sessionDescExitPage.Validators[0].(func(string) error)
	// sessionDescPageCount is the schema descriptor for page_count field.
	sessionDescPageCount := sessionFields[10].Descriptor()
	// session.DefaultPageCount holds the default value on creation for the page_count field.
	session.DefaultPageCount = sessionDescPageCount.Default.(int)
	// sessionDescEventCount is the schema descriptor for event_count field.
	sessionDescEventCount := sessionFields[11].Descriptor()
	// session.DefaultEventCount holds the default value on creation for the event_count field.
	session.DefaultEventCount = sessionDescEventCount.Default.(int)
	// sessionDescLastJourneyStepID is the schema descriptor for last_journey_step_id field.
	sessionDescLastJourneyStepID := sessionFields[13].Descriptor()
	// session.LastJourneyStepIDValidator is a validator for the "last_journey_step_id" field. It is called by the builders before save.
	session.LastJourneyStepIDValidator = sessionDescLastJourneyStepID.Validators[0].(func(string) error)
	// sessionDescConversionStatus is the schema descriptor for conversion_status field.
	sessionDescConversionStatus := sessionFields[14].Descriptor()
	// session.ConversionStatusValidator is a validator for the "conversion_status" field. It is called by the builders before save.
	session.ConversionStatusValidator = sessionDescConversionStatus.Validators[0].(func(string) error)
	// sessionDescUserAgent is the schema descriptor for user_agent field.
	sessionDescUserAgent := sessionFields[15].Descriptor()
	// session.UserAgentValidator is a validator for the "user_agent" field. It is called by the builders before save.
	session.UserAgentValidator = sessionDescUserAgent.Validators[0].(func(string) error)
	// sessionDescDeviceType is the schema descriptor for device_type field.
	sessionDescDeviceType := sessionFields[16].Descriptor()
	// session.DeviceTypeValidator is a validator for the "device_type" field. It is called by the builders before save.
	session.DeviceTypeValidator = sessionDescDeviceType.Validators[0].(func(string) error)
	// sessionDescBrowser is the schema descriptor for browser field.
	sessionDescBrowser := sessionFields[17].Descriptor()
	// session.BrowserValidator is a validator for the "browser" field. It is called by the builders before save.
	session.BrowserValidator = sessionDescBrowser.Validators[0].(func(string) error)
	// sessionDescOs is the schema descriptor for os field.
	sessionDescOs := sessionFields[18].Descriptor()
	// session.OsValidator is a validator for the "os" field. It is called by the builders before save.
	session.OsValidator = sessionDescOs.Validators[0].(func(string) error)
	// sessionDescCountry is the schema descriptor for country field.
	sessionDescCountry := sessionFields[19].Descriptor()
	// session.CountryValidator is a validator for the "country" field. It is called by the builders before save.
	session.CountryValidator = sessionDescCountry.Validators[0].(func(string) error)
	// sessionDescRegion is the schema descriptor for region field.
	sessionDescRegion := sessionFields[20].Descriptor()
	// session.RegionValidator is a validator for the "region" field. It is called by the builders before save.
	session.RegionValidator = sessionDescRegion.Validators[0].(func(string) error)
	// sessionDescCity is the schema descriptor for city field.
	sessionDescCity := sessionFields[21].Descriptor()
	// session.CityValidator is a validator for the "city" field. It is called by the builders before save.
	session.CityValidator = sessionDescCity.Validators[0].(func(string) error)
	// sessionDescCreatedAt is the schema descriptor for created_at field.
	sessionDescCreatedAt := sessionFields[22].Descriptor()
	// session.DefaultCreatedAt holds the default value on creation for the created_at field.
	session.DefaultCreatedAt = sessionDescCreatedAt.Default.(func() time.Time)
	// sessionDescUpdatedAt is the schema descriptor for updated_at field.
	sessionDescUpdatedAt := sessionFields[23].Descriptor()
	// session.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	session.DefaultUpdatedAt = sessionDescUpdatedAt.Default.(func() time.Time)
	// session.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	session.UpdateDefaultUpdatedAt = sessionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// sessionDescID is the schema descriptor for id field.
	sessionDescID := sessionFields[0].Descriptor()
	// session.DefaultID holds the default value on creation for the id field.
	session.DefaultID = sessionDescID.Default.(func() uuid.UUID)
}
