// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/plexusone/productgraph/ent/journey"
	"github.com/plexusone/productgraph/ent/project"
	"github.com/plexusone/productgraph/ent/session"
)

// SessionCreate is the builder for creating a Session entity.
type SessionCreate struct {
	config
	mutation *SessionMutation
	hooks    []Hook
}

// SetOrgID sets the "org_id" field.
func (_c *SessionCreate) SetOrgID(v uuid.UUID) *SessionCreate {
	_c.mutation.SetOrgID(v)
	return _c
}

// SetProjectID sets the "project_id" field.
func (_c *SessionCreate) SetProjectID(v uuid.UUID) *SessionCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetSessionID sets the "session_id" field.
func (_c *SessionCreate) SetSessionID(v string) *SessionCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *SessionCreate) SetUserID(v string) *SessionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *SessionCreate) SetNillableUserID(v *string) *SessionCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *SessionCreate) SetStartedAt(v time.Time) *SessionCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetEndedAt sets the "ended_at" field.
func (_c *SessionCreate) SetEndedAt(v time.Time) *SessionCreate {
	_c.mutation.SetEndedAt(v)
	return _c
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_c *SessionCreate) SetNillableEndedAt(v *time.Time) *SessionCreate {
	if v != nil {
		_c.SetEndedAt(*v)
	}
	return _c
}

// SetDurationMs sets the "duration_ms" field.
func (_c *SessionCreate) SetDurationMs(v int64) *SessionCreate {
	_c.mutation.SetDurationMs(v)
	return _c
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_c *SessionCreate) SetNillableDurationMs(v *int64) *SessionCreate {
	if v != nil {
		_c.SetDurationMs(*v)
	}
	return _c
}

// SetEntryPage sets the "entry_page" field.
func (_c *SessionCreate) SetEntryPage(v string) *SessionCreate {
	_c.mutation.SetEntryPage(v)
	return _c
}

// SetNillableEntryPage sets the "entry_page" field if the given value is not nil.
func (_c *SessionCreate) SetNillableEntryPage(v *string) *SessionCreate {
	if v != nil {
		_c.SetEntryPage(*v)
	}
	return _c
}

// SetExitPage sets the "exit_page" field.
func (_c *SessionCreate) SetExitPage(v string) *SessionCreate {
	_c.mutation.SetExitPage(v)
	return _c
}

// SetNillableExitPage sets the "exit_page" field if the given value is not nil.
func (_c *SessionCreate) SetNillableExitPage(v *string) *SessionCreate {
	if v != nil {
		_c.SetExitPage(*v)
	}
	return _c
}

// SetPageCount sets the "page_count" field.
func (_c *SessionCreate) SetPageCount(v int) *SessionCreate {
	_c.mutation.SetPageCount(v)
	return _c
}

// SetNillablePageCount sets the "page_count" field if the given value is not nil.
func (_c *SessionCreate) SetNillablePageCount(v *int) *SessionCreate {
	if v != nil {
		_c.SetPageCount(*v)
	}
	return _c
}

// SetEventCount sets the "event_count" field.
func (_c *SessionCreate) SetEventCount(v int) *SessionCreate {
	_c.mutation.SetEventCount(v)
	return _c
}

// SetNillableEventCount sets the "event_count" field if the given value is not nil.
func (_c *SessionCreate) SetNillableEventCount(v *int) *SessionCreate {
	if v != nil {
		_c.SetEventCount(*v)
	}
	return _c
}

// SetJourneyID sets the "journey_id" field.
func (_c *SessionCreate) SetJourneyID(v uuid.UUID) *SessionCreate {
	_c.mutation.SetJourneyID(v)
	return _c
}

// SetNillableJourneyID sets the "journey_id" field if the given value is not nil.
func (_c *SessionCreate) SetNillableJourneyID(v *uuid.UUID) *SessionCreate {
	if v != nil {
		_c.SetJourneyID(*v)
	}
	return _c
}

// SetLastJourneyStepID sets the "last_journey_step_id" field.
func (_c *SessionCreate) SetLastJourneyStepID(v string) *SessionCreate {
	_c.mutation.SetLastJourneyStepID(v)
	return _c
}

// SetNillableLastJourneyStepID sets the "last_journey_step_id" field if the given value is not nil.
func (_c *SessionCreate) SetNillableLastJourneyStepID(v *string) *SessionCreate {
	if v != nil {
		_c.SetLastJourneyStepID(*v)
	}
	return _c
}

// SetConversionStatus sets the "conversion_status" field.
func (_c *SessionCreate) SetConversionStatus(v string) *SessionCreate {
	_c.mutation.SetConversionStatus(v)
	return _c
}

// SetNillableConversionStatus sets the "conversion_status" field if the given value is not nil.
func (_c *SessionCreate) SetNillableConversionStatus(v *string) *SessionCreate {
	if v != nil {
		_c.SetConversionStatus(*v)
	}
	return _c
}

// SetUserAgent sets the "user_agent" field.
func (_c *SessionCreate) SetUserAgent(v string) *SessionCreate {
	_c.mutation.SetUserAgent(v)
	return _c
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_c *SessionCreate) SetNillableUserAgent(v *string) *SessionCreate {
	if v != nil {
		_c.SetUserAgent(*v)
	}
	return _c
}

// SetDeviceType sets the "device_type" field.
func (_c *SessionCreate) SetDeviceType(v string) *SessionCreate {
	_c.mutation.SetDeviceType(v)
	return _c
}

// SetNillableDeviceType sets the "device_type" field if the given value is not nil.
func (_c *SessionCreate) SetNillableDeviceType(v *string) *SessionCreate {
	if v != nil {
		_c.SetDeviceType(*v)
	}
	return _c
}

// SetBrowser sets the "browser" field.
func (_c *SessionCreate) SetBrowser(v string) *SessionCreate {
	_c.mutation.SetBrowser(v)
	return _c
}

// SetNillableBrowser sets the "browser" field if the given value is not nil.
func (_c *SessionCreate) SetNillableBrowser(v *string) *SessionCreate {
	if v != nil {
		_c.SetBrowser(*v)
	}
	return _c
}

// SetOs sets the "os" field.
func (_c *SessionCreate) SetOs(v string) *SessionCreate {
	_c.mutation.SetOs(v)
	return _c
}

// SetNillableOs sets the "os" field if the given value is not nil.
func (_c *SessionCreate) SetNillableOs(v *string) *SessionCreate {
	if v != nil {
		_c.SetOs(*v)
	}
	return _c
}

// SetCountry sets the "country" field.
func (_c *SessionCreate) SetCountry(v string) *SessionCreate {
	_c.mutation.SetCountry(v)
	return _c
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_c *SessionCreate) SetNillableCountry(v *string) *SessionCreate {
	if v != nil {
		_c.SetCountry(*v)
	}
	return _c
}

// SetRegion sets the "region" field.
func (_c *SessionCreate) SetRegion(v string) *SessionCreate {
	_c.mutation.SetRegion(v)
	return _c
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_c *SessionCreate) SetNillableRegion(v *string) *SessionCreate {
	if v != nil {
		_c.SetRegion(*v)
	}
	return _c
}

// SetCity sets the "city" field.
func (_c *SessionCreate) SetCity(v string) *SessionCreate {
	_c.mutation.SetCity(v)
	return _c
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (_c *SessionCreate) SetNillableCity(v *string) *SessionCreate {
	if v != nil {
		_c.SetCity(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SessionCreate) SetCreatedAt(v time.Time) *SessionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SessionCreate) SetNillableCreatedAt(v *time.Time) *SessionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SessionCreate) SetUpdatedAt(v time.Time) *SessionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SessionCreate) SetNillableUpdatedAt(v *time.Time) *SessionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SessionCreate) SetID(v uuid.UUID) *SessionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SessionCreate) SetNillableID(v *uuid.UUID) *SessionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetProject sets the "project" edge to the Project entity.
func (_c *SessionCreate) SetProject(v *Project) *SessionCreate {
	return _c.SetProjectID(v.ID)
}

// SetJourney sets the "journey" edge to the Journey entity.
func (_c *SessionCreate) SetJourney(v *Journey) *SessionCreate {
	return _c.SetJourneyID(v.ID)
}

// Mutation returns the SessionMutation object of the builder.
func (_c *SessionCreate) Mutation() *SessionMutation {
	return _c.mutation
}

// Save creates the Session in the database.
func (_c *SessionCreate) Save(ctx context.Context) (*Session, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SessionCreate) SaveX(ctx context.Context) *Session {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SessionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SessionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SessionCreate) defaults() {
	if _, ok := _c.mutation.DurationMs(); !ok {
		v := session.DefaultDurationMs
		_c.mutation.SetDurationMs(v)
	}
	if _, ok := _c.mutation.PageCount(); !ok {
		v := session.DefaultPageCount
		_c.mutation.SetPageCount(v)
	}
	if _, ok := _c.mutation.EventCount(); !ok {
		v := session.DefaultEventCount
		_c.mutation.SetEventCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := session.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := session.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := session.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SessionCreate) check() error {
	if _, ok := _c.mutation.OrgID(); !ok {
		return &ValidationError{Name: "org_id", err: errors.New(`ent: missing required field "Session.org_id"`)}
	}
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "Session.project_id"`)}
	}
	if _, ok := _c.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "Session.session_id"`)}
	}
	if v, ok := _c.mutation.SessionID(); ok {
		if err := session.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "Session.session_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := session.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Session.user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StartedAt(); !ok {
		return &ValidationError{Name: "started_at", err: errors.New(`ent: missing required field "Session.started_at"`)}
	}
	if _, ok := _c.mutation.DurationMs(); !ok {
		return &ValidationError{Name: "duration_ms", err: errors.New(`ent: missing required field "Session.duration_ms"`)}
	}
	if v, ok := _c.mutation.EntryPage(); ok {
		if err := session.EntryPageValidator(v); err != nil {
			return &ValidationError{Name: "entry_page", err: fmt.Errorf(`ent: validator failed for field "Session.entry_page": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ExitPage(); ok {
		if err := session.ExitPageValidator(v); err != nil {
			return &ValidationError{Name: "exit_page", err: fmt.Errorf(`ent: validator failed for field "Session.exit_page": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PageCount(); !ok {
		return &ValidationError{Name: "page_count", err: errors.New(`ent: missing required field "Session.page_count"`)}
	}
	if _, ok := _c.mutation.EventCount(); !ok {
		return &ValidationError{Name: "event_count", err: errors.New(`ent: missing required field "Session.event_count"`)}
	}
	if v, ok := _c.mutation.LastJourneyStepID(); ok {
		if err := session.LastJourneyStepIDValidator(v); err != nil {
			return &ValidationError{Name: "last_journey_step_id", err: fmt.Errorf(`ent: validator failed for field "Session.last_journey_step_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ConversionStatus(); ok {
		if err := session.ConversionStatusValidator(v); err != nil {
			return &ValidationError{Name: "conversion_status", err: fmt.Errorf(`ent: validator failed for field "Session.conversion_status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.UserAgent(); ok {
		if err := session.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "Session.user_agent": %w`, err)}
		}
	}
	if v, ok := _c.mutation.DeviceType(); ok {
		if err := session.DeviceTypeValidator(v); err != nil {
			return &ValidationError{Name: "device_type", err: fmt.Errorf(`ent: validator failed for field "Session.device_type": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Browser(); ok {
		if err := session.BrowserValidator(v); err != nil {
			return &ValidationError{Name: "browser", err: fmt.Errorf(`ent: validator failed for field "Session.browser": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Os(); ok {
		if err := session.OsValidator(v); err != nil {
			return &ValidationError{Name: "os", err: fmt.Errorf(`ent: validator failed for field "Session.os": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Country(); ok {
		if err := session.CountryValidator(v); err != nil {
			return &ValidationError{Name: "country", err: fmt.Errorf(`ent: validator failed for field "Session.country": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Region(); ok {
		if err := session.RegionValidator(v); err != nil {
			return &ValidationError{Name: "region", err: fmt.Errorf(`ent: validator failed for field "Session.region": %w`, err)}
		}
	}
	if v, ok := _c.mutation.City(); ok {
		if err := session.CityValidator(v); err != nil {
			return &ValidationError{Name: "city", err: fmt.Errorf(`ent: validator failed for field "Session.city": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Session.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Session.updated_at"`)}
	}
	if len(_c.mutation.ProjectIDs()) == 0 {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required edge "Session.project"`)}
	}
	return nil
}

func (_c *SessionCreate) sqlSave(ctx context.Context) (*Session, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SessionCreate) createSpec() (*Session, *sqlgraph.CreateSpec) {
	var (
		_node = &Session{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(session.Table, sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.OrgID(); ok {
		_spec.SetField(session.FieldOrgID, field.TypeUUID, value)
		_node.OrgID = value
	}
	if value, ok := _c.mutation.SessionID(); ok {
		_spec.SetField(session.FieldSessionID, field.TypeString, value)
		_node.SessionID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(session.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(session.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := _c.mutation.EndedAt(); ok {
		_spec.SetField(session.FieldEndedAt, field.TypeTime, value)
		_node.EndedAt = &value
	}
	if value, ok := _c.mutation.DurationMs(); ok {
		_spec.SetField(session.FieldDurationMs, field.TypeInt64, value)
		_node.DurationMs = value
	}
	if value, ok := _c.mutation.EntryPage(); ok {
		_spec.SetField(session.FieldEntryPage, field.TypeString, value)
		_node.EntryPage = value
	}
	if value, ok := _c.mutation.ExitPage(); ok {
		_spec.SetField(session.FieldExitPage, field.TypeString, value)
		_node.ExitPage = value
	}
	if value, ok := _c.mutation.PageCount(); ok {
		_spec.SetField(session.FieldPageCount, field.TypeInt, value)
		_node.PageCount = value
	}
	if value, ok := _c.mutation.EventCount(); ok {
		_spec.SetField(session.FieldEventCount, field.TypeInt, value)
		_node.EventCount = value
	}
	if value, ok := _c.mutation.LastJourneyStepID(); ok {
		_spec.SetField(session.FieldLastJourneyStepID, field.TypeString, value)
		_node.LastJourneyStepID = value
	}
	if value, ok := _c.mutation.ConversionStatus(); ok {
		_spec.SetField(session.FieldConversionStatus, field.TypeString, value)
		_node.ConversionStatus = value
	}
	if value, ok := _c.mutation.UserAgent(); ok {
		_spec.SetField(session.FieldUserAgent, field.TypeString, value)
		_node.UserAgent = value
	}
	if value, ok := _c.mutation.DeviceType(); ok {
		_spec.SetField(session.FieldDeviceType, field.TypeString, value)
		_node.DeviceType = value
	}
	if value, ok := _c.mutation.Browser(); ok {
		_spec.SetField(session.FieldBrowser, field.TypeString, value)
		_node.Browser = value
	}
	if value, ok := _c.mutation.Os(); ok {
		_spec.SetField(session.FieldOs, field.TypeString, value)
		_node.Os = value
	}
	if value, ok := _c.mutation.Country(); ok {
		_spec.SetField(session.FieldCountry, field.TypeString, value)
		_node.Country = value
	}
	if value, ok := _c.mutation.Region(); ok {
		_spec.SetField(session.FieldRegion, field.TypeString, value)
		_node.Region = value
	}
	if value, ok := _c.mutation.City(); ok {
		_spec.SetField(session.FieldCity, field.TypeString, value)
		_node.City = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(session.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(session.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   session.ProjectTable,
			Columns: []string{session.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProjectID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.JourneyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   session.JourneyTable,
			Columns: []string{session.JourneyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(journey.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.JourneyID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SessionCreateBulk is the builder for creating many Session entities in bulk.
type SessionCreateBulk struct {
	config
	err      error
	builders []*SessionCreate
}

// Save creates the Session entities in the database.
func (_c *SessionCreateBulk) Save(ctx context.Context) ([]*Session, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Session, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SessionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SessionCreateBulk) SaveX(ctx context.Context) []*Session {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SessionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SessionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
