// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/plexusone/productgraph/ent/journey"
	"github.com/plexusone/productgraph/ent/predicate"
	"github.com/plexusone/productgraph/ent/product"
	"github.com/plexusone/productgraph/ent/session"
)

// SessionUpdate is the builder for updating Session entities.
type SessionUpdate struct {
	config
	hooks    []Hook
	mutation *SessionMutation
}

// Where appends a list predicates to the SessionUpdate builder.
func (_u *SessionUpdate) Where(ps ...predicate.Session) *SessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOrgID sets the "org_id" field.
func (_u *SessionUpdate) SetOrgID(v uuid.UUID) *SessionUpdate {
	_u.mutation.SetOrgID(v)
	return _u
}

// SetNillableOrgID sets the "org_id" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableOrgID(v *uuid.UUID) *SessionUpdate {
	if v != nil {
		_u.SetOrgID(*v)
	}
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *SessionUpdate) SetProductID(v uuid.UUID) *SessionUpdate {
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableProductID(v *uuid.UUID) *SessionUpdate {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *SessionUpdate) SetSessionID(v string) *SessionUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableSessionID(v *string) *SessionUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SessionUpdate) SetUserID(v string) *SessionUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableUserID(v *string) *SessionUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *SessionUpdate) ClearUserID() *SessionUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *SessionUpdate) SetStartedAt(v time.Time) *SessionUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableStartedAt(v *time.Time) *SessionUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetEndedAt sets the "ended_at" field.
func (_u *SessionUpdate) SetEndedAt(v time.Time) *SessionUpdate {
	_u.mutation.SetEndedAt(v)
	return _u
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableEndedAt(v *time.Time) *SessionUpdate {
	if v != nil {
		_u.SetEndedAt(*v)
	}
	return _u
}

// ClearEndedAt clears the value of the "ended_at" field.
func (_u *SessionUpdate) ClearEndedAt() *SessionUpdate {
	_u.mutation.ClearEndedAt()
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *SessionUpdate) SetDurationMs(v int64) *SessionUpdate {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableDurationMs(v *int64) *SessionUpdate {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *SessionUpdate) AddDurationMs(v int64) *SessionUpdate {
	_u.mutation.AddDurationMs(v)
	return _u
}

// SetEntryPage sets the "entry_page" field.
func (_u *SessionUpdate) SetEntryPage(v string) *SessionUpdate {
	_u.mutation.SetEntryPage(v)
	return _u
}

// SetNillableEntryPage sets the "entry_page" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableEntryPage(v *string) *SessionUpdate {
	if v != nil {
		_u.SetEntryPage(*v)
	}
	return _u
}

// ClearEntryPage clears the value of the "entry_page" field.
func (_u *SessionUpdate) ClearEntryPage() *SessionUpdate {
	_u.mutation.ClearEntryPage()
	return _u
}

// SetExitPage sets the "exit_page" field.
func (_u *SessionUpdate) SetExitPage(v string) *SessionUpdate {
	_u.mutation.SetExitPage(v)
	return _u
}

// SetNillableExitPage sets the "exit_page" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableExitPage(v *string) *SessionUpdate {
	if v != nil {
		_u.SetExitPage(*v)
	}
	return _u
}

// ClearExitPage clears the value of the "exit_page" field.
func (_u *SessionUpdate) ClearExitPage() *SessionUpdate {
	_u.mutation.ClearExitPage()
	return _u
}

// SetPageCount sets the "page_count" field.
func (_u *SessionUpdate) SetPageCount(v int) *SessionUpdate {
	_u.mutation.ResetPageCount()
	_u.mutation.SetPageCount(v)
	return _u
}

// SetNillablePageCount sets the "page_count" field if the given value is not nil.
func (_u *SessionUpdate) SetNillablePageCount(v *int) *SessionUpdate {
	if v != nil {
		_u.SetPageCount(*v)
	}
	return _u
}

// AddPageCount adds value to the "page_count" field.
func (_u *SessionUpdate) AddPageCount(v int) *SessionUpdate {
	_u.mutation.AddPageCount(v)
	return _u
}

// SetEventCount sets the "event_count" field.
func (_u *SessionUpdate) SetEventCount(v int) *SessionUpdate {
	_u.mutation.ResetEventCount()
	_u.mutation.SetEventCount(v)
	return _u
}

// SetNillableEventCount sets the "event_count" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableEventCount(v *int) *SessionUpdate {
	if v != nil {
		_u.SetEventCount(*v)
	}
	return _u
}

// AddEventCount adds value to the "event_count" field.
func (_u *SessionUpdate) AddEventCount(v int) *SessionUpdate {
	_u.mutation.AddEventCount(v)
	return _u
}

// SetJourneyID sets the "journey_id" field.
func (_u *SessionUpdate) SetJourneyID(v uuid.UUID) *SessionUpdate {
	_u.mutation.SetJourneyID(v)
	return _u
}

// SetNillableJourneyID sets the "journey_id" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableJourneyID(v *uuid.UUID) *SessionUpdate {
	if v != nil {
		_u.SetJourneyID(*v)
	}
	return _u
}

// ClearJourneyID clears the value of the "journey_id" field.
func (_u *SessionUpdate) ClearJourneyID() *SessionUpdate {
	_u.mutation.ClearJourneyID()
	return _u
}

// SetLastJourneyStepID sets the "last_journey_step_id" field.
func (_u *SessionUpdate) SetLastJourneyStepID(v string) *SessionUpdate {
	_u.mutation.SetLastJourneyStepID(v)
	return _u
}

// SetNillableLastJourneyStepID sets the "last_journey_step_id" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableLastJourneyStepID(v *string) *SessionUpdate {
	if v != nil {
		_u.SetLastJourneyStepID(*v)
	}
	return _u
}

// ClearLastJourneyStepID clears the value of the "last_journey_step_id" field.
func (_u *SessionUpdate) ClearLastJourneyStepID() *SessionUpdate {
	_u.mutation.ClearLastJourneyStepID()
	return _u
}

// SetConversionStatus sets the "conversion_status" field.
func (_u *SessionUpdate) SetConversionStatus(v string) *SessionUpdate {
	_u.mutation.SetConversionStatus(v)
	return _u
}

// SetNillableConversionStatus sets the "conversion_status" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableConversionStatus(v *string) *SessionUpdate {
	if v != nil {
		_u.SetConversionStatus(*v)
	}
	return _u
}

// ClearConversionStatus clears the value of the "conversion_status" field.
func (_u *SessionUpdate) ClearConversionStatus() *SessionUpdate {
	_u.mutation.ClearConversionStatus()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *SessionUpdate) SetUserAgent(v string) *SessionUpdate {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableUserAgent(v *string) *SessionUpdate {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *SessionUpdate) ClearUserAgent() *SessionUpdate {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetDeviceType sets the "device_type" field.
func (_u *SessionUpdate) SetDeviceType(v string) *SessionUpdate {
	_u.mutation.SetDeviceType(v)
	return _u
}

// SetNillableDeviceType sets the "device_type" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableDeviceType(v *string) *SessionUpdate {
	if v != nil {
		_u.SetDeviceType(*v)
	}
	return _u
}

// ClearDeviceType clears the value of the "device_type" field.
func (_u *SessionUpdate) ClearDeviceType() *SessionUpdate {
	_u.mutation.ClearDeviceType()
	return _u
}

// SetBrowser sets the "browser" field.
func (_u *SessionUpdate) SetBrowser(v string) *SessionUpdate {
	_u.mutation.SetBrowser(v)
	return _u
}

// SetNillableBrowser sets the "browser" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableBrowser(v *string) *SessionUpdate {
	if v != nil {
		_u.SetBrowser(*v)
	}
	return _u
}

// ClearBrowser clears the value of the "browser" field.
func (_u *SessionUpdate) ClearBrowser() *SessionUpdate {
	_u.mutation.ClearBrowser()
	return _u
}

// SetOs sets the "os" field.
func (_u *SessionUpdate) SetOs(v string) *SessionUpdate {
	_u.mutation.SetOs(v)
	return _u
}

// SetNillableOs sets the "os" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableOs(v *string) *SessionUpdate {
	if v != nil {
		_u.SetOs(*v)
	}
	return _u
}

// ClearOs clears the value of the "os" field.
func (_u *SessionUpdate) ClearOs() *SessionUpdate {
	_u.mutation.ClearOs()
	return _u
}

// SetCountry sets the "country" field.
func (_u *SessionUpdate) SetCountry(v string) *SessionUpdate {
	_u.mutation.SetCountry(v)
	return _u
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableCountry(v *string) *SessionUpdate {
	if v != nil {
		_u.SetCountry(*v)
	}
	return _u
}

// ClearCountry clears the value of the "country" field.
func (_u *SessionUpdate) ClearCountry() *SessionUpdate {
	_u.mutation.ClearCountry()
	return _u
}

// SetRegion sets the "region" field.
func (_u *SessionUpdate) SetRegion(v string) *SessionUpdate {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableRegion(v *string) *SessionUpdate {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// ClearRegion clears the value of the "region" field.
func (_u *SessionUpdate) ClearRegion() *SessionUpdate {
	_u.mutation.ClearRegion()
	return _u
}

// SetCity sets the "city" field.
func (_u *SessionUpdate) SetCity(v string) *SessionUpdate {
	_u.mutation.SetCity(v)
	return _u
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableCity(v *string) *SessionUpdate {
	if v != nil {
		_u.SetCity(*v)
	}
	return _u
}

// ClearCity clears the value of the "city" field.
func (_u *SessionUpdate) ClearCity() *SessionUpdate {
	_u.mutation.ClearCity()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SessionUpdate) SetUpdatedAt(v time.Time) *SessionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProduct sets the "product" edge to the Product entity.
func (_u *SessionUpdate) SetProduct(v *Product) *SessionUpdate {
	return _u.SetProductID(v.ID)
}

// SetJourney sets the "journey" edge to the Journey entity.
func (_u *SessionUpdate) SetJourney(v *Journey) *SessionUpdate {
	return _u.SetJourneyID(v.ID)
}

// Mutation returns the SessionMutation object of the builder.
func (_u *SessionUpdate) Mutation() *SessionMutation {
	return _u.mutation
}

// ClearProduct clears the "product" edge to the Product entity.
func (_u *SessionUpdate) ClearProduct() *SessionUpdate {
	_u.mutation.ClearProduct()
	return _u
}

// ClearJourney clears the "journey" edge to the Journey entity.
func (_u *SessionUpdate) ClearJourney() *SessionUpdate {
	_u.mutation.ClearJourney()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SessionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SessionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := session.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SessionUpdate) check() error {
	if v, ok := _u.mutation.SessionID(); ok {
		if err := session.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "Session.session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserID(); ok {
		if err := session.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Session.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EntryPage(); ok {
		if err := session.EntryPageValidator(v); err != nil {
			return &ValidationError{Name: "entry_page", err: fmt.Errorf(`ent: validator failed for field "Session.entry_page": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExitPage(); ok {
		if err := session.ExitPageValidator(v); err != nil {
			return &ValidationError{Name: "exit_page", err: fmt.Errorf(`ent: validator failed for field "Session.exit_page": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastJourneyStepID(); ok {
		if err := session.LastJourneyStepIDValidator(v); err != nil {
			return &ValidationError{Name: "last_journey_step_id", err: fmt.Errorf(`ent: validator failed for field "Session.last_journey_step_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConversionStatus(); ok {
		if err := session.ConversionStatusValidator(v); err != nil {
			return &ValidationError{Name: "conversion_status", err: fmt.Errorf(`ent: validator failed for field "Session.conversion_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserAgent(); ok {
		if err := session.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "Session.user_agent": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeviceType(); ok {
		if err := session.DeviceTypeValidator(v); err != nil {
			return &ValidationError{Name: "device_type", err: fmt.Errorf(`ent: validator failed for field "Session.device_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Browser(); ok {
		if err := session.BrowserValidator(v); err != nil {
			return &ValidationError{Name: "browser", err: fmt.Errorf(`ent: validator failed for field "Session.browser": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Os(); ok {
		if err := session.OsValidator(v); err != nil {
			return &ValidationError{Name: "os", err: fmt.Errorf(`ent: validator failed for field "Session.os": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Country(); ok {
		if err := session.CountryValidator(v); err != nil {
			return &ValidationError{Name: "country", err: fmt.Errorf(`ent: validator failed for field "Session.country": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Region(); ok {
		if err := session.RegionValidator(v); err != nil {
			return &ValidationError{Name: "region", err: fmt.Errorf(`ent: validator failed for field "Session.region": %w`, err)}
		}
	}
	if v, ok := _u.mutation.City(); ok {
		if err := session.CityValidator(v); err != nil {
			return &ValidationError{Name: "city", err: fmt.Errorf(`ent: validator failed for field "Session.city": %w`, err)}
		}
	}
	if _u.mutation.ProductCleared() && len(_u.mutation.ProductIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Session.product"`)
	}
	return nil
}

func (_u *SessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(session.Table, session.Columns, sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrgID(); ok {
		_spec.SetField(session.FieldOrgID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(session.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(session.FieldUserID, field.TypeString, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(session.FieldUserID, field.TypeString)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(session.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndedAt(); ok {
		_spec.SetField(session.FieldEndedAt, field.TypeTime, value)
	}
	if _u.mutation.EndedAtCleared() {
		_spec.ClearField(session.FieldEndedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(session.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(session.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.EntryPage(); ok {
		_spec.SetField(session.FieldEntryPage, field.TypeString, value)
	}
	if _u.mutation.EntryPageCleared() {
		_spec.ClearField(session.FieldEntryPage, field.TypeString)
	}
	if value, ok := _u.mutation.ExitPage(); ok {
		_spec.SetField(session.FieldExitPage, field.TypeString, value)
	}
	if _u.mutation.ExitPageCleared() {
		_spec.ClearField(session.FieldExitPage, field.TypeString)
	}
	if value, ok := _u.mutation.PageCount(); ok {
		_spec.SetField(session.FieldPageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPageCount(); ok {
		_spec.AddField(session.FieldPageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.EventCount(); ok {
		_spec.SetField(session.FieldEventCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEventCount(); ok {
		_spec.AddField(session.FieldEventCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastJourneyStepID(); ok {
		_spec.SetField(session.FieldLastJourneyStepID, field.TypeString, value)
	}
	if _u.mutation.LastJourneyStepIDCleared() {
		_spec.ClearField(session.FieldLastJourneyStepID, field.TypeString)
	}
	if value, ok := _u.mutation.ConversionStatus(); ok {
		_spec.SetField(session.FieldConversionStatus, field.TypeString, value)
	}
	if _u.mutation.ConversionStatusCleared() {
		_spec.ClearField(session.FieldConversionStatus, field.TypeString)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(session.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(session.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.DeviceType(); ok {
		_spec.SetField(session.FieldDeviceType, field.TypeString, value)
	}
	if _u.mutation.DeviceTypeCleared() {
		_spec.ClearField(session.FieldDeviceType, field.TypeString)
	}
	if value, ok := _u.mutation.Browser(); ok {
		_spec.SetField(session.FieldBrowser, field.TypeString, value)
	}
	if _u.mutation.BrowserCleared() {
		_spec.ClearField(session.FieldBrowser, field.TypeString)
	}
	if value, ok := _u.mutation.Os(); ok {
		_spec.SetField(session.FieldOs, field.TypeString, value)
	}
	if _u.mutation.OsCleared() {
		_spec.ClearField(session.FieldOs, field.TypeString)
	}
	if value, ok := _u.mutation.Country(); ok {
		_spec.SetField(session.FieldCountry, field.TypeString, value)
	}
	if _u.mutation.CountryCleared() {
		_spec.ClearField(session.FieldCountry, field.TypeString)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(session.FieldRegion, field.TypeString, value)
	}
	if _u.mutation.RegionCleared() {
		_spec.ClearField(session.FieldRegion, field.TypeString)
	}
	if value, ok := _u.mutation.City(); ok {
		_spec.SetField(session.FieldCity, field.TypeString, value)
	}
	if _u.mutation.CityCleared() {
		_spec.ClearField(session.FieldCity, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(session.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ProductCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   session.ProductTable,
			Columns: []string{session.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   session.ProductTable,
			Columns: []string{session.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.JourneyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   session.JourneyTable,
			Columns: []string{session.JourneyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(journey.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.JourneyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   session.JourneyTable,
			Columns: []string{session.JourneyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(journey.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{session.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SessionUpdateOne is the builder for updating a single Session entity.
type SessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SessionMutation
}

// SetOrgID sets the "org_id" field.
func (_u *SessionUpdateOne) SetOrgID(v uuid.UUID) *SessionUpdateOne {
	_u.mutation.SetOrgID(v)
	return _u
}

// SetNillableOrgID sets the "org_id" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableOrgID(v *uuid.UUID) *SessionUpdateOne {
	if v != nil {
		_u.SetOrgID(*v)
	}
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *SessionUpdateOne) SetProductID(v uuid.UUID) *SessionUpdateOne {
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableProductID(v *uuid.UUID) *SessionUpdateOne {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *SessionUpdateOne) SetSessionID(v string) *SessionUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableSessionID(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SessionUpdateOne) SetUserID(v string) *SessionUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableUserID(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *SessionUpdateOne) ClearUserID() *SessionUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *SessionUpdateOne) SetStartedAt(v time.Time) *SessionUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableStartedAt(v *time.Time) *SessionUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetEndedAt sets the "ended_at" field.
func (_u *SessionUpdateOne) SetEndedAt(v time.Time) *SessionUpdateOne {
	_u.mutation.SetEndedAt(v)
	return _u
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableEndedAt(v *time.Time) *SessionUpdateOne {
	if v != nil {
		_u.SetEndedAt(*v)
	}
	return _u
}

// ClearEndedAt clears the value of the "ended_at" field.
func (_u *SessionUpdateOne) ClearEndedAt() *SessionUpdateOne {
	_u.mutation.ClearEndedAt()
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *SessionUpdateOne) SetDurationMs(v int64) *SessionUpdateOne {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableDurationMs(v *int64) *SessionUpdateOne {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *SessionUpdateOne) AddDurationMs(v int64) *SessionUpdateOne {
	_u.mutation.AddDurationMs(v)
	return _u
}

// SetEntryPage sets the "entry_page" field.
func (_u *SessionUpdateOne) SetEntryPage(v string) *SessionUpdateOne {
	_u.mutation.SetEntryPage(v)
	return _u
}

// SetNillableEntryPage sets the "entry_page" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableEntryPage(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetEntryPage(*v)
	}
	return _u
}

// ClearEntryPage clears the value of the "entry_page" field.
func (_u *SessionUpdateOne) ClearEntryPage() *SessionUpdateOne {
	_u.mutation.ClearEntryPage()
	return _u
}

// SetExitPage sets the "exit_page" field.
func (_u *SessionUpdateOne) SetExitPage(v string) *SessionUpdateOne {
	_u.mutation.SetExitPage(v)
	return _u
}

// SetNillableExitPage sets the "exit_page" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableExitPage(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetExitPage(*v)
	}
	return _u
}

// ClearExitPage clears the value of the "exit_page" field.
func (_u *SessionUpdateOne) ClearExitPage() *SessionUpdateOne {
	_u.mutation.ClearExitPage()
	return _u
}

// SetPageCount sets the "page_count" field.
func (_u *SessionUpdateOne) SetPageCount(v int) *SessionUpdateOne {
	_u.mutation.ResetPageCount()
	_u.mutation.SetPageCount(v)
	return _u
}

// SetNillablePageCount sets the "page_count" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillablePageCount(v *int) *SessionUpdateOne {
	if v != nil {
		_u.SetPageCount(*v)
	}
	return _u
}

// AddPageCount adds value to the "page_count" field.
func (_u *SessionUpdateOne) AddPageCount(v int) *SessionUpdateOne {
	_u.mutation.AddPageCount(v)
	return _u
}

// SetEventCount sets the "event_count" field.
func (_u *SessionUpdateOne) SetEventCount(v int) *SessionUpdateOne {
	_u.mutation.ResetEventCount()
	_u.mutation.SetEventCount(v)
	return _u
}

// SetNillableEventCount sets the "event_count" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableEventCount(v *int) *SessionUpdateOne {
	if v != nil {
		_u.SetEventCount(*v)
	}
	return _u
}

// AddEventCount adds value to the "event_count" field.
func (_u *SessionUpdateOne) AddEventCount(v int) *SessionUpdateOne {
	_u.mutation.AddEventCount(v)
	return _u
}

// SetJourneyID sets the "journey_id" field.
func (_u *SessionUpdateOne) SetJourneyID(v uuid.UUID) *SessionUpdateOne {
	_u.mutation.SetJourneyID(v)
	return _u
}

// SetNillableJourneyID sets the "journey_id" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableJourneyID(v *uuid.UUID) *SessionUpdateOne {
	if v != nil {
		_u.SetJourneyID(*v)
	}
	return _u
}

// ClearJourneyID clears the value of the "journey_id" field.
func (_u *SessionUpdateOne) ClearJourneyID() *SessionUpdateOne {
	_u.mutation.ClearJourneyID()
	return _u
}

// SetLastJourneyStepID sets the "last_journey_step_id" field.
func (_u *SessionUpdateOne) SetLastJourneyStepID(v string) *SessionUpdateOne {
	_u.mutation.SetLastJourneyStepID(v)
	return _u
}

// SetNillableLastJourneyStepID sets the "last_journey_step_id" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableLastJourneyStepID(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetLastJourneyStepID(*v)
	}
	return _u
}

// ClearLastJourneyStepID clears the value of the "last_journey_step_id" field.
func (_u *SessionUpdateOne) ClearLastJourneyStepID() *SessionUpdateOne {
	_u.mutation.ClearLastJourneyStepID()
	return _u
}

// SetConversionStatus sets the "conversion_status" field.
func (_u *SessionUpdateOne) SetConversionStatus(v string) *SessionUpdateOne {
	_u.mutation.SetConversionStatus(v)
	return _u
}

// SetNillableConversionStatus sets the "conversion_status" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableConversionStatus(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetConversionStatus(*v)
	}
	return _u
}

// ClearConversionStatus clears the value of the "conversion_status" field.
func (_u *SessionUpdateOne) ClearConversionStatus() *SessionUpdateOne {
	_u.mutation.ClearConversionStatus()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *SessionUpdateOne) SetUserAgent(v string) *SessionUpdateOne {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableUserAgent(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *SessionUpdateOne) ClearUserAgent() *SessionUpdateOne {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetDeviceType sets the "device_type" field.
func (_u *SessionUpdateOne) SetDeviceType(v string) *SessionUpdateOne {
	_u.mutation.SetDeviceType(v)
	return _u
}

// SetNillableDeviceType sets the "device_type" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableDeviceType(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetDeviceType(*v)
	}
	return _u
}

// ClearDeviceType clears the value of the "device_type" field.
func (_u *SessionUpdateOne) ClearDeviceType() *SessionUpdateOne {
	_u.mutation.ClearDeviceType()
	return _u
}

// SetBrowser sets the "browser" field.
func (_u *SessionUpdateOne) SetBrowser(v string) *SessionUpdateOne {
	_u.mutation.SetBrowser(v)
	return _u
}

// SetNillableBrowser sets the "browser" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableBrowser(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetBrowser(*v)
	}
	return _u
}

// ClearBrowser clears the value of the "browser" field.
func (_u *SessionUpdateOne) ClearBrowser() *SessionUpdateOne {
	_u.mutation.ClearBrowser()
	return _u
}

// SetOs sets the "os" field.
func (_u *SessionUpdateOne) SetOs(v string) *SessionUpdateOne {
	_u.mutation.SetOs(v)
	return _u
}

// SetNillableOs sets the "os" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableOs(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetOs(*v)
	}
	return _u
}

// ClearOs clears the value of the "os" field.
func (_u *SessionUpdateOne) ClearOs() *SessionUpdateOne {
	_u.mutation.ClearOs()
	return _u
}

// SetCountry sets the "country" field.
func (_u *SessionUpdateOne) SetCountry(v string) *SessionUpdateOne {
	_u.mutation.SetCountry(v)
	return _u
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableCountry(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetCountry(*v)
	}
	return _u
}

// ClearCountry clears the value of the "country" field.
func (_u *SessionUpdateOne) ClearCountry() *SessionUpdateOne {
	_u.mutation.ClearCountry()
	return _u
}

// SetRegion sets the "region" field.
func (_u *SessionUpdateOne) SetRegion(v string) *SessionUpdateOne {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableRegion(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// ClearRegion clears the value of the "region" field.
func (_u *SessionUpdateOne) ClearRegion() *SessionUpdateOne {
	_u.mutation.ClearRegion()
	return _u
}

// SetCity sets the "city" field.
func (_u *SessionUpdateOne) SetCity(v string) *SessionUpdateOne {
	_u.mutation.SetCity(v)
	return _u
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableCity(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetCity(*v)
	}
	return _u
}

// ClearCity clears the value of the "city" field.
func (_u *SessionUpdateOne) ClearCity() *SessionUpdateOne {
	_u.mutation.ClearCity()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SessionUpdateOne) SetUpdatedAt(v time.Time) *SessionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProduct sets the "product" edge to the Product entity.
func (_u *SessionUpdateOne) SetProduct(v *Product) *SessionUpdateOne {
	return _u.SetProductID(v.ID)
}

// SetJourney sets the "journey" edge to the Journey entity.
func (_u *SessionUpdateOne) SetJourney(v *Journey) *SessionUpdateOne {
	return _u.SetJourneyID(v.ID)
}

// Mutation returns the SessionMutation object of the builder.
func (_u *SessionUpdateOne) Mutation() *SessionMutation {
	return _u.mutation
}

// ClearProduct clears the "product" edge to the Product entity.
func (_u *SessionUpdateOne) ClearProduct() *SessionUpdateOne {
	_u.mutation.ClearProduct()
	return _u
}

// ClearJourney clears the "journey" edge to the Journey entity.
func (_u *SessionUpdateOne) ClearJourney() *SessionUpdateOne {
	_u.mutation.ClearJourney()
	return _u
}

// Where appends a list predicates to the SessionUpdate builder.
func (_u *SessionUpdateOne) Where(ps ...predicate.Session) *SessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SessionUpdateOne) Select(field string, fields ...string) *SessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Session entity.
func (_u *SessionUpdateOne) Save(ctx context.Context) (*Session, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SessionUpdateOne) SaveX(ctx context.Context) *Session {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SessionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := session.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SessionUpdateOne) check() error {
	if v, ok := _u.mutation.SessionID(); ok {
		if err := session.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "Session.session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserID(); ok {
		if err := session.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Session.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EntryPage(); ok {
		if err := session.EntryPageValidator(v); err != nil {
			return &ValidationError{Name: "entry_page", err: fmt.Errorf(`ent: validator failed for field "Session.entry_page": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExitPage(); ok {
		if err := session.ExitPageValidator(v); err != nil {
			return &ValidationError{Name: "exit_page", err: fmt.Errorf(`ent: validator failed for field "Session.exit_page": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastJourneyStepID(); ok {
		if err := session.LastJourneyStepIDValidator(v); err != nil {
			return &ValidationError{Name: "last_journey_step_id", err: fmt.Errorf(`ent: validator failed for field "Session.last_journey_step_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConversionStatus(); ok {
		if err := session.ConversionStatusValidator(v); err != nil {
			return &ValidationError{Name: "conversion_status", err: fmt.Errorf(`ent: validator failed for field "Session.conversion_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserAgent(); ok {
		if err := session.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "Session.user_agent": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeviceType(); ok {
		if err := session.DeviceTypeValidator(v); err != nil {
			return &ValidationError{Name: "device_type", err: fmt.Errorf(`ent: validator failed for field "Session.device_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Browser(); ok {
		if err := session.BrowserValidator(v); err != nil {
			return &ValidationError{Name: "browser", err: fmt.Errorf(`ent: validator failed for field "Session.browser": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Os(); ok {
		if err := session.OsValidator(v); err != nil {
			return &ValidationError{Name: "os", err: fmt.Errorf(`ent: validator failed for field "Session.os": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Country(); ok {
		if err := session.CountryValidator(v); err != nil {
			return &ValidationError{Name: "country", err: fmt.Errorf(`ent: validator failed for field "Session.country": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Region(); ok {
		if err := session.RegionValidator(v); err != nil {
			return &ValidationError{Name: "region", err: fmt.Errorf(`ent: validator failed for field "Session.region": %w`, err)}
		}
	}
	if v, ok := _u.mutation.City(); ok {
		if err := session.CityValidator(v); err != nil {
			return &ValidationError{Name: "city", err: fmt.Errorf(`ent: validator failed for field "Session.city": %w`, err)}
		}
	}
	if _u.mutation.ProductCleared() && len(_u.mutation.ProductIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Session.product"`)
	}
	return nil
}

func (_u *SessionUpdateOne) sqlSave(ctx context.Context) (_node *Session, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(session.Table, session.Columns, sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Session.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, session.FieldID)
		for _, f := range fields {
			if !session.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != session.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrgID(); ok {
		_spec.SetField(session.FieldOrgID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(session.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(session.FieldUserID, field.TypeString, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(session.FieldUserID, field.TypeString)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(session.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndedAt(); ok {
		_spec.SetField(session.FieldEndedAt, field.TypeTime, value)
	}
	if _u.mutation.EndedAtCleared() {
		_spec.ClearField(session.FieldEndedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(session.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(session.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.EntryPage(); ok {
		_spec.SetField(session.FieldEntryPage, field.TypeString, value)
	}
	if _u.mutation.EntryPageCleared() {
		_spec.ClearField(session.FieldEntryPage, field.TypeString)
	}
	if value, ok := _u.mutation.ExitPage(); ok {
		_spec.SetField(session.FieldExitPage, field.TypeString, value)
	}
	if _u.mutation.ExitPageCleared() {
		_spec.ClearField(session.FieldExitPage, field.TypeString)
	}
	if value, ok := _u.mutation.PageCount(); ok {
		_spec.SetField(session.FieldPageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPageCount(); ok {
		_spec.AddField(session.FieldPageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.EventCount(); ok {
		_spec.SetField(session.FieldEventCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEventCount(); ok {
		_spec.AddField(session.FieldEventCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastJourneyStepID(); ok {
		_spec.SetField(session.FieldLastJourneyStepID, field.TypeString, value)
	}
	if _u.mutation.LastJourneyStepIDCleared() {
		_spec.ClearField(session.FieldLastJourneyStepID, field.TypeString)
	}
	if value, ok := _u.mutation.ConversionStatus(); ok {
		_spec.SetField(session.FieldConversionStatus, field.TypeString, value)
	}
	if _u.mutation.ConversionStatusCleared() {
		_spec.ClearField(session.FieldConversionStatus, field.TypeString)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(session.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(session.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.DeviceType(); ok {
		_spec.SetField(session.FieldDeviceType, field.TypeString, value)
	}
	if _u.mutation.DeviceTypeCleared() {
		_spec.ClearField(session.FieldDeviceType, field.TypeString)
	}
	if value, ok := _u.mutation.Browser(); ok {
		_spec.SetField(session.FieldBrowser, field.TypeString, value)
	}
	if _u.mutation.BrowserCleared() {
		_spec.ClearField(session.FieldBrowser, field.TypeString)
	}
	if value, ok := _u.mutation.Os(); ok {
		_spec.SetField(session.FieldOs, field.TypeString, value)
	}
	if _u.mutation.OsCleared() {
		_spec.ClearField(session.FieldOs, field.TypeString)
	}
	if value, ok := _u.mutation.Country(); ok {
		_spec.SetField(session.FieldCountry, field.TypeString, value)
	}
	if _u.mutation.CountryCleared() {
		_spec.ClearField(session.FieldCountry, field.TypeString)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(session.FieldRegion, field.TypeString, value)
	}
	if _u.mutation.RegionCleared() {
		_spec.ClearField(session.FieldRegion, field.TypeString)
	}
	if value, ok := _u.mutation.City(); ok {
		_spec.SetField(session.FieldCity, field.TypeString, value)
	}
	if _u.mutation.CityCleared() {
		_spec.ClearField(session.FieldCity, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(session.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ProductCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   session.ProductTable,
			Columns: []string{session.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   session.ProductTable,
			Columns: []string{session.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.JourneyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   session.JourneyTable,
			Columns: []string{session.JourneyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(journey.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.JourneyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   session.JourneyTable,
			Columns: []string{session.JourneyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(journey.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Session{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{session.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
