// Code generated by ent, DO NOT EDIT.

package journey

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/plexusone/productgraph/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Journey {
	return predicate.Journey(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Journey {
	return predicate.Journey(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Journey {
	return predicate.Journey(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Journey {
	return predicate.Journey(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Journey {
	return predicate.Journey(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Journey {
	return predicate.Journey(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Journey {
	return predicate.Journey(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Journey {
	return predicate.Journey(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Journey {
	return predicate.Journey(sql.FieldLTE(FieldID, id))
}

// OrgID applies equality check predicate on the "org_id" field. It's identical to OrgIDEQ.
func OrgID(v uuid.UUID) predicate.Journey {
	return predicate.Journey(sql.FieldEQ(FieldOrgID, v))
}

// ProductID applies equality check predicate on the "product_id" field. It's identical to ProductIDEQ.
func ProductID(v uuid.UUID) predicate.Journey {
	return predicate.Journey(sql.FieldEQ(FieldProductID, v))
}

// FeatureID applies equality check predicate on the "feature_id" field. It's identical to FeatureIDEQ.
func FeatureID(v uuid.UUID) predicate.Journey {
	return predicate.Journey(sql.FieldEQ(FieldFeatureID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Journey {
	return predicate.Journey(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Journey {
	return predicate.Journey(sql.FieldEQ(FieldDescription, v))
}

// TimeoutMinutes applies equality check predicate on the "timeout_minutes" field. It's identical to TimeoutMinutesEQ.
func TimeoutMinutes(v int) predicate.Journey {
	return predicate.Journey(sql.FieldEQ(FieldTimeoutMinutes, v))
}

// TotalSessions applies equality check predicate on the "total_sessions" field. It's identical to TotalSessionsEQ.
func TotalSessions(v int64) predicate.Journey {
	return predicate.Journey(sql.FieldEQ(FieldTotalSessions, v))
}

// ConvertedSessions applies equality check predicate on the "converted_sessions" field. It's identical to ConvertedSessionsEQ.
func ConvertedSessions(v int64) predicate.Journey {
	return predicate.Journey(sql.FieldEQ(FieldConvertedSessions, v))
}

// ConversionRate applies equality check predicate on the "conversion_rate" field. It's identical to ConversionRateEQ.
func ConversionRate(v float64) predicate.Journey {
	return predicate.Journey(sql.FieldEQ(FieldConversionRate, v))
}

// AvgDurationMs applies equality check predicate on the "avg_duration_ms" field. It's identical to AvgDurationMsEQ.
func AvgDurationMs(v int64) predicate.Journey {
	return predicate.Journey(sql.FieldEQ(FieldAvgDurationMs, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.Journey {
	return predicate.Journey(sql.FieldEQ(FieldIsActive, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Journey {
	return predicate.Journey(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Journey {
	return predicate.Journey(sql.FieldEQ(FieldUpdatedAt, v))
}

// OrgIDEQ applies the EQ predicate on the "org_id" field.
func OrgIDEQ(v uuid.UUID) predicate.Journey {
	return predicate.Journey(sql.FieldEQ(FieldOrgID, v))
}

// OrgIDNEQ applies the NEQ predicate on the "org_id" field.
func OrgIDNEQ(v uuid.UUID) predicate.Journey {
	return predicate.Journey(sql.FieldNEQ(FieldOrgID, v))
}

// OrgIDIn applies the In predicate on the "org_id" field.
func OrgIDIn(vs ...uuid.UUID) predicate.Journey {
	return predicate.Journey(sql.FieldIn(FieldOrgID, vs...))
}

// OrgIDNotIn applies the NotIn predicate on the "org_id" field.
func OrgIDNotIn(vs ...uuid.UUID) predicate.Journey {
	return predicate.Journey(sql.FieldNotIn(FieldOrgID, vs...))
}

// OrgIDGT applies the GT predicate on the "org_id" field.
func OrgIDGT(v uuid.UUID) predicate.Journey {
	return predicate.Journey(sql.FieldGT(FieldOrgID, v))
}

// OrgIDGTE applies the GTE predicate on the "org_id" field.
func OrgIDGTE(v uuid.UUID) predicate.Journey {
	return predicate.Journey(sql.FieldGTE(FieldOrgID, v))
}

// OrgIDLT applies the LT predicate on the "org_id" field.
func OrgIDLT(v uuid.UUID) predicate.Journey {
	return predicate.Journey(sql.FieldLT(FieldOrgID, v))
}

// OrgIDLTE applies the LTE predicate on the "org_id" field.
func OrgIDLTE(v uuid.UUID) predicate.Journey {
	return predicate.Journey(sql.FieldLTE(FieldOrgID, v))
}

// ProductIDEQ applies the EQ predicate on the "product_id" field.
func ProductIDEQ(v uuid.UUID) predicate.Journey {
	return predicate.Journey(sql.FieldEQ(FieldProductID, v))
}

// ProductIDNEQ applies the NEQ predicate on the "product_id" field.
func ProductIDNEQ(v uuid.UUID) predicate.Journey {
	return predicate.Journey(sql.FieldNEQ(FieldProductID, v))
}

// ProductIDIn applies the In predicate on the "product_id" field.
func ProductIDIn(vs ...uuid.UUID) predicate.Journey {
	return predicate.Journey(sql.FieldIn(FieldProductID, vs...))
}

// ProductIDNotIn applies the NotIn predicate on the "product_id" field.
func ProductIDNotIn(vs ...uuid.UUID) predicate.Journey {
	return predicate.Journey(sql.FieldNotIn(FieldProductID, vs...))
}

// FeatureIDEQ applies the EQ predicate on the "feature_id" field.
func FeatureIDEQ(v uuid.UUID) predicate.Journey {
	return predicate.Journey(sql.FieldEQ(FieldFeatureID, v))
}

// FeatureIDNEQ applies the NEQ predicate on the "feature_id" field.
func FeatureIDNEQ(v uuid.UUID) predicate.Journey {
	return predicate.Journey(sql.FieldNEQ(FieldFeatureID, v))
}

// FeatureIDIn applies the In predicate on the "feature_id" field.
func FeatureIDIn(vs ...uuid.UUID) predicate.Journey {
	return predicate.Journey(sql.FieldIn(FieldFeatureID, vs...))
}

// FeatureIDNotIn applies the NotIn predicate on the "feature_id" field.
func FeatureIDNotIn(vs ...uuid.UUID) predicate.Journey {
	return predicate.Journey(sql.FieldNotIn(FieldFeatureID, vs...))
}

// FeatureIDIsNil applies the IsNil predicate on the "feature_id" field.
func FeatureIDIsNil() predicate.Journey {
	return predicate.Journey(sql.FieldIsNull(FieldFeatureID))
}

// FeatureIDNotNil applies the NotNil predicate on the "feature_id" field.
func FeatureIDNotNil() predicate.Journey {
	return predicate.Journey(sql.FieldNotNull(FieldFeatureID))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Journey {
	return predicate.Journey(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Journey {
	return predicate.Journey(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Journey {
	return predicate.Journey(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Journey {
	return predicate.Journey(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Journey {
	return predicate.Journey(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Journey {
	return predicate.Journey(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Journey {
	return predicate.Journey(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Journey {
	return predicate.Journey(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Journey {
	return predicate.Journey(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Journey {
	return predicate.Journey(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Journey {
	return predicate.Journey(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Journey {
	return predicate.Journey(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Journey {
	return predicate.Journey(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Journey {
	return predicate.Journey(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Journey {
	return predicate.Journey(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Journey {
	return predicate.Journey(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Journey {
	return predicate.Journey(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Journey {
	return predicate.Journey(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Journey {
	return predicate.Journey(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Journey {
	return predicate.Journey(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Journey {
	return predicate.Journey(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Journey {
	return predicate.Journey(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Journey {
	return predicate.Journey(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Journey {
	return predicate.Journey(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Journey {
	return predicate.Journey(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Journey {
	return predicate.Journey(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Journey {
	return predicate.Journey(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Journey {
	return predicate.Journey(sql.FieldContainsFold(FieldDescription, v))
}

// EntryConditionsIsNil applies the IsNil predicate on the "entry_conditions" field.
func EntryConditionsIsNil() predicate.Journey {
	return predicate.Journey(sql.FieldIsNull(FieldEntryConditions))
}

// EntryConditionsNotNil applies the NotNil predicate on the "entry_conditions" field.
func EntryConditionsNotNil() predicate.Journey {
	return predicate.Journey(sql.FieldNotNull(FieldEntryConditions))
}

// ExitConditionsIsNil applies the IsNil predicate on the "exit_conditions" field.
func ExitConditionsIsNil() predicate.Journey {
	return predicate.Journey(sql.FieldIsNull(FieldExitConditions))
}

// ExitConditionsNotNil applies the NotNil predicate on the "exit_conditions" field.
func ExitConditionsNotNil() predicate.Journey {
	return predicate.Journey(sql.FieldNotNull(FieldExitConditions))
}

// StepsIsNil applies the IsNil predicate on the "steps" field.
func StepsIsNil() predicate.Journey {
	return predicate.Journey(sql.FieldIsNull(FieldSteps))
}

// StepsNotNil applies the NotNil predicate on the "steps" field.
func StepsNotNil() predicate.Journey {
	return predicate.Journey(sql.FieldNotNull(FieldSteps))
}

// TimeoutMinutesEQ applies the EQ predicate on the "timeout_minutes" field.
func TimeoutMinutesEQ(v int) predicate.Journey {
	return predicate.Journey(sql.FieldEQ(FieldTimeoutMinutes, v))
}

// TimeoutMinutesNEQ applies the NEQ predicate on the "timeout_minutes" field.
func TimeoutMinutesNEQ(v int) predicate.Journey {
	return predicate.Journey(sql.FieldNEQ(FieldTimeoutMinutes, v))
}

// TimeoutMinutesIn applies the In predicate on the "timeout_minutes" field.
func TimeoutMinutesIn(vs ...int) predicate.Journey {
	return predicate.Journey(sql.FieldIn(FieldTimeoutMinutes, vs...))
}

// TimeoutMinutesNotIn applies the NotIn predicate on the "timeout_minutes" field.
func TimeoutMinutesNotIn(vs ...int) predicate.Journey {
	return predicate.Journey(sql.FieldNotIn(FieldTimeoutMinutes, vs...))
}

// TimeoutMinutesGT applies the GT predicate on the "timeout_minutes" field.
func TimeoutMinutesGT(v int) predicate.Journey {
	return predicate.Journey(sql.FieldGT(FieldTimeoutMinutes, v))
}

// TimeoutMinutesGTE applies the GTE predicate on the "timeout_minutes" field.
func TimeoutMinutesGTE(v int) predicate.Journey {
	return predicate.Journey(sql.FieldGTE(FieldTimeoutMinutes, v))
}

// TimeoutMinutesLT applies the LT predicate on the "timeout_minutes" field.
func TimeoutMinutesLT(v int) predicate.Journey {
	return predicate.Journey(sql.FieldLT(FieldTimeoutMinutes, v))
}

// TimeoutMinutesLTE applies the LTE predicate on the "timeout_minutes" field.
func TimeoutMinutesLTE(v int) predicate.Journey {
	return predicate.Journey(sql.FieldLTE(FieldTimeoutMinutes, v))
}

// TotalSessionsEQ applies the EQ predicate on the "total_sessions" field.
func TotalSessionsEQ(v int64) predicate.Journey {
	return predicate.Journey(sql.FieldEQ(FieldTotalSessions, v))
}

// TotalSessionsNEQ applies the NEQ predicate on the "total_sessions" field.
func TotalSessionsNEQ(v int64) predicate.Journey {
	return predicate.Journey(sql.FieldNEQ(FieldTotalSessions, v))
}

// TotalSessionsIn applies the In predicate on the "total_sessions" field.
func TotalSessionsIn(vs ...int64) predicate.Journey {
	return predicate.Journey(sql.FieldIn(FieldTotalSessions, vs...))
}

// TotalSessionsNotIn applies the NotIn predicate on the "total_sessions" field.
func TotalSessionsNotIn(vs ...int64) predicate.Journey {
	return predicate.Journey(sql.FieldNotIn(FieldTotalSessions, vs...))
}

// TotalSessionsGT applies the GT predicate on the "total_sessions" field.
func TotalSessionsGT(v int64) predicate.Journey {
	return predicate.Journey(sql.FieldGT(FieldTotalSessions, v))
}

// TotalSessionsGTE applies the GTE predicate on the "total_sessions" field.
func TotalSessionsGTE(v int64) predicate.Journey {
	return predicate.Journey(sql.FieldGTE(FieldTotalSessions, v))
}

// TotalSessionsLT applies the LT predicate on the "total_sessions" field.
func TotalSessionsLT(v int64) predicate.Journey {
	return predicate.Journey(sql.FieldLT(FieldTotalSessions, v))
}

// TotalSessionsLTE applies the LTE predicate on the "total_sessions" field.
func TotalSessionsLTE(v int64) predicate.Journey {
	return predicate.Journey(sql.FieldLTE(FieldTotalSessions, v))
}

// ConvertedSessionsEQ applies the EQ predicate on the "converted_sessions" field.
func ConvertedSessionsEQ(v int64) predicate.Journey {
	return predicate.Journey(sql.FieldEQ(FieldConvertedSessions, v))
}

// ConvertedSessionsNEQ applies the NEQ predicate on the "converted_sessions" field.
func ConvertedSessionsNEQ(v int64) predicate.Journey {
	return predicate.Journey(sql.FieldNEQ(FieldConvertedSessions, v))
}

// ConvertedSessionsIn applies the In predicate on the "converted_sessions" field.
func ConvertedSessionsIn(vs ...int64) predicate.Journey {
	return predicate.Journey(sql.FieldIn(FieldConvertedSessions, vs...))
}

// ConvertedSessionsNotIn applies the NotIn predicate on the "converted_sessions" field.
func ConvertedSessionsNotIn(vs ...int64) predicate.Journey {
	return predicate.Journey(sql.FieldNotIn(FieldConvertedSessions, vs...))
}

// ConvertedSessionsGT applies the GT predicate on the "converted_sessions" field.
func ConvertedSessionsGT(v int64) predicate.Journey {
	return predicate.Journey(sql.FieldGT(FieldConvertedSessions, v))
}

// ConvertedSessionsGTE applies the GTE predicate on the "converted_sessions" field.
func ConvertedSessionsGTE(v int64) predicate.Journey {
	return predicate.Journey(sql.FieldGTE(FieldConvertedSessions, v))
}

// ConvertedSessionsLT applies the LT predicate on the "converted_sessions" field.
func ConvertedSessionsLT(v int64) predicate.Journey {
	return predicate.Journey(sql.FieldLT(FieldConvertedSessions, v))
}

// ConvertedSessionsLTE applies the LTE predicate on the "converted_sessions" field.
func ConvertedSessionsLTE(v int64) predicate.Journey {
	return predicate.Journey(sql.FieldLTE(FieldConvertedSessions, v))
}

// ConversionRateEQ applies the EQ predicate on the "conversion_rate" field.
func ConversionRateEQ(v float64) predicate.Journey {
	return predicate.Journey(sql.FieldEQ(FieldConversionRate, v))
}

// ConversionRateNEQ applies the NEQ predicate on the "conversion_rate" field.
func ConversionRateNEQ(v float64) predicate.Journey {
	return predicate.Journey(sql.FieldNEQ(FieldConversionRate, v))
}

// ConversionRateIn applies the In predicate on the "conversion_rate" field.
func ConversionRateIn(vs ...float64) predicate.Journey {
	return predicate.Journey(sql.FieldIn(FieldConversionRate, vs...))
}

// ConversionRateNotIn applies the NotIn predicate on the "conversion_rate" field.
func ConversionRateNotIn(vs ...float64) predicate.Journey {
	return predicate.Journey(sql.FieldNotIn(FieldConversionRate, vs...))
}

// ConversionRateGT applies the GT predicate on the "conversion_rate" field.
func ConversionRateGT(v float64) predicate.Journey {
	return predicate.Journey(sql.FieldGT(FieldConversionRate, v))
}

// ConversionRateGTE applies the GTE predicate on the "conversion_rate" field.
func ConversionRateGTE(v float64) predicate.Journey {
	return predicate.Journey(sql.FieldGTE(FieldConversionRate, v))
}

// ConversionRateLT applies the LT predicate on the "conversion_rate" field.
func ConversionRateLT(v float64) predicate.Journey {
	return predicate.Journey(sql.FieldLT(FieldConversionRate, v))
}

// ConversionRateLTE applies the LTE predicate on the "conversion_rate" field.
func ConversionRateLTE(v float64) predicate.Journey {
	return predicate.Journey(sql.FieldLTE(FieldConversionRate, v))
}

// AvgDurationMsEQ applies the EQ predicate on the "avg_duration_ms" field.
func AvgDurationMsEQ(v int64) predicate.Journey {
	return predicate.Journey(sql.FieldEQ(FieldAvgDurationMs, v))
}

// AvgDurationMsNEQ applies the NEQ predicate on the "avg_duration_ms" field.
func AvgDurationMsNEQ(v int64) predicate.Journey {
	return predicate.Journey(sql.FieldNEQ(FieldAvgDurationMs, v))
}

// AvgDurationMsIn applies the In predicate on the "avg_duration_ms" field.
func AvgDurationMsIn(vs ...int64) predicate.Journey {
	return predicate.Journey(sql.FieldIn(FieldAvgDurationMs, vs...))
}

// AvgDurationMsNotIn applies the NotIn predicate on the "avg_duration_ms" field.
func AvgDurationMsNotIn(vs ...int64) predicate.Journey {
	return predicate.Journey(sql.FieldNotIn(FieldAvgDurationMs, vs...))
}

// AvgDurationMsGT applies the GT predicate on the "avg_duration_ms" field.
func AvgDurationMsGT(v int64) predicate.Journey {
	return predicate.Journey(sql.FieldGT(FieldAvgDurationMs, v))
}

// AvgDurationMsGTE applies the GTE predicate on the "avg_duration_ms" field.
func AvgDurationMsGTE(v int64) predicate.Journey {
	return predicate.Journey(sql.FieldGTE(FieldAvgDurationMs, v))
}

// AvgDurationMsLT applies the LT predicate on the "avg_duration_ms" field.
func AvgDurationMsLT(v int64) predicate.Journey {
	return predicate.Journey(sql.FieldLT(FieldAvgDurationMs, v))
}

// AvgDurationMsLTE applies the LTE predicate on the "avg_duration_ms" field.
func AvgDurationMsLTE(v int64) predicate.Journey {
	return predicate.Journey(sql.FieldLTE(FieldAvgDurationMs, v))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.Journey {
	return predicate.Journey(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.Journey {
	return predicate.Journey(sql.FieldNEQ(FieldIsActive, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Journey {
	return predicate.Journey(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Journey {
	return predicate.Journey(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Journey {
	return predicate.Journey(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Journey {
	return predicate.Journey(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Journey {
	return predicate.Journey(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Journey {
	return predicate.Journey(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Journey {
	return predicate.Journey(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Journey {
	return predicate.Journey(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Journey {
	return predicate.Journey(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Journey {
	return predicate.Journey(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Journey {
	return predicate.Journey(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Journey {
	return predicate.Journey(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Journey {
	return predicate.Journey(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Journey {
	return predicate.Journey(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Journey {
	return predicate.Journey(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Journey {
	return predicate.Journey(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasProduct applies the HasEdge predicate on the "product" edge.
func HasProduct() predicate.Journey {
	return predicate.Journey(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProductTable, ProductColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProductWith applies the HasEdge predicate on the "product" edge with a given conditions (other predicates).
func HasProductWith(preds ...predicate.Product) predicate.Journey {
	return predicate.Journey(func(s *sql.Selector) {
		step := newProductStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasFeature applies the HasEdge predicate on the "feature" edge.
func HasFeature() predicate.Journey {
	return predicate.Journey(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, FeatureTable, FeatureColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFeatureWith applies the HasEdge predicate on the "feature" edge with a given conditions (other predicates).
func HasFeatureWith(preds ...predicate.Feature) predicate.Journey {
	return predicate.Journey(func(s *sql.Selector) {
		step := newFeatureStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEvents applies the HasEdge predicate on the "events" edge.
func HasEvents() predicate.Journey {
	return predicate.Journey(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, EventsTable, EventsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEventsWith applies the HasEdge predicate on the "events" edge with a given conditions (other predicates).
func HasEventsWith(preds ...predicate.Event) predicate.Journey {
	return predicate.Journey(func(s *sql.Selector) {
		step := newEventsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSessions applies the HasEdge predicate on the "sessions" edge.
func HasSessions() predicate.Journey {
	return predicate.Journey(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SessionsTable, SessionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSessionsWith applies the HasEdge predicate on the "sessions" edge with a given conditions (other predicates).
func HasSessionsWith(preds ...predicate.Session) predicate.Journey {
	return predicate.Journey(func(s *sql.Selector) {
		step := newSessionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Journey) predicate.Journey {
	return predicate.Journey(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Journey) predicate.Journey {
	return predicate.Journey(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Journey) predicate.Journey {
	return predicate.Journey(sql.NotPredicates(p))
}
